; little-little-man — an interpreter for the LLM language.
; GENERATED by randomfun2026solvers.llm_lm1; do not hand-edit.
; cells are one to a slot.

.equ W      1    ; program width
.equ H      2    ; program height
.equ NMEN   3    ; men found, 1..3
.equ NP     4    ; pipes found, 0..2
.equ NROOM  5    ; rooms found, 1..3
.equ NRUN   6    ; candidate horizontal wall runs
.equ NSRC   7    ; pipe source arrowheads found
.equ STOP   8    ; a wall freeze or the last H: nothing runs after this
.equ NHALT  105  ; men halted on an H
.equ K      9    ; interpreted ticks left this round
.equ CA     10   ; cell cursor: display address
.equ CX     11   ; cell cursor: column
.equ CY     12   ; cell cursor: row
.equ BY     13   ; the input byte
.equ CLS    14   ; the class being computed / dispatched
.equ COL    106  ; the colour being painted
.equ PLUSX  15   ; column of the last '+' in this row, or -1
.equ CLEAN  107  ; every cell since that '+' was a '-'
.equ LIMIT  16   ; 16 * H — one past the last live display address
.equ RET    108  ; return site for the room_kind subroutine
.equ RKX    17   ; room_kind argument: column
.equ RKY    18   ; room_kind argument: row
.equ KIND   109  ; room_kind result: 0 outside, 1 inside, 2 wall
.equ RIDX   110  ; room_kind result: which room, or -1
.equ RI     19   ; room_kind's loop cursor
.equ T0     20   
.equ T1     21   
.equ T2     22   
.equ T3     111  
.equ T4     23   
.equ JDX    112  ; second array cursor, for the run pairing's inner loop
.equ PKEY   24   ; the (x0, x1) key of the run being paired
.equ PY0    113  ; the row of the run being paired
.equ PX0    25   ; unpacked x0 of a candidate room
.equ PX1    114  ; unpacked x1 of a candidate room
.equ FCLS   115  ; the final class the pipe walk writes for the cell it is on
.equ CP0    116  ; packed cell access scratch — never touched by callers
.equ CP1    117  
.equ CP2    118  
.equ C20    26   ; the encoded wall class, for stamping with MOVA
.equ CZ     27   ; the constant 0, for clearing with MOVA
.equ IDX    28   ; generic array cursor
.equ VAL    29   ; generic value staged for an indexed write
.equ NEWHI  30   ; pipe shift: highest occupied cell after the pass
.equ NEWLO  119  ; pipe shift: lowest occupied cell after the pass
.equ BEST   31   ; s/r: the pipe chosen, or -1
.equ BESTD  120  ; s/r: its Manhattan distance
.equ BESTA  121  ; s/r: its arrowhead address, for the reading-order tie
.equ PICKM  122  ; pick(): 0 = outgoing pipes for an s, 1 = incoming for an r
.equ PICKR  123  ; pick(): the room the man is in
.equ PICKA  124  ; pick(): the man's cell
.equ RET2   32   ; return site for pick()
.equ RUN    125  ; packed wall run: (y*16 + x0)*16 + x1 [8]
.equ RX0    133  ; room rectangles, inclusive [3]
.equ RY0    136  ;  [3]
.equ RX1    139  ;  [3]
.equ RY1    142  ;  [3]
.equ SRCA   145  ; pipe source arrowhead: display address [3]
.equ SRCD   148  ; its flow direction [3]
.equ SRCR   151  ; the room it leaves [3]
.equ MPOS   33   ; man: display address [3]
.equ MDIR   36   ; man: heading 0..3 [3]
.equ MA     154  ; man: register A [3]
.equ MB     157  ; man: register B [3]
.equ MHALT  39   ; man: halted on an H [3]
.equ MROOM  160  ; man: which room he lives in [3]
.equ MCLS   42   ; man: the class under him, read when he moved [3]
.equ MPIPE  163  ; man: the pipe his s/r bound to, cached [3]
.equ MPIPEA 166  ; man: the cell that cache is valid for, or -1 [3]
.equ PLEN   45   ; pipe: cells, so index len-1 is the destination [2]
.equ PBASE  47   ; pipe: its first slot in PCA/OCC [2]
.equ PSRC   169  ; pipe: source arrowhead address [2]
.equ PDST   171  ; pipe: destination arrowhead address [2]
.equ PSROOM 173  ; pipe: the room it leaves [2]
.equ PDROOM 175  ; pipe: the room it enters [2]
.equ PLO    49   ; pipe: lowest maybe-occupied cell [2]
.equ PHI    177  ; pipe: highest maybe-occupied cell [2]
.equ PCNT   51   ; pipe: values in flight [2]
.equ DTAB   179  ; address delta per heading: -16, +1, +16, -1 [4]
.equ PCA    183  ; pipe cell display addresses, flow order [20]
.equ OCC    203  ; 0 empty, else value + 10 [20]
.equ CELL   223  ; the program grid, one class a cell [256]

        JMP   setup           ; the ROM starts here; setup runs once and falls into round

; ── one round: k ticks, then one committed frame ──────────────────────
round:
        IN                    ; k
        ST    K
tick:
        LD    STOP            ; a wall freeze, or every man home on an H: pipes stop too
        BRZ   tk_go
        JMP   commit
tk_go:
        LD    K
        BRZ   commit

; ── pipe 0: shift the occupied window down from its head ──────────────
        LDI   0
        SUB   NP
        BRN   sh_go0
        JMP   sh_done0
sh_go0:
        LD    51
        BRZ   sh_done0        ; nothing in flight
        LD    177
        ST    IDX
        LDI   0
        SUBI  1
        ST    NEWHI
        LDI   0
        ST    NEWLO
        LD    45              ; T2 = the destination cell's local index
        SUBI  1
        ST    T2
sh_loop0:
        LD    IDX
        SUB   49
        BRN   sh_end0
        LD    47              ; T4 = the slot this cell lives in
        ADD   IDX
        ST    T4
        LD    T4
        ADDI  OCC
        LDA  
        ST    T0
        BRZ   sh_step0        ; empty
        LD    IDX
        SUB   T2
        BRZ   sh_stay0        ; the destination cell never advances
        LD    T4
        ADDI  1
        ST    VAL
        LD    VAL
        ADDI  OCC
        LDA  
        BRZ   sh_move0
        JMP   sh_stay0        ; the cell ahead is still occupied
sh_move0:
        LD    VAL
        ADDI  OCC
        MOVA  T0
        LD    T4
        ADDI  OCC
        MOVA  CZ
        LD    T4              ; the vacated cell goes back to plain pipe
        ADDI  PCA
        LDA  
        DSPA 
        LDI   6
        DSPD 
        LD    VAL
        ADDI  PCA
        LDA  
        DSPA 
        LDI   14
        DSPD 
        LD    IDX
        ADDI  1
        ST    T1
        JMP   sh_rec0
sh_stay0:
        LD    IDX
        ST    T1
sh_rec0:
        LD    NEWHI
        BRN   sh_hi0
        JMP   sh_lo0
sh_hi0:
        LD    T1              ; the first value found is the new head
        ST    NEWHI
sh_lo0:
        LD    T1              ; the last one found is the new tail
        ST    NEWLO
sh_step0:
        LD    IDX
        SUBI  1
        ST    IDX
        JMP   sh_loop0
sh_end0:
        LD    NEWHI
        BRN   sh_heal0
        LD    NEWHI
        ST    177
        LD    NEWLO
        ST    49
        JMP   sh_done0
sh_heal0:
        LD    T2              ; the window was stale: widen it and let the next pass tighten
        ST    177
        LDI   0
        ST    49
sh_done0:

; ── pipe 1: shift the occupied window down from its head ──────────────
        LDI   1
        SUB   NP
        BRN   sh_go1
        JMP   sh_done1
sh_go1:
        LD    52
        BRZ   sh_done1        ; nothing in flight
        LD    178
        ST    IDX
        LDI   0
        SUBI  1
        ST    NEWHI
        LDI   0
        ST    NEWLO
        LD    46              ; T2 = the destination cell's local index
        SUBI  1
        ST    T2
sh_loop1:
        LD    IDX
        SUB   50
        BRN   sh_end1
        LD    48              ; T4 = the slot this cell lives in
        ADD   IDX
        ST    T4
        LD    T4
        ADDI  OCC
        LDA  
        ST    T0
        BRZ   sh_step1        ; empty
        LD    IDX
        SUB   T2
        BRZ   sh_stay1        ; the destination cell never advances
        LD    T4
        ADDI  1
        ST    VAL
        LD    VAL
        ADDI  OCC
        LDA  
        BRZ   sh_move1
        JMP   sh_stay1        ; the cell ahead is still occupied
sh_move1:
        LD    VAL
        ADDI  OCC
        MOVA  T0
        LD    T4
        ADDI  OCC
        MOVA  CZ
        LD    T4              ; the vacated cell goes back to plain pipe
        ADDI  PCA
        LDA  
        DSPA 
        LDI   6
        DSPD 
        LD    VAL
        ADDI  PCA
        LDA  
        DSPA 
        LDI   14
        DSPD 
        LD    IDX
        ADDI  1
        ST    T1
        JMP   sh_rec1
sh_stay1:
        LD    IDX
        ST    T1
sh_rec1:
        LD    NEWHI
        BRN   sh_hi1
        JMP   sh_lo1
sh_hi1:
        LD    T1              ; the first value found is the new head
        ST    NEWHI
sh_lo1:
        LD    T1              ; the last one found is the new tail
        ST    NEWLO
sh_step1:
        LD    IDX
        SUBI  1
        ST    IDX
        JMP   sh_loop1
sh_end1:
        LD    NEWHI
        BRN   sh_heal1
        LD    NEWHI
        ST    178
        LD    NEWLO
        ST    50
        JMP   sh_done1
sh_heal1:
        LD    T2              ; the window was stale: widen it and let the next pass tighten
        ST    178
        LDI   0
        ST    50
sh_done1:

; ── man 0 ─────────────────────────────────────────────────────────────
        LDI   0
        SUB   NMEN
        BRN   m_go0
        JMP   m_done0
m_go0:
        LD    39
        BRZ   m_live0
        JMP   m_done0
m_live0:
        LD    42
        MODI  32
        ST    CLS
        SUBI  10
        BRN   m_digit0        ; 0..9: A = the digit
        BRZ   m_move0         ; 10: space
        SUBI  1
        BRZ   m_mov0          ; 11: M
        SUBI  1
        BRZ   m_add0          ; 12: +
        SUBI  1
        BRZ   m_sub0          ; 13: -
        SUBI  1
        BRZ   m_turn0         ; 14: X
        SUBI  1
        BRZ   m_halt0         ; 15: H
        SUBI  5
        BRN   m_dir0          ; 16..19: a heading
        SUBI  1
        BRZ   m_send0         ; 21: s
        SUBI  1
        BRZ   m_recv0         ; 22: r
        JMP   m_move0         ; a wall or a pipe cell cannot be under a live man
m_digit0:
        LD    CLS
        ST    154
        JMP   m_move0
m_mov0:
        LD    154
        ST    157
        JMP   m_move0
m_add0:
        LD    154
        ADD   157
        ST    154
        JMP   m_move0
m_sub0:
        LD    154
        SUB   157
        ST    154
        JMP   m_move0
m_dir0:
        LD    CLS
        SUBI  16
        ST    36
        JMP   m_move0
m_turn0:
        LD    154             ; X turns by sign(A)
        BRZ   m_move0
        BRN   m_ccw0
        LD    36
        ADDI  1
        MODI  4
        ST    36
        JMP   m_move0
m_ccw0:
        LD    36
        SUBI  1
        MODI  4
        ST    36
        JMP   m_move0
m_halt0:
        LDI   1               ; H: he stays here forever
        ST    39
        LD    NHALT
        ADDI  1
        ST    NHALT
        SUB   NMEN            ; the last man home stops the program
        BRZ   m_last0
        JMP   m_done0
m_last0:
        LDI   1
        ST    STOP
        JMP   m_done0
m_send0:
        LD    166             ; which pipe this cell binds to never changes, so cache it
        SUB   33
        BRZ   m_send_hit0
        LDI   0
        ST    PICKM
        LD    160
        ST    PICKR
        LD    33
        ST    PICKA
        LDI   0
        ST    RET2
        JMP   pick
pk_ret0:
        LD    BEST
        ST    163
        LD    33
        ST    166
        JMP   m_send_go0
m_send_hit0:
        LD    163
        ST    BEST
m_send_go0:
        LD    BEST
        BRN   m_move0         ; no outgoing pipe: nothing a well-formed program can do
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4              ; the source cell is local index 0
        LD    T4
        ADDI  OCC
        LDA  
        BRZ   m_send_ok0
        JMP   m_done0         ; the pipe's first cell is full: he blocks on the s
m_send_ok0:
        LD    154
        ADDI  10
        ST    VAL
        LD    T4
        ADDI  OCC
        MOVA  VAL
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   14
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        ST    T0
        ADDI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        LD    BEST
        ADDI  PLO
        MOVA  CZ
        LD    T0
        BRZ   m_send_hi0
        JMP   m_move0
m_send_hi0:
        LD    BEST            ; the pipe was empty, so cell 0 is also its head
        ADDI  PHI
        MOVA  CZ
        JMP   m_move0
m_recv0:
        LD    166             ; which pipe this cell binds to never changes, so cache it
        SUB   33
        BRZ   m_recv_hit0
        LDI   1
        ST    PICKM
        LD    160
        ST    PICKR
        LD    33
        ST    PICKA
        LDI   1
        ST    RET2
        JMP   pick
pk_ret1:
        LD    BEST
        ST    163
        LD    33
        ST    166
        JMP   m_recv_go0
m_recv_hit0:
        LD    163
        ST    BEST
m_recv_go0:
        LD    BEST
        BRN   m_move0         ; no incoming pipe
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4
        LD    BEST
        ADDI  PLEN
        LDA  
        SUBI  1
        ADD   T4
        ST    T4              ; the destination cell
        LD    T4
        ADDI  OCC
        LDA  
        ST    T0
        BRZ   m_done0         ; nothing has arrived: he blocks on the r
        SUBI  10
        ST    154
        LD    T4
        ADDI  OCC
        MOVA  CZ
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   6
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        SUBI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        JMP   m_move0
m_move0:
        LD    33              ; repaint the cell he leaves with the colour of the class under it
        DSPA 
        LD    42
        DIVI  32
        DSPD 
        LD    36
        ADDI  DTAB
        LDA  
        ST    T0
        LD    33
        ADD   T0
        ST    33
        DSPA 
        LDI   9
        DSPD 
        LD    33
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS             ; keep it for the next tick's dispatch, and test it for a wall
        ST    42
        SUBI  148
        BRZ   m_wall0
        JMP   m_done0
m_wall0:
        LDI   1               ; this tick still completes; nothing after it does
        ST    STOP
m_done0:

; ── man 1 ─────────────────────────────────────────────────────────────
        LDI   1
        SUB   NMEN
        BRN   m_go1
        JMP   m_done1
m_go1:
        LD    40
        BRZ   m_live1
        JMP   m_done1
m_live1:
        LD    43
        MODI  32
        ST    CLS
        SUBI  10
        BRN   m_digit1        ; 0..9: A = the digit
        BRZ   m_move1         ; 10: space
        SUBI  1
        BRZ   m_mov1          ; 11: M
        SUBI  1
        BRZ   m_add1          ; 12: +
        SUBI  1
        BRZ   m_sub1          ; 13: -
        SUBI  1
        BRZ   m_turn1         ; 14: X
        SUBI  1
        BRZ   m_halt1         ; 15: H
        SUBI  5
        BRN   m_dir1          ; 16..19: a heading
        SUBI  1
        BRZ   m_send1         ; 21: s
        SUBI  1
        BRZ   m_recv1         ; 22: r
        JMP   m_move1         ; a wall or a pipe cell cannot be under a live man
m_digit1:
        LD    CLS
        ST    155
        JMP   m_move1
m_mov1:
        LD    155
        ST    158
        JMP   m_move1
m_add1:
        LD    155
        ADD   158
        ST    155
        JMP   m_move1
m_sub1:
        LD    155
        SUB   158
        ST    155
        JMP   m_move1
m_dir1:
        LD    CLS
        SUBI  16
        ST    37
        JMP   m_move1
m_turn1:
        LD    155             ; X turns by sign(A)
        BRZ   m_move1
        BRN   m_ccw1
        LD    37
        ADDI  1
        MODI  4
        ST    37
        JMP   m_move1
m_ccw1:
        LD    37
        SUBI  1
        MODI  4
        ST    37
        JMP   m_move1
m_halt1:
        LDI   1               ; H: he stays here forever
        ST    40
        LD    NHALT
        ADDI  1
        ST    NHALT
        SUB   NMEN            ; the last man home stops the program
        BRZ   m_last1
        JMP   m_done1
m_last1:
        LDI   1
        ST    STOP
        JMP   m_done1
m_send1:
        LD    167             ; which pipe this cell binds to never changes, so cache it
        SUB   34
        BRZ   m_send_hit1
        LDI   0
        ST    PICKM
        LD    161
        ST    PICKR
        LD    34
        ST    PICKA
        LDI   2
        ST    RET2
        JMP   pick
pk_ret2:
        LD    BEST
        ST    164
        LD    34
        ST    167
        JMP   m_send_go1
m_send_hit1:
        LD    164
        ST    BEST
m_send_go1:
        LD    BEST
        BRN   m_move1         ; no outgoing pipe: nothing a well-formed program can do
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4              ; the source cell is local index 0
        LD    T4
        ADDI  OCC
        LDA  
        BRZ   m_send_ok1
        JMP   m_done1         ; the pipe's first cell is full: he blocks on the s
m_send_ok1:
        LD    155
        ADDI  10
        ST    VAL
        LD    T4
        ADDI  OCC
        MOVA  VAL
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   14
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        ST    T0
        ADDI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        LD    BEST
        ADDI  PLO
        MOVA  CZ
        LD    T0
        BRZ   m_send_hi1
        JMP   m_move1
m_send_hi1:
        LD    BEST            ; the pipe was empty, so cell 0 is also its head
        ADDI  PHI
        MOVA  CZ
        JMP   m_move1
m_recv1:
        LD    167             ; which pipe this cell binds to never changes, so cache it
        SUB   34
        BRZ   m_recv_hit1
        LDI   1
        ST    PICKM
        LD    161
        ST    PICKR
        LD    34
        ST    PICKA
        LDI   3
        ST    RET2
        JMP   pick
pk_ret3:
        LD    BEST
        ST    164
        LD    34
        ST    167
        JMP   m_recv_go1
m_recv_hit1:
        LD    164
        ST    BEST
m_recv_go1:
        LD    BEST
        BRN   m_move1         ; no incoming pipe
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4
        LD    BEST
        ADDI  PLEN
        LDA  
        SUBI  1
        ADD   T4
        ST    T4              ; the destination cell
        LD    T4
        ADDI  OCC
        LDA  
        ST    T0
        BRZ   m_done1         ; nothing has arrived: he blocks on the r
        SUBI  10
        ST    155
        LD    T4
        ADDI  OCC
        MOVA  CZ
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   6
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        SUBI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        JMP   m_move1
m_move1:
        LD    34              ; repaint the cell he leaves with the colour of the class under it
        DSPA 
        LD    43
        DIVI  32
        DSPD 
        LD    37
        ADDI  DTAB
        LDA  
        ST    T0
        LD    34
        ADD   T0
        ST    34
        DSPA 
        LDI   9
        DSPD 
        LD    34
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS             ; keep it for the next tick's dispatch, and test it for a wall
        ST    43
        SUBI  148
        BRZ   m_wall1
        JMP   m_done1
m_wall1:
        LDI   1               ; this tick still completes; nothing after it does
        ST    STOP
m_done1:

; ── man 2 ─────────────────────────────────────────────────────────────
        LDI   2
        SUB   NMEN
        BRN   m_go2
        JMP   m_done2
m_go2:
        LD    41
        BRZ   m_live2
        JMP   m_done2
m_live2:
        LD    44
        MODI  32
        ST    CLS
        SUBI  10
        BRN   m_digit2        ; 0..9: A = the digit
        BRZ   m_move2         ; 10: space
        SUBI  1
        BRZ   m_mov2          ; 11: M
        SUBI  1
        BRZ   m_add2          ; 12: +
        SUBI  1
        BRZ   m_sub2          ; 13: -
        SUBI  1
        BRZ   m_turn2         ; 14: X
        SUBI  1
        BRZ   m_halt2         ; 15: H
        SUBI  5
        BRN   m_dir2          ; 16..19: a heading
        SUBI  1
        BRZ   m_send2         ; 21: s
        SUBI  1
        BRZ   m_recv2         ; 22: r
        JMP   m_move2         ; a wall or a pipe cell cannot be under a live man
m_digit2:
        LD    CLS
        ST    156
        JMP   m_move2
m_mov2:
        LD    156
        ST    159
        JMP   m_move2
m_add2:
        LD    156
        ADD   159
        ST    156
        JMP   m_move2
m_sub2:
        LD    156
        SUB   159
        ST    156
        JMP   m_move2
m_dir2:
        LD    CLS
        SUBI  16
        ST    38
        JMP   m_move2
m_turn2:
        LD    156             ; X turns by sign(A)
        BRZ   m_move2
        BRN   m_ccw2
        LD    38
        ADDI  1
        MODI  4
        ST    38
        JMP   m_move2
m_ccw2:
        LD    38
        SUBI  1
        MODI  4
        ST    38
        JMP   m_move2
m_halt2:
        LDI   1               ; H: he stays here forever
        ST    41
        LD    NHALT
        ADDI  1
        ST    NHALT
        SUB   NMEN            ; the last man home stops the program
        BRZ   m_last2
        JMP   m_done2
m_last2:
        LDI   1
        ST    STOP
        JMP   m_done2
m_send2:
        LD    168             ; which pipe this cell binds to never changes, so cache it
        SUB   35
        BRZ   m_send_hit2
        LDI   0
        ST    PICKM
        LD    162
        ST    PICKR
        LD    35
        ST    PICKA
        LDI   4
        ST    RET2
        JMP   pick
pk_ret4:
        LD    BEST
        ST    165
        LD    35
        ST    168
        JMP   m_send_go2
m_send_hit2:
        LD    165
        ST    BEST
m_send_go2:
        LD    BEST
        BRN   m_move2         ; no outgoing pipe: nothing a well-formed program can do
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4              ; the source cell is local index 0
        LD    T4
        ADDI  OCC
        LDA  
        BRZ   m_send_ok2
        JMP   m_done2         ; the pipe's first cell is full: he blocks on the s
m_send_ok2:
        LD    156
        ADDI  10
        ST    VAL
        LD    T4
        ADDI  OCC
        MOVA  VAL
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   14
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        ST    T0
        ADDI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        LD    BEST
        ADDI  PLO
        MOVA  CZ
        LD    T0
        BRZ   m_send_hi2
        JMP   m_move2
m_send_hi2:
        LD    BEST            ; the pipe was empty, so cell 0 is also its head
        ADDI  PHI
        MOVA  CZ
        JMP   m_move2
m_recv2:
        LD    168             ; which pipe this cell binds to never changes, so cache it
        SUB   35
        BRZ   m_recv_hit2
        LDI   1
        ST    PICKM
        LD    162
        ST    PICKR
        LD    35
        ST    PICKA
        LDI   5
        ST    RET2
        JMP   pick
pk_ret5:
        LD    BEST
        ST    165
        LD    35
        ST    168
        JMP   m_recv_go2
m_recv_hit2:
        LD    165
        ST    BEST
m_recv_go2:
        LD    BEST
        BRN   m_move2         ; no incoming pipe
        LD    BEST
        ADDI  PBASE
        LDA  
        ST    T4
        LD    BEST
        ADDI  PLEN
        LDA  
        SUBI  1
        ADD   T4
        ST    T4              ; the destination cell
        LD    T4
        ADDI  OCC
        LDA  
        ST    T0
        BRZ   m_done2         ; nothing has arrived: he blocks on the r
        SUBI  10
        ST    156
        LD    T4
        ADDI  OCC
        MOVA  CZ
        LD    T4
        ADDI  PCA
        LDA  
        DSPA 
        LDI   6
        DSPD 
        LD    BEST
        ADDI  PCNT
        LDA  
        SUBI  1
        ST    T1
        LD    BEST
        ADDI  PCNT
        MOVA  T1
        JMP   m_move2
m_move2:
        LD    35              ; repaint the cell he leaves with the colour of the class under it
        DSPA 
        LD    44
        DIVI  32
        DSPD 
        LD    38
        ADDI  DTAB
        LDA  
        ST    T0
        LD    35
        ADD   T0
        ST    35
        DSPA 
        LDI   9
        DSPD 
        LD    35
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS             ; keep it for the next tick's dispatch, and test it for a wall
        ST    44
        SUBI  148
        BRZ   m_wall2
        JMP   m_done2
m_wall2:
        LDI   1               ; this tick still completes; nothing after it does
        ST    STOP
m_done2:
        LD    K               ; one interpreted tick done
        SUBI  1
        ST    K
        JMP   tick
commit:
        LDI   1               ; SWAP 1: commit, keep both buffers, so the next frame is a delta
        DSPS 
        JMP   round

; ── pick(PICKM, PICKR, PICKA) -> BEST: the pipe an s or an r talks to ───
pick:
        LDI   0
        SUBI  1
        ST    BEST
        LDI   0
        ST    BESTD
        LDI   0
        ST    BESTA
        LDI   0
        ST    IDX
pk_loop:
        LD    IDX
        SUB   NP
        BRN   pk_go
        JMP   pk_ret
pk_go:
        LD    PICKM
        BRZ   pk_send
        LD    IDX
        ADDI  PDROOM
        LDA  
        ST    T0
        LD    IDX
        ADDI  PDST
        LDA  
        ST    T1
        JMP   pk_have
pk_send:
        LD    IDX
        ADDI  PSROOM
        LDA  
        ST    T0
        LD    IDX
        ADDI  PSRC
        LDA  
        ST    T1
pk_have:
        LD    T0
        SUB   PICKR
        BRZ   pk_cand
        JMP   pk_next         ; not attached to his room
pk_cand:
        LD    PICKA           ; |dx|
        MODI  16
        ST    T2
        LD    T1
        MODI  16
        ST    T3
        LD    T2
        SUB   T3
        ST    T4
        BRN   pk_negx
        JMP   pk_dy
pk_negx:
        LDI   0
        SUB   T4
        ST    T4
pk_dy:
        LD    PICKA           ; |dy|
        DIVI  16
        ST    T2
        LD    T1
        DIVI  16
        ST    T3
        LD    T2
        SUB   T3
        ST    T2
        BRN   pk_negy
        JMP   pk_sum
pk_negy:
        LDI   0
        SUB   T2
        ST    T2
pk_sum:
        LD    T4
        ADD   T2
        ST    T4              ; the Manhattan distance
        LD    BEST
        BRN   pk_take         ; first candidate
        LD    T4
        SUB   BESTD
        BRN   pk_take
        BRZ   pk_tie
        JMP   pk_next
pk_tie:
        LD    T1
        SUB   BESTA
        BRN   pk_take         ; same distance: earlier in reading order wins
        JMP   pk_next
pk_take:
        LD    IDX
        ST    BEST
        LD    T4
        ST    BESTD
        LD    T1
        ST    BESTA
pk_next:
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   pk_loop
pk_ret:
        LD    RET2
        SUBI  0
        BRZ   pk_ret0
        LD    RET2
        SUBI  1
        BRZ   pk_ret1
        LD    RET2
        SUBI  2
        BRZ   pk_ret2
        LD    RET2
        SUBI  3
        BRZ   pk_ret3
        LD    RET2
        SUBI  4
        BRZ   pk_ret4
        JMP   pk_ret5

; ── pass 1: W H, then W*H bytes -> CELL, wall runs, men ───────────────
setup:
        IN                    ; W
        ST    W
        IN                    ; H
        ST    H
        LDI   0
        ST    NMEN
        ST    NP
        ST    NROOM
        ST    NRUN
        ST    NSRC
        ST    STOP
        ST    NHALT
        ST    CZ
        ST    CA
        ST    CY
        LDI   148
        ST    C20
        LD    H               ; LIMIT = 16 * H: one past the last live display address
        MULI  16
        ST    LIMIT
        LDI   0               ; DTAB[0]
        SUBI  16
        ST    179
        LDI   1
        ST    180
        LDI   16
        ST    181
        LDI   0
        SUBI  1
        ST    182
        LDI   0               ; home the cursor: pass 1 paints in address order, so DATA advances it
        DSPA 
p1_row:
        LDI   0
        ST    CX
        LDI   0               ; no '+' seen in this row yet
        SUBI  1
        ST    PLUSX
        LDI   0
        ST    CLEAN
p1_cell:
        LD    CX
        SUB   W
        BRN   p1_cell_go
        JMP   p1_row_end
p1_cell_go:
        IN   
        ST    BY
        LD    BY              ; classify: one cumulative SUBI chain, commonest glyphs first
        SUBI  32
        BRZ   cl1             ; ' '
        SUBI  11
        BRZ   cl_plus14       ; '+' 43
        SUBI  2
        BRZ   cl_minus15      ; '-' 45
        SUBI  1
        BRZ   cl2             ; '.' 46
        SUBI  2
        BRN   cl_other18      ; below '0'
        SUBI  9
        BRN   cl_digit16      ; '0'..'8'
        BRZ   cl_digit16      ; '9'
        LD    BY
        SUBI  60
        BRZ   cl3             ; '<' 60
        SUBI  2
        BRZ   cl4             ; '>' 62
        SUBI  2
        BRZ   cl_at17         ; '@' 64
        SUBI  8
        BRZ   cl5             ; 'H' 72
        SUBI  5
        BRZ   cl6             ; 'M' 77
        SUBI  9
        BRZ   cl7             ; 'V' 86
        SUBI  2
        BRZ   cl8             ; 'X' 88
        SUBI  6
        BRZ   cl9             ; '^' 94
        SUBI  20
        BRZ   cl10            ; 'r' 114
        SUBI  1
        BRZ   cl11            ; 's' 115
        SUBI  3
        BRZ   cl12            ; 'v' 118
        SUBI  6
        BRZ   cl13            ; '|' 124
        JMP   cl_other18
cl1:
        LDI   10
        ST    CLS
        JMP   p1_dirty
cl2:
        LDI   10
        ST    CLS
        JMP   p1_dirty
cl3:
        LDI   115
        ST    CLS
        JMP   p1_dirty
cl4:
        LDI   113
        ST    CLS
        JMP   p1_dirty
cl5:
        LDI   111
        ST    CLS
        JMP   p1_dirty
cl6:
        LDI   395
        ST    CLS
        JMP   p1_dirty
cl7:
        LDI   114
        ST    CLS
        JMP   p1_dirty
cl8:
        LDI   110
        ST    CLS
        JMP   p1_dirty
cl9:
        LDI   112
        ST    CLS
        JMP   p1_dirty
cl10:
        LDI   438
        ST    CLS
        JMP   p1_dirty
cl11:
        LDI   437
        ST    CLS
        JMP   p1_dirty
cl12:
        LDI   114
        ST    CLS
        JMP   p1_dirty
cl13:
        LDI   215
        ST    CLS
        JMP   p1_dirty
cl_other18:
        LDI   10
        ST    CLS
        JMP   p1_dirty
cl_digit16:
        LD    BY              ; digit: the class *is* the value, and every digit is colour 8
        SUBI  48
        ADDI  256
        ST    CLS
        JMP   p1_dirty
cl_at17:
        LDI   10              ; '@': empty space, but a man spawns here
        ST    CLS
        LD    NMEN
        SUBI  3
        BRZ   p1_dirty        ; more men than the problem allows: ignore
        LD    NMEN
        ADDI  MPOS
        MOVA  CA
        LD    NMEN
        ADDI  1
        ST    NMEN
        JMP   p1_dirty
cl_minus15:
        LDI   333             ; '-' continues a wall run
        ST    CLS
        JMP   p1_keep
cl_plus14:
        LDI   332
        ST    CLS
        LD    PLUSX           ; a run needs a previous '+' …
        BRN   run_skip19
        LD    CLEAN           ; … nothing but '-' since it …
        BRZ   run_skip19
        LD    CX              ; … and at least one cell between them
        SUB   PLUSX
        SUBI  2
        BRN   run_skip19
        LD    NRUN
        SUBI  8
        BRZ   run_skip19      ; run table full
        LD    CY              ; RUN = (y * 16 + x0) * 16 + x1
        MULI  16
        ADD   PLUSX
        MULI  16
        ADD   CX
        ST    T0
        LD    NRUN
        ADDI  RUN
        MOVA  T0
        LD    NRUN
        ADDI  1
        ST    NRUN
run_skip19:
        LD    CX              ; this '+' opens the next run
        ST    PLUSX
        LDI   1
        ST    CLEAN
        JMP   p1_keep
p1_dirty:
        LDI   0               ; any other glyph breaks a wall run
        ST    CLEAN
p1_keep:
        LD    CLS             ; the glyph's own colour; walls and pipe cells are repainted later
        DIVI  32
        DSPD 
        LD    CA
        ADDI  CELL
        MOVA  CLS
        LD    CA
        ADDI  1
        ST    CA
        LD    CX
        ADDI  1
        ST    CX
        JMP   p1_cell

; ── end of a row: the columns past W stay black, so only the cursor moves ───
p1_row_end:
        LD    CY
        ADDI  1
        ST    CY
        LD    CY              ; the next row starts at 16y, whatever W is
        MULI  16
        ST    CA
        LD    CY
        SUB   H
        BRN   p1_next_row
        JMP   p1_done
p1_next_row:
        LD    CA
        DSPA 
        JMP   p1_row

; ── pair wall runs into rooms; a pair is only a room if its columns are '|' ───
p1_done:
        LDI   0
        ST    IDX
pr_i:
        LD    IDX
        SUB   NRUN
        BRN   pr_i_go
        JMP   pr_done
pr_i_go:
        LD    IDX
        ADDI  RUN
        LDA  
        ST    T0
        BRN   pr_i_next       ; already paired
        MODI  256             ; PKEY = x0 * 16 + x1
        ST    PKEY
        LD    T0
        DIVI  256
        ST    PY0
        LD    IDX
        ADDI  1
        ST    JDX
pr_j:
        LD    JDX
        SUB   NRUN
        BRN   pr_j_go
        JMP   pr_i_next
pr_j_go:
        LD    JDX
        ADDI  RUN
        LDA  
        ST    T1
        BRN   pr_j_next
        MODI  256
        SUB   PKEY
        BRZ   pr_try          ; same (x0, x1): a candidate room
        JMP   pr_j_next
pr_try:
        LD    PKEY
        DIVI  16
        ST    PX0
        LD    PKEY
        MODI  16
        ST    PX1
        LD    T1
        DIVI  256
        ST    T2              ; y1
        LD    PY0             ; yy = y0 + 1
        ADDI  1
        ST    T3
pr_val:
        LD    T3
        SUB   T2
        BRN   pr_val_go
        JMP   pr_accept
pr_val_go:
        LD    T3              ; left column of the candidate
        MULI  16
        ST    T4
        ADD   PX0
        ST    VAL
        LD    VAL
        ADDI  CELL
        LDA  
        ST    T0
        LD    T0
        SUBI  215
        BRZ   pr_val_right
        JMP   pr_j_next       ; not a '|': these two runs are not a room
pr_val_right:
        LD    T4
        ADD   PX1
        ST    VAL
        LD    VAL
        ADDI  CELL
        LDA  
        ST    T0
        LD    T0
        SUBI  215
        BRZ   pr_val_next
        JMP   pr_j_next
pr_val_next:
        LD    T3
        ADDI  1
        ST    T3
        JMP   pr_val
pr_accept:
        LD    NROOM
        SUBI  3
        BRZ   pr_j_next       ; room table full
        LD    NROOM
        ADDI  RX0
        MOVA  PX0
        LD    NROOM
        ADDI  RY0
        MOVA  PY0
        LD    NROOM
        ADDI  RX1
        MOVA  PX1
        LD    NROOM
        ADDI  RY1
        MOVA  T2
        LD    NROOM
        ADDI  1
        ST    NROOM
        LDI   0               ; consume both runs
        SUBI  1
        ST    T0
        LD    IDX
        ADDI  RUN
        MOVA  T0
        LD    JDX
        ADDI  RUN
        MOVA  T0
        JMP   pr_i_next
pr_j_next:
        LD    JDX
        ADDI  1
        ST    JDX
        JMP   pr_j
pr_i_next:
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   pr_i

; ── stamp every room perimeter as class 20 — writes are nearly free ───
pr_done:
        LDI   0
        ST    IDX
st_room:
        LD    IDX
        SUB   NROOM
        BRN   st_room_go
        JMP   st_done
st_room_go:
        LD    IDX
        ADDI  RX0
        LDA  
        ST    T0
        LD    IDX
        ADDI  RY0
        LDA  
        ST    T1
        LD    IDX
        ADDI  RX1
        LDA  
        ST    T2
        LD    IDX
        ADDI  RY1
        LDA  
        ST    T3
        LD    T1              ; VAL walks the top wall, T4 the bottom
        MULI  16
        ADD   T0
        ST    VAL
        LD    T3
        MULI  16
        ADD   T0
        ST    T4
        LD    T0
        ST    JDX
st_top:
        LD    JDX
        SUB   T2
        SUBI  1
        BRN   st_top_go
        JMP   st_side_init
st_top_go:
        LD    VAL
        ADDI  CELL
        MOVA  C20
        LD    T4
        ADDI  CELL
        MOVA  C20
        LD    VAL
        DSPA 
        LDI   4
        DSPD 
        LD    T4
        DSPA 
        LDI   4
        DSPD 
        LD    VAL             ; probe -16 for an arrowhead heading 0
        SUBI  16
        ST    PKEY
        BRN   sp_skip20       ; off the top of the grid
        SUB   LIMIT
        BRN   sp_hit21_in
        JMP   sp_skip20       ; off the bottom
sp_hit21_in:
        LD    PKEY
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS
        SUBI  112
        BRZ   sp_hit21
        JMP   sp_skip20
sp_hit21:
        LD    NSRC
        SUBI  2
        BRZ   sp_skip20       ; more pipes than the problem allows
        LD    NSRC
        ADDI  SRCA
        MOVA  PKEY
        LDI   0
        ST    PX0
        LD    NSRC
        ADDI  SRCD
        MOVA  PX0
        LD    NSRC
        ADDI  SRCR
        MOVA  IDX
        LD    NSRC
        ADDI  1
        ST    NSRC
sp_skip20:
        LD    T4              ; probe +16 for an arrowhead heading 2
        ADDI  16
        ST    PKEY
        BRN   sp_skip22       ; off the top of the grid
        SUB   LIMIT
        BRN   sp_hit23_in
        JMP   sp_skip22       ; off the bottom
sp_hit23_in:
        LD    PKEY
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS
        SUBI  114
        BRZ   sp_hit23
        JMP   sp_skip22
sp_hit23:
        LD    NSRC
        SUBI  2
        BRZ   sp_skip22       ; more pipes than the problem allows
        LD    NSRC
        ADDI  SRCA
        MOVA  PKEY
        LDI   2
        ST    PX0
        LD    NSRC
        ADDI  SRCD
        MOVA  PX0
        LD    NSRC
        ADDI  SRCR
        MOVA  IDX
        LD    NSRC
        ADDI  1
        ST    NSRC
sp_skip22:
        LD    VAL
        ADDI  1
        ST    VAL
        LD    T4
        ADDI  1
        ST    T4
        LD    JDX
        ADDI  1
        ST    JDX
        JMP   st_top
st_side_init:
        LD    T1              ; VAL walks the left wall, T4 the right
        MULI  16
        ST    VAL
        ADD   T2
        ST    T4
        LD    VAL
        ADD   T0
        ST    VAL
        LD    T1
        ST    JDX
st_side:
        LD    JDX
        SUB   T3
        SUBI  1
        BRN   st_side_go
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   st_room
st_side_go:
        LD    VAL
        ADDI  CELL
        MOVA  C20
        LD    T4
        ADDI  CELL
        MOVA  C20
        LD    VAL
        DSPA 
        LDI   4
        DSPD 
        LD    T4
        DSPA 
        LDI   4
        DSPD 
        LD    VAL             ; probe -1 for an arrowhead heading 3
        SUBI  1
        ST    PKEY
        BRN   sp_skip24       ; off the top of the grid
        SUB   LIMIT
        BRN   sp_hit25_in
        JMP   sp_skip24       ; off the bottom
sp_hit25_in:
        LD    PKEY
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS
        SUBI  115
        BRZ   sp_hit25
        JMP   sp_skip24
sp_hit25:
        LD    NSRC
        SUBI  2
        BRZ   sp_skip24       ; more pipes than the problem allows
        LD    NSRC
        ADDI  SRCA
        MOVA  PKEY
        LDI   3
        ST    PX0
        LD    NSRC
        ADDI  SRCD
        MOVA  PX0
        LD    NSRC
        ADDI  SRCR
        MOVA  IDX
        LD    NSRC
        ADDI  1
        ST    NSRC
sp_skip24:
        LD    T4              ; probe +1 for an arrowhead heading 1
        ADDI  1
        ST    PKEY
        BRN   sp_skip26       ; off the top of the grid
        SUB   LIMIT
        BRN   sp_hit27_in
        JMP   sp_skip26       ; off the bottom
sp_hit27_in:
        LD    PKEY
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS
        SUBI  113
        BRZ   sp_hit27
        JMP   sp_skip26
sp_hit27:
        LD    NSRC
        SUBI  2
        BRZ   sp_skip26       ; more pipes than the problem allows
        LD    NSRC
        ADDI  SRCA
        MOVA  PKEY
        LDI   1
        ST    PX0
        LD    NSRC
        ADDI  SRCD
        MOVA  PX0
        LD    NSRC
        ADDI  SRCR
        MOVA  IDX
        LD    NSRC
        ADDI  1
        ST    NSRC
sp_skip26:
        LD    VAL
        ADDI  16
        ST    VAL
        LD    T4
        ADDI  16
        ST    T4
        LD    JDX
        ADDI  1
        ST    JDX
        JMP   st_side

; ── which room each man lives in — fixed for the whole run ────────────
st_done:
        LDI   0
        ST    IDX
mr_loop:
        LD    IDX
        SUB   NMEN
        BRN   mr_go
        JMP   mr_done
mr_go:
        LD    IDX
        ADDI  MPOS
        LDA  
        ST    T0
        MODI  16
        ST    RKX
        LD    T0
        DIVI  16
        ST    RKY
        LDI   0               ; room_kind, returning to site 0
        ST    RET
        JMP   room_kind
rk_ret0:
        LD    IDX
        ADDI  MROOM
        MOVA  RIDX
        LDI   10              ; his own '@' cell is empty space
        ST    T0
        LD    IDX
        ADDI  MCLS
        MOVA  T0
        LDI   1               ; and he starts facing east
        ST    T0
        LD    IDX
        ADDI  MDIR
        MOVA  T0
        LDI   0               ; his pipe cache is empty
        SUBI  1
        ST    T0
        LD    IDX
        ADDI  MPIPEA
        MOVA  T0
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   mr_loop
mr_done:

; ── walk the pipes: flow order, arrowheads re-aim, a wall ends it ─────
        LDI   0               ; next free slot in PCA/OCC
        ST    VAL
        LDI   0
        ST    IDX
pw_loop:
        LD    IDX
        SUB   NSRC
        BRN   pw_go
        JMP   pw_done
pw_go:
        LD    NP
        ADDI  PBASE
        MOVA  VAL
        LD    IDX
        ADDI  SRCA
        LDA  
        ST    T0              ; cur
        LD    NP
        ADDI  PSRC
        MOVA  T0
        LD    IDX
        ADDI  SRCD
        LDA  
        ST    T1              ; flow direction
        ADDI  216
        ST    FCLS            ; the source cell is an arrowhead
        LD    IDX
        ADDI  SRCR
        LDA  
        ST    T2
        LD    NP
        ADDI  PSROOM
        MOVA  T2
        LD    VAL             ; slot cursor
        ST    JDX
        LDI   0               ; cells so far
        ST    T3
pw_step:
        LD    T3
        SUBI  20
        BRN   pw_step_go
        JMP   pw_end          ; longer than the problem allows: stop here
pw_step_go:
        LD    JDX
        ADDI  PCA
        MOVA  T0
        LD    JDX
        ADDI  OCC
        MOVA  CZ
        LD    JDX
        ADDI  1
        ST    JDX
        LD    T3
        ADDI  1
        ST    T3
        LD    T0              ; this cell is a pipe cell after all
        ADDI  CELL
        MOVA  FCLS
        LD    T0
        DSPA 
        LDI   6
        DSPD 
        LD    T1
        ADDI  DTAB
        LDA  
        ST    T4
        LD    T0
        ADD   T4
        ST    PKEY            ; the next cell along the flow
        BRN   pw_end          ; off the grid: the program is not well formed
        SUB   LIMIT
        BRN   pw_in
        JMP   pw_end
pw_in:
        LD    PKEY
        ADDI  CELL
        LDA  
        ST    CLS
        LD    CLS             ; the next cell still carries its provisional class
        MODI  32
        ST    CLS
        SUBI  20
        BRZ   pw_end          ; a wall ends the walk
        LD    CLS
        SUBI  12
        BRN   pw_end          ; space or a digit: not a pipe, so the walk is over
        LD    CLS
        SUBI  16
        BRN   pw_body         ; '+' or '-' is a body
        LD    CLS
        SUBI  20
        BRN   pw_arrow        ; 16..19 re-aims the flow
        LD    CLS
        SUBI  23
        BRZ   pw_body         ; '|' is a body
        JMP   pw_end
pw_arrow:
        LD    CLS
        SUBI  16
        ST    T1
        ADDI  216
        ST    FCLS
        JMP   pw_next
pw_body:
        LDI   215
        ST    FCLS
pw_next:
        LD    PKEY
        ST    T0
        JMP   pw_step
pw_end:
        LD    NP
        ADDI  PDST
        MOVA  T0
        LD    NP
        ADDI  PLEN
        MOVA  T3
        LD    NP
        ADDI  PLO
        MOVA  CZ
        LD    NP
        ADDI  PCNT
        MOVA  CZ
        LDI   0               ; PHI < PLO means the pipe is empty
        SUBI  1
        ST    T4
        LD    NP
        ADDI  PHI
        MOVA  T4
        LD    VAL             ; the next pipe's cells start after this one's
        ADD   T3
        ST    VAL
        LD    PKEY            ; the wall the last arrowhead points into names the room
        MODI  16
        ST    RKX
        LD    PKEY
        DIVI  16
        ST    RKY
        LDI   1               ; room_kind, returning to site 1
        ST    RET
        JMP   room_kind
rk_ret1:
        LD    NP
        ADDI  PDROOM
        MOVA  RIDX
        LD    NP
        ADDI  1
        ST    NP
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   pw_loop
pw_done:

; ── the men, drawn over the cells they spawned on ─────────────────────
        LDI   0
        ST    IDX
pm_loop:
        LD    IDX
        SUB   NMEN
        BRN   pm_go
        JMP   pm_done
pm_go:
        LD    IDX
        ADDI  MPOS
        LDA  
        DSPA 
        LDI   9
        DSPD 
        LD    IDX
        ADDI  1
        ST    IDX
        JMP   pm_loop
pm_done:
        LDI   1               ; commit the opening frame; SWAP 1 keeps both buffers, so it is a base
        DSPS 
        JMP   round

; ── room_kind(RKX, RKY) -> KIND 0 outside / 1 inside / 2 wall, RIDX ───
room_kind:
        LDI   0
        ST    KIND
        LDI   0
        SUBI  1
        ST    RIDX
        LDI   0
        ST    RI
rk_loop:
        LD    RI
        SUB   NROOM
        BRN   rk_go
        JMP   rk_ret
rk_go:
        LD    RI
        ADDI  RX0
        LDA  
        ST    T0
        LD    RI
        ADDI  RX1
        LDA  
        ST    T1
        LD    RI
        ADDI  RY0
        LDA  
        ST    T2
        LD    RI
        ADDI  RY1
        LDA  
        ST    T3
        LD    RKX
        SUB   T0
        BRN   rk_next
        LD    T1
        SUB   RKX
        BRN   rk_next
        LD    RKY
        SUB   T2
        BRN   rk_next
        LD    T3
        SUB   RKY
        BRN   rk_next
        LD    RI              ; inside this room's bounding box
        ST    RIDX
        LDI   1
        ST    KIND
        LD    RKX
        SUB   T0
        BRZ   rk_wall
        LD    T1
        SUB   RKX
        BRZ   rk_wall
        LD    RKY
        SUB   T2
        BRZ   rk_wall
        LD    T3
        SUB   RKY
        BRZ   rk_wall
        JMP   rk_ret
rk_wall:
        LDI   2
        ST    KIND
        JMP   rk_ret
rk_next:
        LD    RI
        ADDI  1
        ST    RI
        JMP   rk_loop
rk_ret:
        LD    RET
        SUBI  0
        BRZ   rk_ret0
        JMP   rk_ret1
