#!/usr/bin/env python3
"""WAD level importer for deadman-3d: real DOOM-format geometry -> the 64x64 grid.

Two sources, one pipeline (see ``deadman3d.py`` for the consumer):

* **Freedoom mode** (``--freedoom DIR``): a checkout/snapshot of
  https://github.com/freedoom/freedoom (pinned commit ``d14dbbe``).  The level
  is ``levels/<map>.wad`` (a PWAD of just the map lumps), wall textures are
  composited from ``lumps/textures/textures.cfg`` + ``patches/*.png``, the
  title screen is ``graphics/titlepic/titlepic.png`` and the status bar is
  ``graphics/stbar.png`` (:func:`stbar_rows`).  Freedoom content is
  BSD-licensed (COPYING.adoc) — the committed deadman-3d map, wall families
  and title screen are generated by this mode.

* **IWAD mode** (``--wad PATH``): a retail-format IWAD (e.g. a DOOM shareware
  ``DOOM1.WAD``).  Everything comes from inside the WAD: map lumps,
  ``TEXTURE1``/``TEXTURE2`` + ``PNAMES`` + patch lumps (DOOM picture format)
  + ``PLAYPAL`` for wall colours, ``TITLEPIC`` for the title.  **Nothing
  derived from a retail IWAD may be committed** — outputs belong in a
  git-ignored directory (``littleman/examples/local/``).

The pipeline:

1. Parse the WAD directory (12-byte header, 16-byte directory entries) and the
   fixed-size little-endian map lumps: VERTEXES (4 bytes: x, y), LINEDEFS
   (14 bytes), SIDEDEFS (30 bytes), THINGS (10 bytes).
2. Rasterize: the level bbox is fitted (uniform scale, centred, one-cell
   border) onto a ``grid``x``grid`` map.  Every **one-sided** linedef at least
   ``min_len`` map units long becomes wall cells via an exact supercover
   traversal; two-sided linedefs (room-to-room joins, doorways) and shorter
   detail lines are ignored.  Each wall cell inherits its dominant linedef's
   sidedef texture (weighted by linedef length).
3. Close the map: the player start (THINGS type 1, bumped to the nearest open
   cell if its own cell caught a wall) seeds a 4-connected flood fill; the
   reachable region must not touch the grid border (watertightness — a
   supercover of the level's closed one-sided perimeter cannot be crossed),
   and every unreachable cell is filled solid, so the committed map has no
   void a ray could escape into.
4. Colour: each texture name that occurs on a wall cell maps to a wall family
   1..7 — the ANSI palette index of its average colour (patches composited,
   alpha-weighted).  Because most DOOM-era textures are desaturated, the
   family is chosen by *hue* (CIELAB, families 1..6) with a chroma gate below
   which the texture is gray (family 7); ties collapse identical-hue textures
   into one family, which is the <=7-group clustering.
5. Title: the 320x200 title art (PNG or TITLEPIC picture lump) is quantized to
   64x48 with the repo's block-Lab method — per target block, the ANSI-16
   colour minimizing the sum of CIELAB distances over the source block's
   pixels — after a fixed x1.6 brightness lift (DOOM-era title art is dark;
   measured on both sources), then a single isolated-dot despeckle pass.
6. Dithering (M9, **opt-in**): every quantizer takes ``dither=`` (default
   ``"none"`` — the method above, unchanged to the byte), selecting CIELAB
   Floyd–Steinberg or ordered Bayer 4x4/8x8 instead (:data:`DITHER_MODES`).
   Art ships as row-major RLE at one command word per run, so the price is
   measured with :func:`rom_words`; the hi-res panel constants
   (:data:`HIRES_W` x :data:`HIRES_H`) give a dither room to read as shading.

The output bundle (``--out DIR``) is ``level.json`` (map rows, spawn, heading,
title rows, the texture->family table) plus eyeball artifacts: ``map.txt``,
``title.txt``, ``overhead.png``, ``title.png``, ``families.txt``.

Stdlib only (struct + zlib carry the PNG codec) so the fast tests can cover
the parser on a synthetic in-memory WAD.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
import zlib
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path

__all__ = [
    "PALETTE", "Wad", "MapData", "Level", "DAMAGE_SPECIALS",
    "MONSTER_TYPES", "MAX_MONSTERS", "MON_BANDS",
    "pack_sprite_columns_wide", "HIRES_BANDS", "HIRES_GUN",
    "read_wad", "parse_map", "supercover", "rasterize",
    "decode_png", "decode_picture", "srgb_to_lab", "family_of",
    "quantize_title", "despeckle", "quantize_sprite", "sprite_runs",
    "quantize_monster", "pack_sprite_columns", "monster_band_words",
    "monster_sprite_words",
    "DITHER_MODES", "bayer_matrix", "block_lab", "dither_lab",
    "rle_runs", "rom_words",
    "HIRES_W", "HIRES_H", "HIRES_H3D", "HIRES_HUD_W", "HIRES_HUD_H", "face_box",
    "gun_tables", "face_tables", "iwad_art",
    "STBAR_REGIONS", "STBAR_MEAN_GREY", "stbar_cells", "stbar_rows",
    "iwad_stbar",
    "load_freedoom", "load_iwad", "emit", "main",
]

#: The LM-75 ANSI-16 palette (== deadman3d.PALETTE; kept local so the importer
#: never imports the consumer).
PALETTE = [
    (0, 0, 0), (170, 0, 0), (0, 170, 0), (170, 85, 0),
    (0, 0, 170), (170, 0, 170), (0, 170, 170), (170, 170, 170),
    (85, 85, 85), (255, 85, 85), (85, 255, 85), (255, 255, 85),
    (85, 85, 255), (255, 85, 255), (85, 255, 255), (255, 255, 255),
]

NO_SIDE = 0xFFFF  # a linedef with no left sidedef is one-sided (solid)


# ── WAD parsing ──────────────────────────────────────────────────────────────
@dataclass
class Wad:
    """A parsed WAD: the ordered lump directory."""

    ident: str
    lumps: list[tuple[str, bytes]]

    def lump(self, name: str) -> bytes:
        for n, data in self.lumps:
            if n == name:
                return data
        raise KeyError(f"no lump {name!r} in this {self.ident}")

    def __contains__(self, name: str) -> bool:
        return any(n == name for n, _ in self.lumps)


@dataclass
class MapData:
    """One map's fixed-size-record lumps, decoded."""

    vertexes: list[tuple[int, int]]
    #: (v1, v2, flags, special, tag, right_sidedef, left_sidedef)
    linedefs: list[tuple[int, int, int, int, int, int, int]]
    #: (upper, lower, middle, sector)
    sidedefs: list[tuple[str, str, str, int]]
    #: (x, y, angle, type, flags)
    things: list[tuple[int, int, int, int, int]]
    #: (floor_h, ceil_h, floorpic, ceilpic, light, special, tag) — M5's damage
    #: floors come from ``special`` (see :data:`DAMAGE_SPECIALS`)
    sectors: list[tuple[int, int, str, str, int, int, int]] = field(default_factory=list)


#: The DOOM damage-floor family: 5%/10%/20% nukage and slime specials (4 is
#: 20% + light blink, 16 is 20%; 11 — end-level — deliberately excluded: at
#: this resolution it is an exit pad, not a pool).
DAMAGE_SPECIALS = frozenset({4, 5, 7, 16})

#: THINGS type -> monster species (M7): former humans (3004 zombieman, 9
#: shotgun guy — same species at this resolution, POSS art) are species 0,
#: imps (3001, TROO art) species 1.  Barrels and decorations are out of scope.
MONSTER_TYPES = {3004: 0, 9: 0, 3001: 1}

#: The monster table cap — the tape's ``MONB`` block is sized to it, and
#: E1M1's medium-skill single-player monster count fits.
MAX_MONSTERS = 16


def read_wad(data: bytes | Path) -> Wad:
    """Parse an IWAD/PWAD: 12-byte header, then 16-byte directory entries."""
    if isinstance(data, Path):
        data = data.read_bytes()
    ident, count, dir_off = struct.unpack("<4sII", data[:12])
    ident = ident.decode("ascii")
    if ident not in ("IWAD", "PWAD"):
        raise ValueError(f"not a WAD: magic {ident!r}")
    lumps = []
    for i in range(count):
        off, size, raw = struct.unpack("<II8s", data[dir_off + 16 * i:dir_off + 16 * i + 16])
        name = raw.rstrip(b"\0").decode("ascii", "replace")
        lumps.append((name, data[off:off + size]))
    return Wad(ident, lumps)


def _cstr(raw: bytes) -> str:
    return raw.rstrip(b"\0").decode("ascii", "replace")


def parse_map(wad: Wad, mapname: str) -> MapData:
    """The named map's THINGS/LINEDEFS/SIDEDEFS/VERTEXES, from the lumps that
    follow its marker (the marker lump itself is empty)."""
    names = [n for n, _ in wad.lumps]
    try:
        at = names.index(mapname)
    except ValueError:
        raise KeyError(f"no map {mapname!r}; lumps: {names[:8]}...") from None
    section = {n: d for n, d in wad.lumps[at + 1:at + 11]}
    need = ("THINGS", "LINEDEFS", "SIDEDEFS", "VERTEXES")
    missing = [n for n in need if n not in section]
    if missing:
        raise ValueError(f"map {mapname} is missing lumps {missing}")
    vertexes = [struct.unpack("<hh", d) for d in _records(section["VERTEXES"], 4)]
    linedefs = [struct.unpack("<HHHHHHH", d) for d in _records(section["LINEDEFS"], 14)]
    sidedefs = []
    for d in _records(section["SIDEDEFS"], 30):
        _xo, _yo, up, lo, mid, sector = struct.unpack("<hh8s8s8sH", d)
        sidedefs.append((_cstr(up), _cstr(lo), _cstr(mid), sector))
    things = [struct.unpack("<hhHHH", d) for d in _records(section["THINGS"], 10)]
    sectors = []
    for d in _records(section.get("SECTORS", b""), 26):
        fh, ch, fp, cp, light, special, tag = struct.unpack("<hh8s8shhh", d)
        sectors.append((fh, ch, _cstr(fp), _cstr(cp), light, special, tag))
    return MapData(vertexes, linedefs, sidedefs, things, sectors)


def _records(data: bytes, size: int):
    return (data[i:i + size] for i in range(0, len(data) - size + 1, size))


# ── rasterization ────────────────────────────────────────────────────────────
def supercover(x0: float, y0: float, x1: float, y1: float) -> set[tuple[int, int]]:
    """Every grid cell the segment touches (Amanatides–Woo traversal; a
    crossing within eps of a cell corner adds both side cells, so a
    4-connected path of empty cells can never slip across the segment)."""
    eps = 1e-9
    cells: set[tuple[int, int]] = set()
    x, y = math.floor(x0), math.floor(y0)
    xe, ye = math.floor(x1), math.floor(y1)
    dx, dy = x1 - x0, y1 - y0
    step_x = 1 if dx > 0 else -1
    step_y = 1 if dy > 0 else -1
    # t at which the ray crosses the next vertical / horizontal grid line
    t_max_x = ((x + (step_x > 0)) - x0) / dx if dx else math.inf
    t_max_y = ((y + (step_y > 0)) - y0) / dy if dy else math.inf
    t_dx = abs(1 / dx) if dx else math.inf
    t_dy = abs(1 / dy) if dy else math.inf
    cells.add((x, y))
    guard = 4 * (abs(xe - x) + abs(ye - y)) + 8
    while (x, y) != (xe, ye) and guard:
        guard -= 1
        if abs(t_max_x - t_max_y) < eps:  # corner crossing: cover both cells
            cells.add((x + step_x, y))
            cells.add((x, y + step_y))
            x += step_x
            y += step_y
            t_max_x += t_dx
            t_max_y += t_dy
        elif t_max_x < t_max_y:
            x += step_x
            t_max_x += t_dx
        else:
            y += step_y
            t_max_y += t_dy
        cells.add((x, y))
    # A segment lying exactly ON a grid line borders both flanking cells
    # (e.g. an axis-aligned wall at an integral coordinate): cover both.
    if dx == 0 and abs(x0 - round(x0)) < eps:
        cells |= {(cx - 1, cy) for cx, cy in cells}
    if dy == 0 and abs(y0 - round(y0)) < eps:
        cells |= {(cx, cy - 1) for cx, cy in cells}
    return cells


@dataclass
class Raster:
    """The rasterized level, before colours."""

    grid: int
    cells: dict[tuple[int, int], str]        # wall cell -> dominant texture
    open_cells: set[tuple[int, int]]         # reachable from the spawn
    spawn: tuple[int, int]
    heading: int                             # 0..15, CCW from east
    bbox: tuple[int, int, int, int]          # minx, miny, maxx, maxy
    void_filled: int = 0
    #: open cells standing on a damage floor (sector special 4/5/7/16)
    nukage: set[tuple[int, int]] = field(default_factory=set)
    nukage_stats: dict = field(default_factory=dict)
    #: ``(cx, cy, species)`` per kept monster THING (M7): medium-skill,
    #: single-player, open-cell, deduped, capped at :data:`MAX_MONSTERS`.
    monsters: list[tuple[int, int, int]] = field(default_factory=list)
    monster_stats: dict = field(default_factory=dict)


def rasterize(m: MapData, grid: int = 64, min_len: float = 32.0) -> Raster:
    """Project the level onto ``grid`` x ``grid`` (uniform scale, centred, one
    border cell), supercover the long one-sided linedefs, close the map.

    Asserts, in order: a player-1 start exists; the spawn cell is open (bumped
    <=2 cells if the exact cell caught a wall); the flood fill from the spawn
    never reaches the grid border (watertight).  Unreachable cells are then
    filled solid, so the result has no void at all.
    """
    xs = [v[0] for v in m.vertexes]
    ys = [v[1] for v in m.vertexes]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    w, h = maxx - minx, maxy - miny
    scale = (grid - 2) / max(w, h)
    offx = 1 + ((grid - 2) - w * scale) / 2
    offy = 1 + ((grid - 2) - h * scale) / 2

    def to_grid(x: float, y: float) -> tuple[float, float]:
        return (x - minx) * scale + offx, (y - miny) * scale + offy

    weight: dict[tuple[int, int], Counter] = defaultdict(Counter)
    for v1, v2, _flags, _special, _tag, right, left in m.linedefs:
        if left != NO_SIDE or right == NO_SIDE:
            continue  # two-sided (or degenerate): not a solid wall
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        length = math.hypot(bx - ax, by - ay)
        if length < min_len:
            continue  # detail geometry
        up, lo, mid, _sector = m.sidedefs[right]
        tex = mid if mid and mid != "-" else (up if up and up != "-" else lo)
        if not tex or tex == "-":
            continue
        for c in supercover(*to_grid(ax, ay), *to_grid(bx, by)):
            if 0 <= c[0] < grid and 0 <= c[1] < grid:
                weight[c][tex] += length
    cells = {c: cnt.most_common(1)[0][0] for c, cnt in weight.items()}

    starts = [t for t in m.things if t[3] == 1]
    assert starts, "no player-1 start (THINGS type 1)"
    sx, sy, angle = starts[0][0], starts[0][1], starts[0][2]
    gx, gy = to_grid(sx, sy)
    spawn = (int(gx), int(gy))
    heading = round(angle / 22.5) % 16
    if spawn in cells:  # the start hugged a wall closer than one cell
        near = [(abs(dx) + abs(dy), (spawn[0] + dx, spawn[1] + dy))
                for dx in range(-2, 3) for dy in range(-2, 3)
                if (spawn[0] + dx, spawn[1] + dy) not in cells]
        assert near, f"no open cell within 2 of the spawn {spawn}"
        spawn = min(near)[1]
    assert 0 < spawn[0] < grid - 1 and 0 < spawn[1] < grid - 1, \
        f"spawn {spawn} out of the map interior"

    open_cells = {spawn}
    queue = deque([spawn])
    while queue:
        x, y = queue.popleft()
        for nxt in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nxt[0] < grid and 0 <= nxt[1] < grid \
                    and nxt not in cells and nxt not in open_cells:
                open_cells.add(nxt)
                queue.append(nxt)
    leaks = [c for c in open_cells if c[0] in (0, grid - 1) or c[1] in (0, grid - 1)]
    assert not leaks, f"map leaks into the void at {sorted(leaks)[:8]}"

    nukage, nstats = _damage_floors(m, to_grid, grid, open_cells)
    monsters, mstats = _monster_things(m, to_grid, open_cells)

    void = 0
    for x in range(grid):
        for y in range(grid):
            if (x, y) not in cells and (x, y) not in open_cells:
                cells[(x, y)] = "#VOID"
                void += 1
    return Raster(grid, cells, open_cells, spawn, heading,
                  (minx, miny, maxx, maxy), void, nukage, nstats,
                  monsters, mstats)


def _monster_things(m: MapData, to_grid,
                    open_cells: set[tuple[int, int]],
                    ) -> tuple[list[tuple[int, int, int]], dict]:
    """The kept monster THINGS (M7): ``(cx, cy, species)`` in THINGS order.

    The filter, in order: a :data:`MONSTER_TYPES` type; present on medium
    skill (``flags & 2``); not multiplayer-only (``flags & 0x10`` clear); its
    grid cell open (a monster inside a supercovered wall cell would never be
    reachable or visible); the cell not already taken (one billboard per
    cell); capped at :data:`MAX_MONSTERS` in THINGS order.
    """
    stats = {"monster_things": 0, "skill_dropped": 0, "closed_dropped": 0,
             "dupe_dropped": 0, "cap_dropped": 0}
    kept: list[tuple[int, int, int]] = []
    taken: set[tuple[int, int]] = set()
    for x, y, _angle, mtype, flags in m.things:
        species = MONSTER_TYPES.get(mtype)
        if species is None:
            continue
        stats["monster_things"] += 1
        if not (flags & 2) or (flags & 0x10):
            stats["skill_dropped"] += 1
            continue
        gx, gy = to_grid(x, y)
        cell = (int(gx), int(gy))
        if cell not in open_cells:
            stats["closed_dropped"] += 1
            continue
        if cell in taken:
            stats["dupe_dropped"] += 1
            continue
        if len(kept) >= MAX_MONSTERS:
            stats["cap_dropped"] += 1
            continue
        taken.add(cell)
        kept.append((cell[0], cell[1], species))
    stats["monsters_kept"] = len(kept)
    return kept, stats


def _damage_floors(m: MapData, to_grid, grid: int,
                   open_cells: set[tuple[int, int]]) -> tuple[set[tuple[int, int]], dict]:
    """Which open cells stand on a damage floor (M5).

    Region flood fill: the open cells are partitioned into regions bounded by
    the supercover of **all** linedefs — two-sided ones included, as thin
    boundaries for regioning only (they are room-to-room joins, not walls).
    Each region's sector is then identified by *sampling*: points either side
    of every linedef (offset along its normal, the right side facing the right
    sidedef — DOOM's front) vote their sidedef's sector into whatever region
    they land in, weighted by linedef length; the plurality wins.  A region
    whose sector's special is in :data:`DAMAGE_SPECIALS` is nukage.  Open
    cells *on* a boundary (a pool's rim) resolve by their own cell votes,
    then by neighbour majority.  If the specials find nothing but flats named
    NUKAGE*/SLIME*/LAVA* exist, the flat-name fallback is used (documented in
    ``stats['nukage_by']``).
    """
    stats: dict = {"regions": 0, "unresolved_regions": 0, "nukage_cells": 0,
                   "damage_sectors": 0, "nukage_by": "specials"}
    if not m.sectors:
        return set(), stats

    def damaging_special(sec: int) -> bool:
        return m.sectors[sec][5] in DAMAGE_SPECIALS

    def damaging_flat(sec: int) -> bool:
        return m.sectors[sec][2].upper().startswith(("NUKAGE", "SLIME", "LAVA"))

    stats["damage_sectors"] = sum(1 for s in range(len(m.sectors)) if damaging_special(s))
    stats["flat_sectors"] = sum(1 for s in range(len(m.sectors)) if damaging_flat(s))

    # 1. The boundary raster: every linedef, any length, both-sided included.
    boundary: set[tuple[int, int]] = set()
    for v1, v2, _flags, _special, _tag, _right, _left in m.linedefs:
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        if (ax, ay) == (bx, by):
            continue
        for c in supercover(*to_grid(ax, ay), *to_grid(bx, by)):
            if 0 <= c[0] < grid and 0 <= c[1] < grid:
                boundary.add(c)

    # 2. Regions: 4-connected components of open cells off the boundary.
    region_of: dict[tuple[int, int], int] = {}
    regions: list[list[tuple[int, int]]] = []
    for cell in sorted(open_cells):
        if cell in boundary or cell in region_of:
            continue
        rid = len(regions)
        comp = [cell]
        region_of[cell] = rid
        queue = deque([cell])
        while queue:
            x, y = queue.popleft()
            for nxt in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                if nxt in open_cells and nxt not in boundary and nxt not in region_of:
                    region_of[nxt] = rid
                    comp.append(nxt)
                    queue.append(nxt)
        regions.append(comp)
    stats["regions"] = len(regions)

    # 3. Sector votes: sample points either side of each linedef.  The right
    # sidedef faces the right of v1->v2, which in this y-up frame is the
    # normal (dy, -dx).
    votes: dict[int, Counter] = defaultdict(Counter)
    cell_votes: dict[tuple[int, int], Counter] = defaultdict(Counter)
    for v1, v2, _flags, _special, _tag, right, left in m.linedefs:
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        gax, gay = to_grid(ax, ay)
        gbx, gby = to_grid(bx, by)
        dx, dy = gbx - gax, gby - gay
        ln = math.hypot(dx, dy)
        if ln < 1e-9:
            continue
        nx, ny = dy / ln, -dx / ln
        length = math.hypot(bx - ax, by - ay)
        for side, sd in ((1.0, right), (-1.0, left)):
            if sd == NO_SIDE or sd >= len(m.sidedefs):
                continue
            sector = m.sidedefs[sd][3]
            if sector >= len(m.sectors):
                continue
            for f in (0.25, 0.5, 0.75):
                for off in (0.6, 1.2):
                    px = gax + f * dx + side * off * nx
                    py = gay + f * dy + side * off * ny
                    cell = (math.floor(px), math.floor(py))
                    rid = region_of.get(cell)
                    if rid is not None:
                        votes[rid][sector] += length
                    elif cell in open_cells:  # an open boundary cell (a rim)
                        cell_votes[cell][sector] += length

    sector_of_region = {rid: cnt.most_common(1)[0][0] for rid, cnt in votes.items()}
    stats["unresolved_regions"] = len(regions) - len(sector_of_region)

    def resolve(damaging) -> set[tuple[int, int]]:
        nukage: set[tuple[int, int]] = set()
        clear: set[tuple[int, int]] = set()
        for rid, comp in enumerate(regions):
            sec = sector_of_region.get(rid)
            (nukage if sec is not None and damaging(sec) else clear).update(comp)
        # The rims: first by their own votes, then two neighbour-majority passes.
        rim = [c for c in open_cells if c not in region_of]
        rest = []
        for cell in rim:
            if cell_votes.get(cell):
                (nukage if damaging(cell_votes[cell].most_common(1)[0][0])
                 else clear).add(cell)
            else:
                rest.append(cell)
        for _ in range(2):
            for cell in list(rest):
                x, y = cell
                nb = [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
                n_nuk = sum(1 for c in nb if c in nukage)
                n_clr = sum(1 for c in nb if c in clear)
                if n_nuk + n_clr:
                    (nukage if n_nuk > n_clr else clear).add(cell)
                    rest.remove(cell)
        return nukage

    nukage = resolve(damaging_special)
    if not nukage and stats["flat_sectors"]:
        stats["nukage_by"] = "flats"
        nukage = resolve(damaging_flat)
    # Agreement between the two definitions, for the report.
    stats["special_vs_flat_disagree"] = sum(
        1 for s in range(len(m.sectors)) if damaging_special(s) != damaging_flat(s))
    stats["nukage_cells"] = len(nukage)
    return nukage, stats


# ── colours ──────────────────────────────────────────────────────────────────
def srgb_to_lab(rgb: tuple[float, float, float]) -> tuple[float, float, float]:
    """CIELAB (D65) — the same conversion the title/gun quantization used."""
    def lin(c: float) -> float:
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (lin(c) for c in rgb)
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883

    def f(t: float) -> float:
        return t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116

    fx, fy, fz = f(x), f(y), f(z)
    return 116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)


_LAB = [srgb_to_lab(p) for p in PALETTE]
_HUES = {i: math.atan2(_LAB[i][2], _LAB[i][1]) for i in range(1, 7)}
#: Below this CIELAB chroma a texture is just gray (family 7).  DOOM-era
#: metals/concretes sit around 4..8; bricks and screens well above 10.
CHROMA_GATE = 10.0


def family_of(avg: tuple[float, float, float] | None) -> int:
    """Wall family 1..7 for a texture's average colour: gray under the chroma
    gate, else the hue-nearest of the six chromatic ANSI colours."""
    if avg is None:
        return 7
    _l, a, b = srgb_to_lab(avg)
    if math.hypot(a, b) < CHROMA_GATE:
        return 7
    hue = math.atan2(b, a)

    def dist(i: int) -> float:
        d = abs(hue - _HUES[i])
        return min(d, 2 * math.pi - d)

    return min(range(1, 7), key=dist)


# ── PNG decode (stdlib; the subset Freedoom's assets use) ────────────────────
def decode_png(data: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a non-interlaced PNG (bit depth 1/2/4/8; colour types
    0 gray, 2 RGB, 3 palette, 4 gray+alpha, 6 RGBA; tRNS honoured)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    w = h = bitd = ctype = 0
    plte: list[tuple[int, int, int]] = []
    trns = b""
    idat = b""
    at = 8
    while at < len(data):
        (ln,), tag = struct.unpack(">I", data[at:at + 4]), data[at + 4:at + 8]
        body = data[at + 8:at + 8 + ln]
        at += 12 + ln
        if tag == b"IHDR":
            w, h, bitd, ctype, comp, filt, inter = struct.unpack(">IIBBBBB", body)
            if inter:
                raise ValueError("interlaced PNG unsupported")
            if comp or filt:
                raise ValueError("nonstandard PNG compression/filter")
        elif tag == b"PLTE":
            plte = [tuple(body[i:i + 3]) for i in range(0, len(body), 3)]
        elif tag == b"tRNS":
            trns = body
        elif tag == b"IDAT":
            idat += body
        elif tag == b"IEND":
            break
    raw = zlib.decompress(idat)
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bpp = max(1, channels * bitd // 8)
    stride = (w * channels * bitd + 7) // 8
    rows: list[bytearray] = []
    prev = bytearray(stride)
    for yy in range(h):
        f = raw[yy * (stride + 1)]
        line = bytearray(raw[yy * (stride + 1) + 1:(yy + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1:
                line[i] = (line[i] + a) & 0xFF
            elif f == 2:
                line[i] = (line[i] + b) & 0xFF
            elif f == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        rows.append(line)
        prev = line

    def samples(line: bytearray):
        if bitd == 8:
            yield from line
        else:
            per = 8 // bitd
            mask = (1 << bitd) - 1
            for byte in line:
                for k in range(per):
                    yield (byte >> (8 - bitd * (k + 1))) & mask

    out = []
    scale = 255 // ((1 << bitd) - 1) if ctype != 3 else 1
    for line in rows:
        vals = list(samples(line))
        row = []
        for xx in range(w):
            v = vals[xx * channels:(xx + 1) * channels]
            if ctype == 3:
                r, g, b = plte[v[0]]
                a = trns[v[0]] if v[0] < len(trns) else 255
                row.append((r, g, b, a))
            elif ctype == 0:
                g = v[0] * scale
                row.append((g, g, g, 255))
            elif ctype == 4:
                g = v[0] * scale
                row.append((g, g, g, v[1] * scale))
            elif ctype == 2:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, 255))
            else:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, v[3] * scale))
        out.append(row)
    return out


# ── DOOM picture format (IWAD patches, TITLEPIC) ─────────────────────────────
def decode_picture(data: bytes, playpal: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a DOOM picture lump: a header of column offsets, each
    column a run of posts (top-delta, length, pad, pixels..., pad), 0xFF ends."""
    w, h, _lo, _to = struct.unpack("<HHhh", data[:8])
    cols = struct.unpack(f"<{w}I", data[8:8 + 4 * w])
    rows = [[(0, 0, 0, 0)] * w for _ in range(h)]
    for x, off in enumerate(cols):
        at = off
        while data[at] != 0xFF:
            top, ln = data[at], data[at + 1]
            for k in range(ln):
                idx = data[at + 3 + k]
                y = top + k
                if y < h:
                    r, g, b = playpal[3 * idx:3 * idx + 3]
                    rows[y][x] = (r, g, b, 255)
            at += 4 + ln
    return rows


# ── dithering (M9, OPT-IN) ───────────────────────────────────────────────────
#: The dither algorithms :func:`dither_lab` understands.  ``"none"`` is the
#: committed art's method (block-Lab nearest colour, no diffusion) and is the
#: default everywhere: turning dithering on is always an explicit choice, so
#: no committed byte moves.
#:
#: * ``"fs"`` — Floyd–Steinberg error diffusion, serpentine, **in CIELAB**.
#:   Best gradients; shreds flat areas, so the RLE run count explodes.
#: * ``"bayer4"`` / ``"bayer8"`` — ordered dithering against the 4x4 / 8x8
#:   Bayer matrix, also in CIELAB (nearest colour + its overshoot partner,
#:   mixed by the ordered threshold).  Temporally stable and far kinder to the
#:   row-major RLE: a periodic pattern repeats runs instead of inventing new
#:   ones, and a cell whose colour is unambiguous never dithers at all.
DITHER_MODES = ("none", "fs", "bayer4", "bayer8")


def bayer_matrix(n: int) -> list[list[int]]:
    """The ``n`` x ``n`` (n a power of two) Bayer index matrix, values
    ``0..n*n-1``; ``M_2n = [[4M, 4M+2], [4M+3, 4M+1]]``."""
    if n < 1 or n & (n - 1):
        raise ValueError(f"a Bayer matrix side must be a power of two, not {n}")
    m = [[0]]
    size = 1
    while size < n:
        m = ([[4 * v for v in row] + [4 * v + 2 for v in row] for row in m]
             + [[4 * v + 3 for v in row] + [4 * v + 1 for v in row] for row in m])
        size *= 2
    return m


def _nearest_lab(lab: tuple[float, float, float]) -> int:
    return min(range(16), key=lambda i: math.dist(lab, _LAB[i]))


def block_lab(rgba: list[list[tuple[int, int, int, int]]], tw: int, th: int,
              *, brightness: float = 1.0,
              background: tuple[int, int, int] | None = None,
              ) -> list[list[tuple[float, float, float] | None]]:
    """Per target cell, the MEAN CIELAB of its source block.

    The same block grid the undithered path walks, but reduced to one Lab
    value per cell instead of a per-palette distance sum — dithering needs a
    continuous colour to push error around.  Alpha follows
    :func:`quantize_sprite`: with ``background`` the block is composited onto
    it and every cell is a colour; without one, a mostly-transparent block is
    ``None`` and only opaque pixels vote.
    """
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], tuple[float, float, float]] = {}

    def lab_of(rgb: tuple[int, int, int]) -> tuple[float, float, float]:
        key = tuple(min(255, round(c * brightness)) for c in rgb)
        if key not in cache:
            cache[key] = srgb_to_lab(key)
        return cache[key]

    out: list[list[tuple[float, float, float] | None]] = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row: list[tuple[float, float, float] | None] = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0, 0.0, 0.0]
            n = opaque = total = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    r, g, b, a = rgba[yy][xx]
                    total += 1
                    if a > 128:
                        opaque += 1
                        lab = lab_of((r, g, b))
                    elif background is not None:
                        lab = lab_of(background)
                    else:
                        continue
                    for i in range(3):
                        acc[i] += lab[i]
                    n += 1
            if not n or (background is None and opaque * 2 < total):
                row.append(None)
            else:
                row.append((acc[0] / n, acc[1] / n, acc[2] / n))
        out.append(row)
    return out


#: Floyd–Steinberg's kernel, ``(dx, dy, weight/16)`` for a left-to-right row
#: (the serpentine pass mirrors dx).
_FS_KERNEL = ((1, 0, 7 / 16), (-1, 1, 3 / 16), (0, 1, 5 / 16), (1, 1, 1 / 16))


def dither_lab(cells: list[list[tuple[float, float, float] | None]],
               mode: str = "none", *, strength: float = 1.0,
               ) -> list[list[int | None]]:
    """Quantize a grid of CIELAB cells (:func:`block_lab`) to ANSI-16 indices.

    ``mode`` is one of :data:`DITHER_MODES`.  ``None`` cells (transparent
    sprite blocks) pass through untouched and neither receive nor emit error.

    *Floyd–Steinberg* runs serpentine (alternate rows right-to-left), which
    kills the diagonal "worming" a single scan direction leaves on the long
    horizontal gradients DOOM title art is made of.  The residual is carried
    in Lab, so the diffusion is perceptual, exactly like the nearest-colour
    search it feeds.

    *Ordered Bayer* does not threshold a single channel (meaningless against a
    16-colour non-ramp palette).  Per cell it takes the nearest palette colour
    ``c1``, reflects the cell through it to get the overshoot ``2p - c1`` and
    takes that colour's nearest ``c2`` — the two entries the cell actually
    lies between — then projects the cell onto the ``c1``->``c2`` segment for a
    mix fraction ``t`` and paints ``c2`` where the Bayer threshold falls under
    ``t``.  A cell that is already ON a palette colour has ``t == 0`` and never
    dithers, which is what keeps flat areas (and their RLE runs) intact.

    ``strength`` < 1 damps the dither toward the undithered result: it scales
    the diffused residual (Floyd–Steinberg) or the mix fraction (Bayer).  Full
    strength is textbook, and on a palette this sparse it lets chroma error run
    away — a flat dark red diffuses into magenta specks.  Lower it when the
    stipple reads as noise rather than as shading.
    """
    if mode not in DITHER_MODES:
        raise ValueError(f"unknown dither mode {mode!r}; pick one of {DITHER_MODES}")
    h = len(cells)
    w = len(cells[0]) if h else 0
    if mode == "none":
        return [[None if c is None else _nearest_lab(c) for c in row] for row in cells]
    if mode == "fs":
        err = [[[0.0, 0.0, 0.0] for _ in range(w)] for _ in range(h)]
        out: list[list[int | None]] = [[None] * w for _ in range(h)]
        for y in range(h):
            xs = range(w) if not y % 2 else range(w - 1, -1, -1)
            flip = -1 if y % 2 else 1
            for x in xs:
                cell = cells[y][x]
                if cell is None:
                    continue
                want = tuple(cell[i] + err[y][x][i] for i in range(3))
                idx = _nearest_lab(want)
                out[y][x] = idx
                resid = [want[i] - _LAB[idx][i] for i in range(3)]
                for dx, dy, wgt in _FS_KERNEL:
                    nx, ny = x + flip * dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and cells[ny][nx] is not None:
                        for i in range(3):
                            err[ny][nx][i] += resid[i] * wgt * strength
        return out
    n = 4 if mode == "bayer4" else 8
    matrix = bayer_matrix(n)
    thresh = [[(v + 0.5) / (n * n) for v in row] for row in matrix]
    out = [[None] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            cell = cells[y][x]
            if cell is None:
                continue
            c1 = _nearest_lab(cell)
            over = tuple(2 * cell[i] - _LAB[c1][i] for i in range(3))
            c2 = _nearest_lab(over)
            if c2 == c1:
                out[y][x] = c1
                continue
            d = [_LAB[c2][i] - _LAB[c1][i] for i in range(3)]
            dd = sum(v * v for v in d)
            t = sum((cell[i] - _LAB[c1][i]) * d[i] for i in range(3)) / dd if dd else 0.0
            t = min(1.0, max(0.0, t)) * strength
            out[y][x] = c2 if thresh[y % n][x % n] < t else c1
    return out


# ── the title screen ─────────────────────────────────────────────────────────
#: DOOM-era title art is dark; a fixed linear brightness lift keeps the marine
#: (and the shareware IWAD's title) out of the black/dark-gray sump when the
#: 16-colour palette quantizes it.  Chosen by eyeballing 1.0/1.4/1.6/1.8 on
#: both title sources.
TITLE_BRIGHTNESS = 1.6


def quantize_title(rgba: list[list[tuple[int, int, int, int]]],
                   tw: int = 64, th: int = 48,
                   brightness: float = TITLE_BRIGHTNESS,
                   *, dither: str = "none",
                   dither_strength: float = 1.0) -> list[str]:
    """The repo's block-Lab method at ``tw`` x ``th``: per target block pick
    the ANSI-16 colour minimizing the summed CIELAB distance over the source
    block's (brightness-lifted) pixels; then one despeckle pass.

    ``dither`` (default ``"none"`` — the committed art's exact method) switches
    to the M9 path: the block is reduced to its mean CIELAB (:func:`block_lab`)
    and quantized by :func:`dither_lab`.  Despeckling is then skipped on
    purpose: it exists to kill isolated dots, and a dither pattern IS isolated
    dots.
    """
    if dither != "none":
        grid = dither_lab(block_lab(rgba, tw, th, brightness=brightness), dither,
                          strength=dither_strength)
        return ["".join(f"{c:x}" for c in row) for row in grid]
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], list[float]] = {}

    def dists(px: tuple[int, int, int, int]) -> list[float]:
        rgb = tuple(min(255, round(c * brightness)) for c in px[:3])
        if rgb not in cache:
            lab = srgb_to_lab(rgb)
            cache[rgb] = [math.dist(lab, palette_lab) for palette_lab in _LAB]
        return cache[rgb]

    grid = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0] * 16
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    d = dists(rgba[yy][xx])
                    for i in range(16):
                        acc[i] += d[i]
            row.append(min(range(16), key=acc.__getitem__))
        grid.append(row)
    grid = despeckle(grid)
    return ["".join(f"{c:x}" for c in row) for row in grid]


def despeckle(grid: list[list[int]]) -> list[list[int]]:
    """A pixel whose 4-neighbours all agree on another colour joins them."""
    h, w = len(grid), len(grid[0])
    out = [row[:] for row in grid]
    for y in range(h):
        for x in range(w):
            nb = [grid[y + dy][x + dx]
                  for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                  if 0 <= x + dx < w and 0 <= y + dy < h]
            if len(nb) == 4 and len(set(nb)) == 1 and nb[0] != grid[y][x]:
                out[y][x] = nb[0]
    return out


# ── sprite art (M5: the HUD face; the --wad art overrides) ───────────────────
def quantize_sprite(rgba: list[list[tuple[int, int, int, int]]], tw: int, th: int,
                    *, background: tuple[int, int, int] | None = None,
                    brightness: float = 1.0, dither: str = "none",
                    dither_strength: float = 1.0,
                    ) -> list[list[int | None]]:
    """Block-Lab quantize a sprite to ``tw`` x ``th``.

    With ``background`` given, the sprite is composited onto it first and every
    cell is opaque (the HUD face on the field gray).  Without it, a target cell
    whose source block is mostly transparent stays ``None`` (the pistol's
    outline), and only opaque pixels vote.

    ``dither`` (default ``"none"``, the committed art's method) routes through
    :func:`block_lab` + :func:`dither_lab`; transparency is decided by the same
    half-block rule either way.
    """
    if dither != "none":
        return dither_lab(block_lab(rgba, tw, th, brightness=brightness,
                                    background=background), dither,
                          strength=dither_strength)
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], list[float]] = {}

    def dists(rgb: tuple[int, int, int]) -> list[float]:
        rgb = tuple(min(255, round(c * brightness)) for c in rgb)
        if rgb not in cache:
            lab = srgb_to_lab(rgb)
            cache[rgb] = [math.dist(lab, pl) for pl in _LAB]
        return cache[rgb]

    grid: list[list[int | None]] = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row: list[int | None] = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0] * 16
            opaque = total = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    r, g, b, a = rgba[yy][xx]
                    total += 1
                    if a > 128:
                        opaque += 1
                        d = dists((r, g, b))
                    elif background is not None:
                        d = dists(background)
                    else:
                        continue
                    for i in range(16):
                        acc[i] += d[i]
            if background is None and opaque * 2 < total:
                row.append(None)
            else:
                row.append(min(range(16), key=acc.__getitem__))
        grid.append(row)
    return grid


def sprite_runs(grid: list[list[int | None]], row0: int, col0: int,
                *, max_body: int = 12) -> list[tuple[int, int, str]]:
    """``(row, col, colors)`` runs for the DOOM unit's sprite arms.

    Contiguous opaque spans per row, split so every run fits the arm's descent
    windows — the token accounting mirrors ``d3_unit._pixel_tokens`` (one load
    for a colour 0..9, two for a..f, one send per pixel; ``max_body`` is the
    DATA window's 12 rows, counted from the first send).
    """
    runs: list[tuple[int, int, str]] = []
    for r, row in enumerate(grid):
        c = 0
        while c < len(row):
            if row[c] is None:
                c += 1
                continue
            start = c
            colors = ""
            cur: int | None = None
            body = 0  # tokens from the first send, d3_unit's window budget
            while c < len(row) and row[c] is not None:
                px = row[c]
                cost = (0 if px == cur else (1 if px < 10 else 2)) + 1
                if colors and body + cost > max_body:
                    break  # split: the next pixel opens a fresh run
                # the first pixel's loads are the run's lead, not its body
                body += cost if colors else 1
                colors += "%x" % px
                cur = px
                c += 1
            runs.append((row0 + r, col0 + start, colors))
    return runs


def _crop_alpha(rgba: list[list[tuple[int, int, int, int]]]):
    """The sprite's opaque bounding box (DOOM picture lumps pad heavily)."""
    ys = [y for y, row in enumerate(rgba) if any(px[3] > 128 for px in row)]
    xs = [x for x in range(len(rgba[0])) if any(row[x][3] > 128 for row in rgba)]
    if not ys or not xs:
        raise ValueError("sprite is fully transparent")
    return [row[min(xs):max(xs) + 1] for row in rgba[min(ys):max(ys) + 1]]


#: The three baked billboard scale bands (M7): ``(width, height)`` near, mid,
#: far.  Heights <= 14 keep a whole sprite column in ONE packed word (16
#: nibbles max, top nibble below 2**63 by construction); the golden model's
#: ``BAND_T`` thresholds pick the band from the projected depth.
MON_BANDS = ((10, 14), (6, 9), (4, 5))

#: A monster billboard cannot paint black: colour 0 doubles as transparent in
#: the packed columns, so an opaque near-black block maps to dark gray 8.
MON_BLACK = 8


#: Below this CIELAB chroma a billboard block is achromatic; DOOM-era monster
#: skin sits at 7..19, deep shadows below.  Lower than the wall families'
#: gate (10) on purpose: a billboard must READ against the gray floor 8 and
#: walls 7, so faint hues are kept rather than flattened.
MON_CHROMA_GATE = 6.0
#: An achromatic block lighter than this CIELAB L is light gray 7, else 8.
MON_L_GRAY = 45.0
#: A chromatic block lighter than this L takes the bright ANSI variant (+8).
MON_L_BRIGHT = 55.0


def quantize_monster(rgba: list[list[tuple[int, int, int, int]]],
                     tw: int, th: int, *, brightness: float = 1.0,
                     ) -> list[list[int]]:
    """Hue-forward block quantize of a monster sprite to ``tw`` x ``th``.

    Billboard rules: a mostly-transparent block is colour 0 (the packed
    columns' transparency); an opaque block takes its alpha-weighted average
    colour through the wall families' hue logic — gray (7 light / 8 dark)
    under :data:`MON_CHROMA_GATE`, else the hue-nearest chromatic ANSI colour
    (bright variant above :data:`MON_L_BRIGHT`).  Plain block-Lab was tried
    first and flattens Freedoom's dark-brown imps and olive zombimen into the
    floor's own gray 8; hue-forward keeps them readable, exactly as
    :func:`family_of` keeps the desaturated wall textures apart.  Black is
    never produced (colour 0 is transparency): a black-ish block is 8.
    """
    hh, ww = len(rgba), len(rgba[0])
    grid: list[list[int]] = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row: list[int] = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            rs = gs = bs = opaque = total = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    r, g, b, a = rgba[yy][xx]
                    total += 1
                    if a > 128:
                        opaque += 1
                        rs += r
                        gs += g
                        bs += b
            if opaque * 2 < total:
                row.append(0)
                continue
            avg = tuple(min(255.0, c / opaque * brightness) for c in (rs, gs, bs))
            l, a_, b_ = srgb_to_lab(avg)
            if math.hypot(a_, b_) < MON_CHROMA_GATE:
                row.append(7 if l > MON_L_GRAY else MON_BLACK)
                continue
            hue = math.atan2(b_, a_)

            def dist(i: int) -> float:
                d = abs(hue - _HUES[i])
                return min(d, 2 * math.pi - d)

            fam = min(range(1, 7), key=dist)
            row.append(fam + 8 if l > MON_L_BRIGHT else fam)
        grid.append(row)
    return grid


def pack_sprite_columns(grid: list[list[int]]) -> list[int]:
    """One packed word per sprite column, **bottom pixel = nibble 0**.

    The paint chain's bottom-up nibble walk (``c = Q % 16; Q //= 16``) reads
    these; height <= 14 keeps every word under 2**63 (16**14 == 2**56).
    """
    h, w = len(grid), len(grid[0])
    assert h <= 14, f"sprite height {h} > 14 would overflow a packed word"

    words = []
    for x in range(w):
        word = 0
        for j in range(h):  # j = rows above the bottom
            word += grid[h - 1 - j][x] * 16 ** j
        assert 0 <= word < 2 ** 63
        words.append(word)
    return words


def monster_band_words(rgba: list[list[tuple[int, int, int, int]]],
                       *, pad_to_bands: bool = False,
                       brightness: float = 1.0,
                       bands: tuple[tuple[int, int], ...] = MON_BANDS,
                       words_per_col: int = 1) -> list[int]:
    """One sprite's bands, packed — 20 words at the committed ``MON_BANDS``.

    ``pad_to_bands`` is the corpse path: the source (a low, wide death frame)
    is quantized to the band width at its own proportional height (floor 2)
    and padded with transparent top rows to the band height, so the paint
    chain needs no extra entry points.

    ``words_per_col`` > 1 splits a column that is too tall for one word.  A
    packed column is one nibble per row and 16**15 is the last power that fits
    64 bits, so a band taller than 14 rows — which every band is once the
    screen doubles — has to become two words, low rows first.  See
    :func:`pack_sprite_columns_wide`.
    """
    src = _crop_alpha(rgba)
    sh, sw = len(src), len(src[0])
    words: list[int] = []
    for bw, bh in bands:
        if pad_to_bands:
            ch = max(2, min(bh, round(bw * sh / sw)))
            grid = quantize_monster(src, bw, ch, brightness=brightness)
            grid = [[0] * bw for _ in range(bh - ch)] + grid
        else:
            grid = quantize_monster(src, bw, bh, brightness=brightness)
        words += pack_sprite_columns_wide(grid, words_per_col)
    assert len(words) == words_per_col * sum(w for w, _h in bands)
    return words


def pack_sprite_columns_wide(grid: list[list[int]], words_per_col: int = 1) -> list[int]:
    """Packed columns, ``words_per_col`` words each, **low rows in the first**.

    ``words_per_col == 1`` is :func:`pack_sprite_columns` exactly.  Above that
    the column is cut into that many 14-row slices from the bottom up and each
    slice packed on its own, so the paint chain reloads its working word every
    14 nibbles instead of running out of bits at row 15.

    The column is padded with transparent rows to ``14 * words_per_col`` first,
    which is what lets one shared chain serve every band: with the sprite in
    the *bottom* rows and zeros above, a short band simply skips its way
    through the padding (the chain already branches over a 0 nibble) and no
    band needs an entry point of its own.
    """
    h, w = len(grid), len(grid[0])
    span = 14 * words_per_col
    if h > span:
        raise ValueError(f"sprite height {h} > {span} = 14 * {words_per_col} words")
    padded = [[0] * w for _ in range(span - h)] + grid
    out: list[int] = []
    for x in range(w):
        for k in range(words_per_col):
            word = 0
            for j in range(14):  # j = rows above this slice's bottom
                row = span - 1 - (14 * k + j)
                word += padded[row][x] * 16 ** j
            assert 0 <= word < 2 ** 63
            out.append(word)
    return out


def monster_sprite_words(mon0_rgba, mon1_rgba, corpse_rgba,
                         *, brightness: float = 1.0,
                         bands: tuple[tuple[int, int], ...] = MON_BANDS,
                         words_per_col: int = 1) -> list[int]:
    """The whole ``SPRB`` table: species 0 (POSS art) bands, species 1
    (TROO art) bands, then the shared corpse frame padded to the band boxes.
    Column base offsets are ``species * stride + band offset`` (corpse:
    ``2 * stride + ...``, an M7b consumer), all in units of
    ``words_per_col`` words."""
    kw = {"brightness": brightness, "bands": bands, "words_per_col": words_per_col}
    return (monster_band_words(mon0_rgba, **kw)
            + monster_band_words(mon1_rgba, **kw)
            + monster_band_words(corpse_rgba, pad_to_bands=True, **kw))


def gun_tables(idle_rgba, flash_rgba, *, width: int = 11, height: int = 10,
               brightness: float = 1.0,
               screen: tuple[int, int] = (64, 40),
               max_runs: int | None = 20, max_body: int = 12):
    """``(GUN_IDLE, GUN_FIRE)`` run tables from a pistol + muzzle-flash pair.

    The construction, at any screen: the idle gun bottom-centred on the
    viewport, the fire variant the same gun one row higher with the flash
    blooming directly above it.  At the committed 64x40 that is the gun on rows
    30..39 and the flash on 25..28.

    ``screen`` is ``(width, h3d)`` — the *viewport*, not the frame, since the
    status bar is below it.  ``max_runs``/``max_body`` are the DOOM unit's
    sprite-arm budget: a baked arm holds 20 runs of at most a 12-row descent
    window.  Pass ``None`` and a large body when the **CPU** draws the sprite
    instead (the tiled machine does — see ``deadman3d._pistol_asm``), because
    then the only cost of a run is two ROM words and there is no arm to spill.
    """
    sw, sh3d = screen
    idle = quantize_sprite(_crop_alpha(idle_rgba), width, height,
                           brightness=brightness)
    idle_runs = sprite_runs(idle, sh3d - height, (sw - width) // 2,
                            max_body=max_body)
    flash_src = _crop_alpha(flash_rgba)
    fh = max(2, round(4 * height / 10))
    fw = max(2, min(width, round(fh * len(flash_src[0]) / len(flash_src))))
    flash = quantize_sprite(flash_src, fw, fh, brightness=brightness)
    # the flash sits clear above the RECOILED gun (whose top row is
    # sh3d - height - 1), exactly like the committed art's 25..28 band
    flash_runs = sprite_runs(flash, sh3d - height - fh - 1, sw // 2 - fw // 2,
                             max_body=max_body)
    fire_runs = flash_runs + [(r - 1, c, colors) for r, c, colors in idle_runs]
    for name, runs in (("idle", idle_runs), ("fire", fire_runs)):
        if max_runs is not None and len(runs) > max_runs:
            raise ValueError(
                f"the {name} pistol quantized to {len(runs)} runs; the unit's "
                f"sprite arms fit {max_runs} (leaf spill bound) — coarsen the "
                "quantize, or pass max_runs=None if the CPU draws it")
    return idle_runs, fire_runs


# ── the status bar (M8: DOOM's REAL STBAR under the live readouts) ───────────
#: DOOM's status bar art is 320x32 and the demo's HUD strip is 64x8 — exactly
#: 5x4 source pixels per target cell, so the block quantize lands on the art
#: with no resampling distortion at all.
STBAR_W, STBAR_H = 320, 32
HUD_W, HUD_H = 64, 8

#: The bar's REAL regions, ``(x0, y0, x1, y1)`` half-open, in STBAR's own
#: 320x32 pixels.  Every number is id Software's own ``st_stuff.c`` placement
#: constant with the bar's screen origin removed (the bar is blitted at
#: ``ST_Y`` = 168 on the 320x200 screen), and every extent is the lump's real
#: size, read off DOOM's own directory: the big ``STTNUM`` digits and the
#: ``STTPRCNT`` percent sign are 14x16, ``STARMS`` is 40x32, the mugshot
#: ``STFST*`` is 24x29, ``STKEYS*`` 7x5, the small ``STYSNUM`` 4x6.
#:
#: ``STlib_drawNum`` draws a 3-digit number RIGHT-aligned, ending at the
#: ``ST_*X`` constant, so a well starts ``3 * 14`` pixels to its left;
#: ``STlib_updatePercent`` then puts the percent sign AT that x, so health and
#: armor run 14 further right.  The face's own box is not the patch's 24
#: pixels but the recessed inset it sits in — measured on the decoded art
#: (the darkest columns of a real DOOM bar run 143..177, and the mugshot's
#: -5 left offset centres it in exactly that slot).
_D, _P = 3 * 14, 14           # a 3-digit big number, and the percent sign
STBAR_REGIONS: dict[str, tuple[int, int, int, int]] = {
    "ammo":   (44 - _D, 171 - 168, 44, 171 - 168 + 16),          # ST_AMMOX
    "health": (90 - _D, 171 - 168, 90 + _P, 171 - 168 + 16),     # ST_HEALTHX
    "arms":   (104, 0, 104 + 40, 32),                            # ST_ARMSBGX
    "face":   (144, 0, 177, 29),                                 # the ST_FX inset
    "armor":  (221 - _D, 171 - 168, 221 + _P, 171 - 168 + 16),   # ST_ARMORX
    "keys":   (239, 171 - 168, 239 + 7, 191 - 168 + 5),          # ST_KEY0..2
    "ammos":  (288 - 3 * 4, 173 - 168, 314, 191 - 168 + 6),      # ST_AMMO0X
}


def stbar_cells(name: str, tw: int = HUD_W, th: int = HUD_H,
                ) -> tuple[int, int, int, int]:
    """``(col0, row0, col1, row1)`` half-open: a :data:`STBAR_REGIONS` entry
    scaled onto the HUD strip — the bar's own pixels over 5 horizontally and
    4 vertically, rounded to the nearest cell boundary."""
    x0, y0, x1, y1 = STBAR_REGIONS[name]
    sx, sy = STBAR_W / tw, STBAR_H / th
    return (round(x0 / sx), round(y0 / sy), round(x1 / sx), round(y1 / sy))


#: The auto-exposure target for :func:`stbar_rows`: a status bar is DOOM-era
#: dark metal (Freedoom's mean grey is 60, a v1.0 shareware bar's 78) and the
#: ANSI-16 grey ramp only steps at 0 / 85 / 170 / 255, so a bar quantized as
#: it stands is one flat slab of colour 8.  Scaling each source so its MEAN
#: grey lands here puts the wells' bevels and the label band over the 85/170
#: boundary and makes both art sources land in the same regime (a single fixed
#: multiplier cannot: 1.6 exposes Freedoom's bar and blows out DOOM's).
STBAR_MEAN_GREY = 95


def stbar_rows(rgba: list[list[tuple[int, int, int, int]]],
               tw: int = HUD_W, th: int = HUD_H,
               target: int = STBAR_MEAN_GREY, *, dither: str = "none",
               dither_strength: float = 1.0) -> list[str]:
    """The status bar quantized to the HUD strip: ``th`` rows of ``tw`` hex
    digits, the repo's block-Lab method (:func:`quantize_title`) after the
    auto-exposure lift of :data:`STBAR_MEAN_GREY`.

    ``dither`` (default ``"none"``) is forwarded to :func:`quantize_title`; at
    the hi-res strip (:data:`HIRES_HUD_H` rows) it is what stops the bar
    collapsing into one flat slab of colour 8.
    """
    n = len(rgba) * len(rgba[0])
    mean = sum(sum(px[:3]) / 3 for row in rgba for px in row) / n
    if mean <= 0:
        raise ValueError("the status bar art is black")
    return quantize_title(rgba, tw, th, brightness=target / mean, dither=dither,
                          dither_strength=dither_strength)


#: The hi-res panel (M9, opt-in): 128x96 — twice 64x48 in both axes, so the
#: viewport is 80 rows and the HUD strip 16.  At this size the 320x32 bar is
#: 2.5x2 source pixels per cell (against 5x4) and the mugshot inset roughly
#: doubles, which is the resolution dithering needs to read as shading rather
#: than noise.
HIRES_W, HIRES_H, HIRES_H3D = 128, 96, 80

#: The monster bands at the hi-res screen: the committed ``MON_BANDS`` doubled,
#: because a billboard's size is a projection and the projection doubles with
#: the viewport.  Every height is then past the 14 rows one packed word holds,
#: which is why :func:`pack_sprite_columns_wide` exists and why the hi-res table
#: is two words a column.
HIRES_BANDS = tuple((2 * w, 2 * h) for w, h in MON_BANDS)

#: The pistol at the hi-res screen — the committed 11x10 doubled, quantized
#: from the source at that size rather than enlarged after the fact.
HIRES_GUN = (22, 20)
HIRES_HUD_W, HIRES_HUD_H = HIRES_W, HIRES_H - HIRES_H3D


def face_box(hud_w: int = HUD_W, hud_h: int = HUD_H, h3d: int = 40,
             ) -> tuple[int, int, int, int]:
    """``(col, panel_row, w, h)`` of the mugshot, DERIVED from the bar's own
    face inset (:data:`STBAR_REGIONS`) at the given strip geometry.

    At 64x8 over a 40-row viewport this is the committed ``(29, 40, 6, 7)``;
    at the hi-res strip (:data:`HIRES_HUD_W` x :data:`HIRES_HUD_H` over
    :data:`HIRES_H3D`) it is ``(58, 80, 13, 14)``.
    """
    c0, r0, c1, r1 = stbar_cells("face", hud_w, hud_h)
    return c0, h3d + r0, c1 - c0, r1 - r0


#: The HUD face's box, DERIVED from the bar's own face inset
#: (:data:`STBAR_REGIONS`): 6x7 at panel rows 40..46, columns 29..34 — where
#: DOOM's mugshot actually sits, not a hand-picked hole in an invented bezel.
#: The panel's 3D view is 40 rows tall, so the strip's row 0 is panel row 40.
FACE_COL, FACE_ROW, FACE_W, FACE_H = face_box()
#: The face-core crop (top, bottom, left, right fractions).  M5's 10x6 box was
#: twice DOOM's aspect, so it kept only the brow-to-chin band; the real inset
#: is taller than it is wide, like the 24x29 portrait, so the WHOLE mugshot
#: goes in — hair, face and shoulders, exactly what DOOM shows.
FACE_CROP = (0.0, 0.0, 0.0, 0.0)


def face_tables(faces: dict[str, list[list[tuple[int, int, int, int]]]],
                *, brightness: float = 1.4,
                background: tuple[int, int, int] = PALETTE[8],
                box: tuple[int, int, int, int] | None = None,
                dither: str = "none", dither_strength: float = 1.0,
                ) -> dict[str, list[tuple[int, int, str]]]:
    """``{state: runs}`` for the status-bar face: each source cropped to
    :data:`FACE_CROP`, composited onto the bar's own colour under the inset
    and block-Lab quantized to the face box — one opaque run per row (the CPU
    paints them as CURS + RUN words, so there is no arm budget to honour).

    ``box`` is a :func:`face_box` tuple, defaulting to the committed 6x7 slot;
    ``dither`` (default ``"none"``) is the M9 opt-in.
    """
    out = {}
    col, row0, fw, fh = box if box is not None else (FACE_COL, FACE_ROW, FACE_W, FACE_H)
    t, b, lft, rgt = FACE_CROP
    for name, rgba in faces.items():
        src = _crop_alpha(rgba)
        h, w = len(src), len(src[0])
        src = [row[int(w * lft):w - int(w * rgt)]
               for row in src[int(h * t):h - int(h * b)]]
        grid = quantize_sprite(src, fw, fh, background=background,
                               brightness=brightness, dither=dither,
                               dither_strength=dither_strength)
        out[name] = [(row0 + r, col, "".join("%x" % c for c in grid[r]))
                     for r in range(fh)]
    return out


#: Which IWAD lumps feed the --wad art overrides: the pistol pair and the
#: status-bar face family (centre gaze per pain band; EVL is the fire grimace).
IWAD_ART_LUMPS = {
    "gun_idle": "PISGA0", "gun_flash": "PISFA0",
    "face_healthy": "STFST01", "face_hurt": "STFST21",
    "face_bloody": "STFST41", "face_grim": "STFEVL0",
    "mon0": "POSSA1", "mon1": "TROOA1", "corpse": "POSSL0",
}

#: The status bar's lump(s).  v1.2+ and retail IWADs ship one 320x32 ``STBAR``;
#: DOOM v1.0/v1.1 shareware has no such lump and composites the bar from a
#: 104-wide left half and a 216-wide right half instead.  Both spell the same
#: 320x32 geometry, so :data:`STBAR_REGIONS` addresses either.
IWAD_STBAR_LUMPS = ("STBAR",)
IWAD_STBAR_HALVES = ("STMBARL", "STMBARR")


def iwad_stbar(wad: Wad, playpal: bytes) -> list[list[tuple[int, int, int, int]]]:
    """The IWAD's 320x32 status bar, whole or composited from its v1.0 halves."""
    for name in IWAD_STBAR_LUMPS:
        if name in wad:
            return decode_picture(wad.lump(name), playpal)
    halves = [decode_picture(wad.lump(n), playpal) for n in IWAD_STBAR_HALVES]
    if len(halves[0]) != len(halves[1]):
        raise ValueError("the status bar halves disagree on height")
    return [halves[0][y] + halves[1][y] for y in range(len(halves[0]))]


def iwad_art(path: Path, *, dither: str = "none",
             hud_size: tuple[int, int] = (HUD_W, HUD_H), h3d: int = 40,
             gun: tuple[int, int] = (11, 10), screen: tuple[int, int] | None = None,
             max_runs: int | None = 20, max_body: int = 12,
             bands: tuple[tuple[int, int], ...] = MON_BANDS,
             words_per_col: int = 1) -> dict:
    """The --wad art override bundle: WAD-derived pistol, status bar and face
    run tables (M5/M8: the local machines' GUN/GUNF arms, HUD background and
    FACE paint carry the user's own art; nothing from this path may be
    committed).

    ``dither``/``hud_size``/``h3d`` are the M9 opt-ins (the defaults are the
    64x8 strip over the 40-row viewport, undithered).

    ``gun``/``screen``/``max_runs``/``max_body`` size and place the pistol, and
    ``bands``/``words_per_col`` the monster billboards — all defaulting to the
    committed geometry.  Pass the hi-res set (:data:`HIRES_GUN`,
    :data:`HIRES_BANDS`, ``words_per_col=2``, ``max_runs=None``) and every
    sprite here is quantized from the lump at its final size rather than
    enlarged afterwards, which is the whole point of deriving art from the WAD
    instead of scaling someone else's quantization of it."""
    wad = read_wad(path)
    playpal = wad.lump("PLAYPAL")[:768]

    def pic(key: str):
        return decode_picture(wad.lump(IWAD_ART_LUMPS[key]), playpal)

    gun_idle, gun_fire = gun_tables(
        pic("gun_idle"), pic("gun_flash"), width=gun[0], height=gun[1],
        screen=screen or (HUD_W, h3d), max_runs=max_runs, max_body=max_body)
    hud_bg = stbar_rows(iwad_stbar(wad, playpal), *hud_size, dither=dither)
    box = face_box(*hud_size, h3d)
    faces = face_tables({
        "healthy": pic("face_healthy"), "hurt": pic("face_hurt"),
        "bloody": pic("face_bloody"), "grim": pic("face_grim"),
    }, background=PALETTE[int(hud_bg[box[1] - h3d][box[0]], 16)],
        box=box, dither=dither)
    sprites = monster_sprite_words(pic("mon0"), pic("mon1"), pic("corpse"),
                                   bands=bands, words_per_col=words_per_col)
    return {"gun_idle": gun_idle, "gun_fire": gun_fire, "faces": faces,
            "hud_bg": hud_bg, "monster_sprites": sprites}


# ── the Level bundle ─────────────────────────────────────────────────────────
@dataclass
class Level:
    """Everything deadman3d needs, plus the eyeball/report extras."""

    map_rows: list[str]                     # 64 printed rows, north at the top
    spawn: tuple[int, int]                  # open cell
    heading: int                            # 0..15
    title_rows: list[str]                   # 48 rows of 64 hex digits
    families: dict[str, int]                # texture name -> wall family
    #: 64 printed rows, same orientation as ``map_rows``: ``N`` = an open cell
    #: on a damage floor, ``.`` = anything else (M5's nukage bit plane).
    nukage_rows: list[str] = field(default_factory=list)
    #: ``[cx, cy, species]`` per kept monster (M7; see ``_monster_things``).
    monsters: list[list[int]] = field(default_factory=list)
    avg_colours: dict[str, tuple[int, int, int]] = field(default_factory=dict)
    stats: dict = field(default_factory=dict)

    def map_str(self) -> str:
        return "\n".join(self.map_rows) + "\n"

    def family_table(self) -> str:
        lines = ["texture -> wall family (average RGB; family = ANSI hue, "
                 f"gray under CIELAB chroma {CHROMA_GATE:g})"]
        for name in sorted(self.families):
            avg = self.avg_colours.get(name)
            if avg is None:
                a = "  (void fill)"
            else:
                a = f" ({avg[0]:3d},{avg[1]:3d},{avg[2]:3d})"
            lines.append(f"  {name:<8s} -> {self.families[name]}{a}")
        return "\n".join(lines)


def _finish_level(raster: Raster, avg: dict[str, tuple[int, int, int] | None],
                  title_rows: list[str], source: str) -> Level:
    families = {name: family_of(avg.get(name)) for name in
                sorted({t for t in raster.cells.values() if t != "#VOID"})}
    families["#VOID"] = 7
    grid = raster.grid
    rows = []
    nrows = []
    for p in range(grid):
        y = grid - 1 - p
        row = ""
        nrow = ""
        for x in range(grid):
            tex = raster.cells.get((x, y))
            row += "." if tex is None else f"{families[tex]:x}"
            nrow += "N" if tex is None and (x, y) in raster.nukage else "."
        rows.append(row)
        nrows.append(nrow)
    wall_cells = sum(1 for t in raster.cells.values() if t != "#VOID")
    used = sorted(set(families[t] for t in families if t != "#VOID"))
    stats = {
        "source": source,
        "bbox": raster.bbox,
        "grid": grid,
        "wall_cells": wall_cells,
        "open_cells": len(raster.open_cells),
        "void_filled": raster.void_filled,
        "textures": len(families) - 1,
        "families_used": used,
        "title_runs": _run_count(title_rows),
        **{f"nukage_{k}" if not k.startswith("nukage") else k: v
           for k, v in raster.nukage_stats.items()},
        **raster.monster_stats,
    }
    return Level(rows, raster.spawn, raster.heading, title_rows,
                 families, nrows,
                 [list(mon) for mon in raster.monsters],
                 {k: tuple(round(c) for c in v) for k, v in avg.items()
                  if v is not None}, stats)


def rle_runs(rows: list[str]) -> list[tuple[int, int]]:
    """The art's row-major RLE, ``(colour, count)`` — the same encoding
    ``deadman3d.title_runs`` produces, computed straight off the hex rows so
    the importer can price art it has not installed."""
    runs: list[tuple[int, int]] = []
    for ch in "".join(rows):
        c = int(ch, 16)
        if runs and runs[-1][0] == c:
            runs[-1] = (c, runs[-1][1] + 1)
        else:
            runs.append((c, 1))
    return runs


def rom_words(rows: list[str]) -> int:
    """The ROM/tape cost of a piece of art: ONE pre-encoded RUN command word
    per RLE run (``deadman3d.title_words``: ``8*(count*16 + colour) + C_RUN``).
    This is the number dithering has to buy — see :data:`DITHER_MODES`."""
    return len(rle_runs(rows))


def _run_count(rows: list[str]) -> int:
    flat = "".join(rows)
    return 1 + sum(1 for a, b in zip(flat, flat[1:], strict=False) if a != b) if flat else 0


# ── Freedoom mode ────────────────────────────────────────────────────────────
def _parse_textures_cfg(text: str) -> dict[str, list[str]]:
    """``textures.cfg`` -> {texture: [patch, ...]} (offsets not needed for an
    average; simplecpp #directives are ignored, so every branch contributes)."""
    texs: dict[str, list[str]] = {}
    cur: str | None = None
    for line in text.splitlines():
        line = line.split(";")[0].rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split()
        if line[0] not in " \t*" and len(parts) == 3:
            cur = parts[0]
            texs.setdefault(cur, [])
        elif parts[0] == "*" and cur and len(parts) >= 4:
            texs[cur].append(parts[1])
    return texs


def _png_avg(rgba: list[list[tuple[int, int, int, int]]]) -> tuple[float, float, float] | None:
    rs = gs = bs = n = 0
    for row in rgba:
        for r, g, b, a in row:
            if a > 128:
                rs += r
                gs += g
                bs += b
                n += 1
    return (rs / n, gs / n, bs / n) if n else None


def load_freedoom(root: Path, mapname: str = "E1M1", grid: int = 64,
                  min_len: float = 32.0, *, title_size: tuple[int, int] = (64, 48),
                  dither: str = "none") -> Level:
    """Import from a Freedoom checkout: levels/<map>.wad + textures.cfg +
    patches/*.png + graphics/titlepic/titlepic.png.

    ``title_size``/``dither`` are the M9 opt-ins; the defaults reproduce the
    committed art byte for byte."""
    wad = read_wad(root / "levels" / f"{mapname.lower()}.wad")
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    texs = _parse_textures_cfg(
        (root / "lumps" / "textures" / "textures.cfg").read_text(encoding="utf-8"))
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            path = root / "patches" / f"{patch.lower()}.png"
            if not path.exists():
                continue
            one = _png_avg(decode_png(path.read_bytes()))
            if one:
                # weight patches equally; exact per-pixel compositing is not
                # needed for a family decision
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_png(
        (root / "graphics" / "titlepic" / "titlepic.png").read_bytes()),
        *title_size, dither=dither)
    return _finish_level(raster, avg, title, f"freedoom:{mapname}")


# ── IWAD mode ────────────────────────────────────────────────────────────────
def _iwad_textures(wad: Wad) -> dict[str, list[str]]:
    """TEXTURE1/TEXTURE2 + PNAMES -> {texture: [patch lump name, ...]}."""
    pn = wad.lump("PNAMES")
    (n_p,), names = struct.unpack("<I", pn[:4]), []
    for i in range(n_p):
        names.append(_cstr(pn[4 + 8 * i:12 + 8 * i]).upper())
    texs: dict[str, list[str]] = {}
    for lumpname in ("TEXTURE1", "TEXTURE2"):
        if lumpname not in wad:
            continue
        data = wad.lump(lumpname)
        (count,) = struct.unpack("<I", data[:4])
        offsets = struct.unpack(f"<{count}I", data[4:4 + 4 * count])
        for off in offsets:
            tname = _cstr(data[off:off + 8])
            (npatch,) = struct.unpack("<H", data[off + 20:off + 22])
            patches = []
            for k in range(npatch):
                p = off + 22 + 10 * k
                (_ox, _oy, pidx) = struct.unpack("<hhH", data[p:p + 6])
                if pidx < len(names):
                    patches.append(names[pidx])
            texs[tname] = patches
    return texs


def load_iwad(path: Path, mapname: str = "E1M1", grid: int = 64,
              min_len: float = 32.0, *, title_size: tuple[int, int] = (64, 48),
              dither: str = "none") -> Level:
    """Import from a retail-format IWAD (everything from inside the WAD)."""
    wad = read_wad(path)
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    playpal = wad.lump("PLAYPAL")[:768]
    texs = _iwad_textures(wad)
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            if patch not in wad:
                continue
            one = _png_avg(decode_picture(wad.lump(patch), playpal))
            if one:
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_picture(wad.lump("TITLEPIC"), playpal),
                           *title_size, dither=dither)
    return _finish_level(raster, avg, title, f"iwad:{path.name}:{mapname}")


# ── output ───────────────────────────────────────────────────────────────────
def _png_bytes(pixels: list[list[tuple[int, int, int]]], scale: int = 8) -> bytes:
    """A minimal RGB PNG writer (same shape as deadman3d's fallback)."""
    h, w = len(pixels), len(pixels[0])
    raw = bytearray()
    for y in range(h):
        for _ in range(scale):
            raw.append(0)
            for x in range(w):
                raw.extend(bytes(pixels[y][x]) * scale)

    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body)))

    ihdr = struct.pack(">IIBBBBB", w * scale, h * scale, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw))) + chunk(b"IEND", b""))


def emit(level: Level, out_dir: Path) -> None:
    """Write the bundle: level.json + map.txt/title.txt/families.txt + the two
    eyeball PNGs (overhead + title)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "level.json").write_text(json.dumps({
        "map_rows": level.map_rows,
        "spawn": list(level.spawn),
        "heading": level.heading,
        "title_rows": level.title_rows,
        "families": level.families,
        "nukage_rows": level.nukage_rows,
        "monsters": level.monsters,
        "stats": level.stats,
    }, indent=1) + "\n", encoding="utf-8")
    (out_dir / "map.txt").write_text(level.map_str(), encoding="utf-8")
    if level.nukage_rows:
        (out_dir / "nukage.txt").write_text(
            "\n".join(level.nukage_rows) + "\n", encoding="utf-8")
    (out_dir / "title.txt").write_text("\n".join(level.title_rows) + "\n", encoding="utf-8")
    (out_dir / "families.txt").write_text(level.family_table() + "\n", encoding="utf-8")
    grid = len(level.map_rows)
    mon_cells = {(mx, my) for mx, my, _sp in level.monsters}
    overhead = []
    for p in range(grid):
        row = []
        for x in range(grid):
            y = grid - 1 - p
            ch = level.map_rows[p][x]
            if (x, y) == level.spawn:
                row.append((255, 255, 0))
            elif (x, y) in mon_cells:
                row.append((255, 0, 0))
            elif ch == ".":
                nuk = level.nukage_rows and level.nukage_rows[p][x] == "N"
                row.append((0, 130, 0) if nuk else (40, 40, 40))
            else:
                row.append(PALETTE[int(ch, 16)])
        overhead.append(row)
    (out_dir / "overhead.png").write_bytes(_png_bytes(overhead))
    title = [[PALETTE[int(c, 16)] for c in row] for row in level.title_rows]
    (out_dir / "title.png").write_bytes(_png_bytes(title))


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--freedoom", type=Path, metavar="DIR",
                     help="a Freedoom checkout/snapshot (pinned commit d14dbbe)")
    src.add_argument("--wad", type=Path, metavar="PATH",
                     help="a retail-format IWAD (local use only; do NOT commit outputs)")
    parser.add_argument("--map", default="E1M1", help="map marker lump (default E1M1)")
    parser.add_argument("--grid", type=int, default=64,
                        help="grid size (default 64; the demo's map word packing"
                             " supports future 128)")
    parser.add_argument("--min-len", type=float, default=32.0,
                        help="ignore one-sided linedefs shorter than this many map units")
    parser.add_argument("--dither", choices=DITHER_MODES, default="none",
                        help="title dithering (M9 opt-in; default none — the "
                             "committed art's exact method)")
    parser.add_argument("--title-size", default="64x48", metavar="WxH",
                        help="title art size (default 64x48; 128x96 is the "
                             "hi-res panel)")
    parser.add_argument("--out", type=Path, required=True, help="output directory")
    args = parser.parse_args(argv)
    tw, _, th = args.title_size.partition("x")
    title_size = (int(tw), int(th))
    if args.freedoom:
        level = load_freedoom(args.freedoom, args.map, args.grid, args.min_len,
                              title_size=title_size, dither=args.dither)
    else:
        level = load_iwad(args.wad, args.map, args.grid, args.min_len,
                          title_size=title_size, dither=args.dither)
    emit(level, args.out)
    print(json.dumps(level.stats))
    print(level.family_table())
    print(f"spawn {level.spawn} heading {level.heading}")
    print(f"wrote {args.out}/level.json (+ map/title/families/overhead/title.png)")


if __name__ == "__main__":
    main()
