#!/usr/bin/env python3
"""WAD level importer for deadman-3d: real DOOM-format geometry -> the 64x64 grid.

Two sources, one pipeline (see ``deadman3d.py`` for the consumer):

* **Freedoom mode** (``--freedoom DIR``): a checkout/snapshot of
  https://github.com/freedoom/freedoom (pinned commit ``d14dbbe``).  The level
  is ``levels/<map>.wad`` (a PWAD of just the map lumps), wall textures are
  composited from ``lumps/textures/textures.cfg`` + ``patches/*.png``, and the
  title screen is ``graphics/titlepic/titlepic.png``.  Freedoom content is
  BSD-licensed (COPYING.adoc) — the committed deadman-3d map, wall families
  and title screen are generated by this mode.

* **IWAD mode** (``--wad PATH``): a retail-format IWAD (e.g. a DOOM shareware
  ``DOOM1.WAD``).  Everything comes from inside the WAD: map lumps,
  ``TEXTURE1``/``TEXTURE2`` + ``PNAMES`` + patch lumps (DOOM picture format)
  + ``PLAYPAL`` for wall colours, ``TITLEPIC`` for the title.  **Nothing
  derived from a retail IWAD may be committed** — outputs belong in a
  git-ignored directory (``littleman/examples/local/``).

The pipeline:

1. Parse the WAD directory (12-byte header, 16-byte directory entries) and the
   fixed-size little-endian map lumps: VERTEXES (4 bytes: x, y), LINEDEFS
   (14 bytes), SIDEDEFS (30 bytes), THINGS (10 bytes).
2. Rasterize: the level bbox is fitted (uniform scale, centred, one-cell
   border) onto a ``grid``x``grid`` map.  Every **one-sided** linedef at least
   ``min_len`` map units long becomes wall cells via an exact supercover
   traversal; two-sided linedefs (room-to-room joins, doorways) and shorter
   detail lines are ignored.  Each wall cell inherits its dominant linedef's
   sidedef texture (weighted by linedef length).
3. Close the map: the player start (THINGS type 1, bumped to the nearest open
   cell if its own cell caught a wall) seeds a 4-connected flood fill; the
   reachable region must not touch the grid border (watertightness — a
   supercover of the level's closed one-sided perimeter cannot be crossed),
   and every unreachable cell is filled solid, so the committed map has no
   void a ray could escape into.
4. Colour: each texture name that occurs on a wall cell maps to a wall family
   1..7 — the ANSI palette index of its average colour (patches composited,
   alpha-weighted).  Because most DOOM-era textures are desaturated, the
   family is chosen by *hue* (CIELAB, families 1..6) with a chroma gate below
   which the texture is gray (family 7); ties collapse identical-hue textures
   into one family, which is the <=7-group clustering.
5. Title: the 320x200 title art (PNG or TITLEPIC picture lump) is quantized to
   64x48 with the repo's block-Lab method — per target block, the ANSI-16
   colour minimizing the sum of CIELAB distances over the source block's
   pixels — after a fixed x1.6 brightness lift (DOOM-era title art is dark;
   measured on both sources), then a single isolated-dot despeckle pass.

The output bundle (``--out DIR``) is ``level.json`` (map rows, spawn, heading,
title rows, the texture->family table) plus eyeball artifacts: ``map.txt``,
``title.txt``, ``overhead.png``, ``title.png``, ``families.txt``.

Stdlib only (struct + zlib carry the PNG codec) so the fast tests can cover
the parser on a synthetic in-memory WAD.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
import zlib
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path

__all__ = [
    "PALETTE", "Wad", "MapData", "Level", "DAMAGE_SPECIALS",
    "MONSTER_TYPES", "MAX_MONSTERS", "MON_BANDS",
    "read_wad", "parse_map", "supercover", "rasterize",
    "decode_png", "decode_picture", "srgb_to_lab", "family_of",
    "quantize_title", "despeckle", "quantize_sprite", "sprite_runs",
    "quantize_monster", "pack_sprite_columns", "monster_band_words",
    "monster_sprite_words",
    "gun_tables", "face_tables", "iwad_art",
    "load_freedoom", "load_iwad", "emit", "main",
]

#: The LM-75 ANSI-16 palette (== deadman3d.PALETTE; kept local so the importer
#: never imports the consumer).
PALETTE = [
    (0, 0, 0), (170, 0, 0), (0, 170, 0), (170, 85, 0),
    (0, 0, 170), (170, 0, 170), (0, 170, 170), (170, 170, 170),
    (85, 85, 85), (255, 85, 85), (85, 255, 85), (255, 255, 85),
    (85, 85, 255), (255, 85, 255), (85, 255, 255), (255, 255, 255),
]

NO_SIDE = 0xFFFF  # a linedef with no left sidedef is one-sided (solid)


# ── WAD parsing ──────────────────────────────────────────────────────────────
@dataclass
class Wad:
    """A parsed WAD: the ordered lump directory."""

    ident: str
    lumps: list[tuple[str, bytes]]

    def lump(self, name: str) -> bytes:
        for n, data in self.lumps:
            if n == name:
                return data
        raise KeyError(f"no lump {name!r} in this {self.ident}")

    def __contains__(self, name: str) -> bool:
        return any(n == name for n, _ in self.lumps)


@dataclass
class MapData:
    """One map's fixed-size-record lumps, decoded."""

    vertexes: list[tuple[int, int]]
    #: (v1, v2, flags, special, tag, right_sidedef, left_sidedef)
    linedefs: list[tuple[int, int, int, int, int, int, int]]
    #: (upper, lower, middle, sector)
    sidedefs: list[tuple[str, str, str, int]]
    #: (x, y, angle, type, flags)
    things: list[tuple[int, int, int, int, int]]
    #: (floor_h, ceil_h, floorpic, ceilpic, light, special, tag) — M5's damage
    #: floors come from ``special`` (see :data:`DAMAGE_SPECIALS`)
    sectors: list[tuple[int, int, str, str, int, int, int]] = field(default_factory=list)


#: The DOOM damage-floor family: 5%/10%/20% nukage and slime specials (4 is
#: 20% + light blink, 16 is 20%; 11 — end-level — deliberately excluded: at
#: this resolution it is an exit pad, not a pool).
DAMAGE_SPECIALS = frozenset({4, 5, 7, 16})

#: THINGS type -> monster species (M7): former humans (3004 zombieman, 9
#: shotgun guy — same species at this resolution, POSS art) are species 0,
#: imps (3001, TROO art) species 1.  Barrels and decorations are out of scope.
MONSTER_TYPES = {3004: 0, 9: 0, 3001: 1}

#: The monster table cap — the tape's ``MONB`` block is sized to it, and
#: E1M1's medium-skill single-player monster count fits.
MAX_MONSTERS = 16


def read_wad(data: bytes | Path) -> Wad:
    """Parse an IWAD/PWAD: 12-byte header, then 16-byte directory entries."""
    if isinstance(data, Path):
        data = data.read_bytes()
    ident, count, dir_off = struct.unpack("<4sII", data[:12])
    ident = ident.decode("ascii")
    if ident not in ("IWAD", "PWAD"):
        raise ValueError(f"not a WAD: magic {ident!r}")
    lumps = []
    for i in range(count):
        off, size, raw = struct.unpack("<II8s", data[dir_off + 16 * i:dir_off + 16 * i + 16])
        name = raw.rstrip(b"\0").decode("ascii", "replace")
        lumps.append((name, data[off:off + size]))
    return Wad(ident, lumps)


def _cstr(raw: bytes) -> str:
    return raw.rstrip(b"\0").decode("ascii", "replace")


def parse_map(wad: Wad, mapname: str) -> MapData:
    """The named map's THINGS/LINEDEFS/SIDEDEFS/VERTEXES, from the lumps that
    follow its marker (the marker lump itself is empty)."""
    names = [n for n, _ in wad.lumps]
    try:
        at = names.index(mapname)
    except ValueError:
        raise KeyError(f"no map {mapname!r}; lumps: {names[:8]}...") from None
    section = {n: d for n, d in wad.lumps[at + 1:at + 11]}
    need = ("THINGS", "LINEDEFS", "SIDEDEFS", "VERTEXES")
    missing = [n for n in need if n not in section]
    if missing:
        raise ValueError(f"map {mapname} is missing lumps {missing}")
    vertexes = [struct.unpack("<hh", d) for d in _records(section["VERTEXES"], 4)]
    linedefs = [struct.unpack("<HHHHHHH", d) for d in _records(section["LINEDEFS"], 14)]
    sidedefs = []
    for d in _records(section["SIDEDEFS"], 30):
        _xo, _yo, up, lo, mid, sector = struct.unpack("<hh8s8s8sH", d)
        sidedefs.append((_cstr(up), _cstr(lo), _cstr(mid), sector))
    things = [struct.unpack("<hhHHH", d) for d in _records(section["THINGS"], 10)]
    sectors = []
    for d in _records(section.get("SECTORS", b""), 26):
        fh, ch, fp, cp, light, special, tag = struct.unpack("<hh8s8shhh", d)
        sectors.append((fh, ch, _cstr(fp), _cstr(cp), light, special, tag))
    return MapData(vertexes, linedefs, sidedefs, things, sectors)


def _records(data: bytes, size: int):
    return (data[i:i + size] for i in range(0, len(data) - size + 1, size))


# ── rasterization ────────────────────────────────────────────────────────────
def supercover(x0: float, y0: float, x1: float, y1: float) -> set[tuple[int, int]]:
    """Every grid cell the segment touches (Amanatides–Woo traversal; a
    crossing within eps of a cell corner adds both side cells, so a
    4-connected path of empty cells can never slip across the segment)."""
    eps = 1e-9
    cells: set[tuple[int, int]] = set()
    x, y = math.floor(x0), math.floor(y0)
    xe, ye = math.floor(x1), math.floor(y1)
    dx, dy = x1 - x0, y1 - y0
    step_x = 1 if dx > 0 else -1
    step_y = 1 if dy > 0 else -1
    # t at which the ray crosses the next vertical / horizontal grid line
    t_max_x = ((x + (step_x > 0)) - x0) / dx if dx else math.inf
    t_max_y = ((y + (step_y > 0)) - y0) / dy if dy else math.inf
    t_dx = abs(1 / dx) if dx else math.inf
    t_dy = abs(1 / dy) if dy else math.inf
    cells.add((x, y))
    guard = 4 * (abs(xe - x) + abs(ye - y)) + 8
    while (x, y) != (xe, ye) and guard:
        guard -= 1
        if abs(t_max_x - t_max_y) < eps:  # corner crossing: cover both cells
            cells.add((x + step_x, y))
            cells.add((x, y + step_y))
            x += step_x
            y += step_y
            t_max_x += t_dx
            t_max_y += t_dy
        elif t_max_x < t_max_y:
            x += step_x
            t_max_x += t_dx
        else:
            y += step_y
            t_max_y += t_dy
        cells.add((x, y))
    # A segment lying exactly ON a grid line borders both flanking cells
    # (e.g. an axis-aligned wall at an integral coordinate): cover both.
    if dx == 0 and abs(x0 - round(x0)) < eps:
        cells |= {(cx - 1, cy) for cx, cy in cells}
    if dy == 0 and abs(y0 - round(y0)) < eps:
        cells |= {(cx, cy - 1) for cx, cy in cells}
    return cells


@dataclass
class Raster:
    """The rasterized level, before colours."""

    grid: int
    cells: dict[tuple[int, int], str]        # wall cell -> dominant texture
    open_cells: set[tuple[int, int]]         # reachable from the spawn
    spawn: tuple[int, int]
    heading: int                             # 0..15, CCW from east
    bbox: tuple[int, int, int, int]          # minx, miny, maxx, maxy
    void_filled: int = 0
    #: open cells standing on a damage floor (sector special 4/5/7/16)
    nukage: set[tuple[int, int]] = field(default_factory=set)
    nukage_stats: dict = field(default_factory=dict)
    #: ``(cx, cy, species)`` per kept monster THING (M7): medium-skill,
    #: single-player, open-cell, deduped, capped at :data:`MAX_MONSTERS`.
    monsters: list[tuple[int, int, int]] = field(default_factory=list)
    monster_stats: dict = field(default_factory=dict)


def rasterize(m: MapData, grid: int = 64, min_len: float = 32.0) -> Raster:
    """Project the level onto ``grid`` x ``grid`` (uniform scale, centred, one
    border cell), supercover the long one-sided linedefs, close the map.

    Asserts, in order: a player-1 start exists; the spawn cell is open (bumped
    <=2 cells if the exact cell caught a wall); the flood fill from the spawn
    never reaches the grid border (watertight).  Unreachable cells are then
    filled solid, so the result has no void at all.
    """
    xs = [v[0] for v in m.vertexes]
    ys = [v[1] for v in m.vertexes]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    w, h = maxx - minx, maxy - miny
    scale = (grid - 2) / max(w, h)
    offx = 1 + ((grid - 2) - w * scale) / 2
    offy = 1 + ((grid - 2) - h * scale) / 2

    def to_grid(x: float, y: float) -> tuple[float, float]:
        return (x - minx) * scale + offx, (y - miny) * scale + offy

    weight: dict[tuple[int, int], Counter] = defaultdict(Counter)
    for v1, v2, _flags, _special, _tag, right, left in m.linedefs:
        if left != NO_SIDE or right == NO_SIDE:
            continue  # two-sided (or degenerate): not a solid wall
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        length = math.hypot(bx - ax, by - ay)
        if length < min_len:
            continue  # detail geometry
        up, lo, mid, _sector = m.sidedefs[right]
        tex = mid if mid and mid != "-" else (up if up and up != "-" else lo)
        if not tex or tex == "-":
            continue
        for c in supercover(*to_grid(ax, ay), *to_grid(bx, by)):
            if 0 <= c[0] < grid and 0 <= c[1] < grid:
                weight[c][tex] += length
    cells = {c: cnt.most_common(1)[0][0] for c, cnt in weight.items()}

    starts = [t for t in m.things if t[3] == 1]
    assert starts, "no player-1 start (THINGS type 1)"
    sx, sy, angle = starts[0][0], starts[0][1], starts[0][2]
    gx, gy = to_grid(sx, sy)
    spawn = (int(gx), int(gy))
    heading = round(angle / 22.5) % 16
    if spawn in cells:  # the start hugged a wall closer than one cell
        near = [(abs(dx) + abs(dy), (spawn[0] + dx, spawn[1] + dy))
                for dx in range(-2, 3) for dy in range(-2, 3)
                if (spawn[0] + dx, spawn[1] + dy) not in cells]
        assert near, f"no open cell within 2 of the spawn {spawn}"
        spawn = min(near)[1]
    assert 0 < spawn[0] < grid - 1 and 0 < spawn[1] < grid - 1, \
        f"spawn {spawn} out of the map interior"

    open_cells = {spawn}
    queue = deque([spawn])
    while queue:
        x, y = queue.popleft()
        for nxt in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nxt[0] < grid and 0 <= nxt[1] < grid \
                    and nxt not in cells and nxt not in open_cells:
                open_cells.add(nxt)
                queue.append(nxt)
    leaks = [c for c in open_cells if c[0] in (0, grid - 1) or c[1] in (0, grid - 1)]
    assert not leaks, f"map leaks into the void at {sorted(leaks)[:8]}"

    nukage, nstats = _damage_floors(m, to_grid, grid, open_cells)
    monsters, mstats = _monster_things(m, to_grid, open_cells)

    void = 0
    for x in range(grid):
        for y in range(grid):
            if (x, y) not in cells and (x, y) not in open_cells:
                cells[(x, y)] = "#VOID"
                void += 1
    return Raster(grid, cells, open_cells, spawn, heading,
                  (minx, miny, maxx, maxy), void, nukage, nstats,
                  monsters, mstats)


def _monster_things(m: MapData, to_grid,
                    open_cells: set[tuple[int, int]],
                    ) -> tuple[list[tuple[int, int, int]], dict]:
    """The kept monster THINGS (M7): ``(cx, cy, species)`` in THINGS order.

    The filter, in order: a :data:`MONSTER_TYPES` type; present on medium
    skill (``flags & 2``); not multiplayer-only (``flags & 0x10`` clear); its
    grid cell open (a monster inside a supercovered wall cell would never be
    reachable or visible); the cell not already taken (one billboard per
    cell); capped at :data:`MAX_MONSTERS` in THINGS order.
    """
    stats = {"monster_things": 0, "skill_dropped": 0, "closed_dropped": 0,
             "dupe_dropped": 0, "cap_dropped": 0}
    kept: list[tuple[int, int, int]] = []
    taken: set[tuple[int, int]] = set()
    for x, y, _angle, mtype, flags in m.things:
        species = MONSTER_TYPES.get(mtype)
        if species is None:
            continue
        stats["monster_things"] += 1
        if not (flags & 2) or (flags & 0x10):
            stats["skill_dropped"] += 1
            continue
        gx, gy = to_grid(x, y)
        cell = (int(gx), int(gy))
        if cell not in open_cells:
            stats["closed_dropped"] += 1
            continue
        if cell in taken:
            stats["dupe_dropped"] += 1
            continue
        if len(kept) >= MAX_MONSTERS:
            stats["cap_dropped"] += 1
            continue
        taken.add(cell)
        kept.append((cell[0], cell[1], species))
    stats["monsters_kept"] = len(kept)
    return kept, stats


def _damage_floors(m: MapData, to_grid, grid: int,
                   open_cells: set[tuple[int, int]]) -> tuple[set[tuple[int, int]], dict]:
    """Which open cells stand on a damage floor (M5).

    Region flood fill: the open cells are partitioned into regions bounded by
    the supercover of **all** linedefs — two-sided ones included, as thin
    boundaries for regioning only (they are room-to-room joins, not walls).
    Each region's sector is then identified by *sampling*: points either side
    of every linedef (offset along its normal, the right side facing the right
    sidedef — DOOM's front) vote their sidedef's sector into whatever region
    they land in, weighted by linedef length; the plurality wins.  A region
    whose sector's special is in :data:`DAMAGE_SPECIALS` is nukage.  Open
    cells *on* a boundary (a pool's rim) resolve by their own cell votes,
    then by neighbour majority.  If the specials find nothing but flats named
    NUKAGE*/SLIME*/LAVA* exist, the flat-name fallback is used (documented in
    ``stats['nukage_by']``).
    """
    stats: dict = {"regions": 0, "unresolved_regions": 0, "nukage_cells": 0,
                   "damage_sectors": 0, "nukage_by": "specials"}
    if not m.sectors:
        return set(), stats

    def damaging_special(sec: int) -> bool:
        return m.sectors[sec][5] in DAMAGE_SPECIALS

    def damaging_flat(sec: int) -> bool:
        return m.sectors[sec][2].upper().startswith(("NUKAGE", "SLIME", "LAVA"))

    stats["damage_sectors"] = sum(1 for s in range(len(m.sectors)) if damaging_special(s))
    stats["flat_sectors"] = sum(1 for s in range(len(m.sectors)) if damaging_flat(s))

    # 1. The boundary raster: every linedef, any length, both-sided included.
    boundary: set[tuple[int, int]] = set()
    for v1, v2, _flags, _special, _tag, _right, _left in m.linedefs:
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        if (ax, ay) == (bx, by):
            continue
        for c in supercover(*to_grid(ax, ay), *to_grid(bx, by)):
            if 0 <= c[0] < grid and 0 <= c[1] < grid:
                boundary.add(c)

    # 2. Regions: 4-connected components of open cells off the boundary.
    region_of: dict[tuple[int, int], int] = {}
    regions: list[list[tuple[int, int]]] = []
    for cell in sorted(open_cells):
        if cell in boundary or cell in region_of:
            continue
        rid = len(regions)
        comp = [cell]
        region_of[cell] = rid
        queue = deque([cell])
        while queue:
            x, y = queue.popleft()
            for nxt in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                if nxt in open_cells and nxt not in boundary and nxt not in region_of:
                    region_of[nxt] = rid
                    comp.append(nxt)
                    queue.append(nxt)
        regions.append(comp)
    stats["regions"] = len(regions)

    # 3. Sector votes: sample points either side of each linedef.  The right
    # sidedef faces the right of v1->v2, which in this y-up frame is the
    # normal (dy, -dx).
    votes: dict[int, Counter] = defaultdict(Counter)
    cell_votes: dict[tuple[int, int], Counter] = defaultdict(Counter)
    for v1, v2, _flags, _special, _tag, right, left in m.linedefs:
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        gax, gay = to_grid(ax, ay)
        gbx, gby = to_grid(bx, by)
        dx, dy = gbx - gax, gby - gay
        ln = math.hypot(dx, dy)
        if ln < 1e-9:
            continue
        nx, ny = dy / ln, -dx / ln
        length = math.hypot(bx - ax, by - ay)
        for side, sd in ((1.0, right), (-1.0, left)):
            if sd == NO_SIDE or sd >= len(m.sidedefs):
                continue
            sector = m.sidedefs[sd][3]
            if sector >= len(m.sectors):
                continue
            for f in (0.25, 0.5, 0.75):
                for off in (0.6, 1.2):
                    px = gax + f * dx + side * off * nx
                    py = gay + f * dy + side * off * ny
                    cell = (math.floor(px), math.floor(py))
                    rid = region_of.get(cell)
                    if rid is not None:
                        votes[rid][sector] += length
                    elif cell in open_cells:  # an open boundary cell (a rim)
                        cell_votes[cell][sector] += length

    sector_of_region = {rid: cnt.most_common(1)[0][0] for rid, cnt in votes.items()}
    stats["unresolved_regions"] = len(regions) - len(sector_of_region)

    def resolve(damaging) -> set[tuple[int, int]]:
        nukage: set[tuple[int, int]] = set()
        clear: set[tuple[int, int]] = set()
        for rid, comp in enumerate(regions):
            sec = sector_of_region.get(rid)
            (nukage if sec is not None and damaging(sec) else clear).update(comp)
        # The rims: first by their own votes, then two neighbour-majority passes.
        rim = [c for c in open_cells if c not in region_of]
        rest = []
        for cell in rim:
            if cell_votes.get(cell):
                (nukage if damaging(cell_votes[cell].most_common(1)[0][0])
                 else clear).add(cell)
            else:
                rest.append(cell)
        for _ in range(2):
            for cell in list(rest):
                x, y = cell
                nb = [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
                n_nuk = sum(1 for c in nb if c in nukage)
                n_clr = sum(1 for c in nb if c in clear)
                if n_nuk + n_clr:
                    (nukage if n_nuk > n_clr else clear).add(cell)
                    rest.remove(cell)
        return nukage

    nukage = resolve(damaging_special)
    if not nukage and stats["flat_sectors"]:
        stats["nukage_by"] = "flats"
        nukage = resolve(damaging_flat)
    # Agreement between the two definitions, for the report.
    stats["special_vs_flat_disagree"] = sum(
        1 for s in range(len(m.sectors)) if damaging_special(s) != damaging_flat(s))
    stats["nukage_cells"] = len(nukage)
    return nukage, stats


# ── colours ──────────────────────────────────────────────────────────────────
def srgb_to_lab(rgb: tuple[float, float, float]) -> tuple[float, float, float]:
    """CIELAB (D65) — the same conversion the title/gun quantization used."""
    def lin(c: float) -> float:
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (lin(c) for c in rgb)
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883

    def f(t: float) -> float:
        return t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116

    fx, fy, fz = f(x), f(y), f(z)
    return 116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)


_LAB = [srgb_to_lab(p) for p in PALETTE]
_HUES = {i: math.atan2(_LAB[i][2], _LAB[i][1]) for i in range(1, 7)}
#: Below this CIELAB chroma a texture is just gray (family 7).  DOOM-era
#: metals/concretes sit around 4..8; bricks and screens well above 10.
CHROMA_GATE = 10.0


def family_of(avg: tuple[float, float, float] | None) -> int:
    """Wall family 1..7 for a texture's average colour: gray under the chroma
    gate, else the hue-nearest of the six chromatic ANSI colours."""
    if avg is None:
        return 7
    _l, a, b = srgb_to_lab(avg)
    if math.hypot(a, b) < CHROMA_GATE:
        return 7
    hue = math.atan2(b, a)

    def dist(i: int) -> float:
        d = abs(hue - _HUES[i])
        return min(d, 2 * math.pi - d)

    return min(range(1, 7), key=dist)


# ── PNG decode (stdlib; the subset Freedoom's assets use) ────────────────────
def decode_png(data: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a non-interlaced PNG (bit depth 1/2/4/8; colour types
    0 gray, 2 RGB, 3 palette, 4 gray+alpha, 6 RGBA; tRNS honoured)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    w = h = bitd = ctype = 0
    plte: list[tuple[int, int, int]] = []
    trns = b""
    idat = b""
    at = 8
    while at < len(data):
        (ln,), tag = struct.unpack(">I", data[at:at + 4]), data[at + 4:at + 8]
        body = data[at + 8:at + 8 + ln]
        at += 12 + ln
        if tag == b"IHDR":
            w, h, bitd, ctype, comp, filt, inter = struct.unpack(">IIBBBBB", body)
            if inter:
                raise ValueError("interlaced PNG unsupported")
            if comp or filt:
                raise ValueError("nonstandard PNG compression/filter")
        elif tag == b"PLTE":
            plte = [tuple(body[i:i + 3]) for i in range(0, len(body), 3)]
        elif tag == b"tRNS":
            trns = body
        elif tag == b"IDAT":
            idat += body
        elif tag == b"IEND":
            break
    raw = zlib.decompress(idat)
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bpp = max(1, channels * bitd // 8)
    stride = (w * channels * bitd + 7) // 8
    rows: list[bytearray] = []
    prev = bytearray(stride)
    for yy in range(h):
        f = raw[yy * (stride + 1)]
        line = bytearray(raw[yy * (stride + 1) + 1:(yy + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1:
                line[i] = (line[i] + a) & 0xFF
            elif f == 2:
                line[i] = (line[i] + b) & 0xFF
            elif f == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        rows.append(line)
        prev = line

    def samples(line: bytearray):
        if bitd == 8:
            yield from line
        else:
            per = 8 // bitd
            mask = (1 << bitd) - 1
            for byte in line:
                for k in range(per):
                    yield (byte >> (8 - bitd * (k + 1))) & mask

    out = []
    scale = 255 // ((1 << bitd) - 1) if ctype != 3 else 1
    for line in rows:
        vals = list(samples(line))
        row = []
        for xx in range(w):
            v = vals[xx * channels:(xx + 1) * channels]
            if ctype == 3:
                r, g, b = plte[v[0]]
                a = trns[v[0]] if v[0] < len(trns) else 255
                row.append((r, g, b, a))
            elif ctype == 0:
                g = v[0] * scale
                row.append((g, g, g, 255))
            elif ctype == 4:
                g = v[0] * scale
                row.append((g, g, g, v[1] * scale))
            elif ctype == 2:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, 255))
            else:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, v[3] * scale))
        out.append(row)
    return out


# ── DOOM picture format (IWAD patches, TITLEPIC) ─────────────────────────────
def decode_picture(data: bytes, playpal: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a DOOM picture lump: a header of column offsets, each
    column a run of posts (top-delta, length, pad, pixels..., pad), 0xFF ends."""
    w, h, _lo, _to = struct.unpack("<HHhh", data[:8])
    cols = struct.unpack(f"<{w}I", data[8:8 + 4 * w])
    rows = [[(0, 0, 0, 0)] * w for _ in range(h)]
    for x, off in enumerate(cols):
        at = off
        while data[at] != 0xFF:
            top, ln = data[at], data[at + 1]
            for k in range(ln):
                idx = data[at + 3 + k]
                y = top + k
                if y < h:
                    r, g, b = playpal[3 * idx:3 * idx + 3]
                    rows[y][x] = (r, g, b, 255)
            at += 4 + ln
    return rows


# ── the title screen ─────────────────────────────────────────────────────────
#: DOOM-era title art is dark; a fixed linear brightness lift keeps the marine
#: (and the shareware IWAD's title) out of the black/dark-gray sump when the
#: 16-colour palette quantizes it.  Chosen by eyeballing 1.0/1.4/1.6/1.8 on
#: both title sources.
TITLE_BRIGHTNESS = 1.6


def quantize_title(rgba: list[list[tuple[int, int, int, int]]],
                   tw: int = 64, th: int = 48,
                   brightness: float = TITLE_BRIGHTNESS) -> list[str]:
    """The repo's block-Lab method at ``tw`` x ``th``: per target block pick
    the ANSI-16 colour minimizing the summed CIELAB distance over the source
    block's (brightness-lifted) pixels; then one despeckle pass."""
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], list[float]] = {}

    def dists(px: tuple[int, int, int, int]) -> list[float]:
        rgb = tuple(min(255, round(c * brightness)) for c in px[:3])
        if rgb not in cache:
            lab = srgb_to_lab(rgb)
            cache[rgb] = [math.dist(lab, palette_lab) for palette_lab in _LAB]
        return cache[rgb]

    grid = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0] * 16
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    d = dists(rgba[yy][xx])
                    for i in range(16):
                        acc[i] += d[i]
            row.append(min(range(16), key=acc.__getitem__))
        grid.append(row)
    grid = despeckle(grid)
    return ["".join(f"{c:x}" for c in row) for row in grid]


def despeckle(grid: list[list[int]]) -> list[list[int]]:
    """A pixel whose 4-neighbours all agree on another colour joins them."""
    h, w = len(grid), len(grid[0])
    out = [row[:] for row in grid]
    for y in range(h):
        for x in range(w):
            nb = [grid[y + dy][x + dx]
                  for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                  if 0 <= x + dx < w and 0 <= y + dy < h]
            if len(nb) == 4 and len(set(nb)) == 1 and nb[0] != grid[y][x]:
                out[y][x] = nb[0]
    return out


# ── sprite art (M5: the HUD face; the --wad art overrides) ───────────────────
def quantize_sprite(rgba: list[list[tuple[int, int, int, int]]], tw: int, th: int,
                    *, background: tuple[int, int, int] | None = None,
                    brightness: float = 1.0,
                    ) -> list[list[int | None]]:
    """Block-Lab quantize a sprite to ``tw`` x ``th``.

    With ``background`` given, the sprite is composited onto it first and every
    cell is opaque (the HUD face on the field gray).  Without it, a target cell
    whose source block is mostly transparent stays ``None`` (the pistol's
    outline), and only opaque pixels vote.
    """
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], list[float]] = {}

    def dists(rgb: tuple[int, int, int]) -> list[float]:
        rgb = tuple(min(255, round(c * brightness)) for c in rgb)
        if rgb not in cache:
            lab = srgb_to_lab(rgb)
            cache[rgb] = [math.dist(lab, pl) for pl in _LAB]
        return cache[rgb]

    grid: list[list[int | None]] = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row: list[int | None] = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0] * 16
            opaque = total = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    r, g, b, a = rgba[yy][xx]
                    total += 1
                    if a > 128:
                        opaque += 1
                        d = dists((r, g, b))
                    elif background is not None:
                        d = dists(background)
                    else:
                        continue
                    for i in range(16):
                        acc[i] += d[i]
            if background is None and opaque * 2 < total:
                row.append(None)
            else:
                row.append(min(range(16), key=acc.__getitem__))
        grid.append(row)
    return grid


def sprite_runs(grid: list[list[int | None]], row0: int, col0: int,
                *, max_body: int = 12) -> list[tuple[int, int, str]]:
    """``(row, col, colors)`` runs for the DOOM unit's sprite arms.

    Contiguous opaque spans per row, split so every run fits the arm's descent
    windows — the token accounting mirrors ``d3_unit._pixel_tokens`` (one load
    for a colour 0..9, two for a..f, one send per pixel; ``max_body`` is the
    DATA window's 12 rows, counted from the first send).
    """
    runs: list[tuple[int, int, str]] = []
    for r, row in enumerate(grid):
        c = 0
        while c < len(row):
            if row[c] is None:
                c += 1
                continue
            start = c
            colors = ""
            cur: int | None = None
            body = 0  # tokens from the first send, d3_unit's window budget
            while c < len(row) and row[c] is not None:
                px = row[c]
                cost = (0 if px == cur else (1 if px < 10 else 2)) + 1
                if colors and body + cost > max_body:
                    break  # split: the next pixel opens a fresh run
                # the first pixel's loads are the run's lead, not its body
                body += cost if colors else 1
                colors += "%x" % px
                cur = px
                c += 1
            runs.append((row0 + r, col0 + start, colors))
    return runs


def _crop_alpha(rgba: list[list[tuple[int, int, int, int]]]):
    """The sprite's opaque bounding box (DOOM picture lumps pad heavily)."""
    ys = [y for y, row in enumerate(rgba) if any(px[3] > 128 for px in row)]
    xs = [x for x in range(len(rgba[0])) if any(row[x][3] > 128 for row in rgba)]
    if not ys or not xs:
        raise ValueError("sprite is fully transparent")
    return [row[min(xs):max(xs) + 1] for row in rgba[min(ys):max(ys) + 1]]


#: The three baked billboard scale bands (M7): ``(width, height)`` near, mid,
#: far.  Heights <= 14 keep a whole sprite column in ONE packed word (16
#: nibbles max, top nibble below 2**63 by construction); the golden model's
#: ``BAND_T`` thresholds pick the band from the projected depth.
MON_BANDS = ((10, 14), (6, 9), (4, 5))

#: A monster billboard cannot paint black: colour 0 doubles as transparent in
#: the packed columns, so an opaque near-black block maps to dark gray 8.
MON_BLACK = 8


#: Below this CIELAB chroma a billboard block is achromatic; DOOM-era monster
#: skin sits at 7..19, deep shadows below.  Lower than the wall families'
#: gate (10) on purpose: a billboard must READ against the gray floor 8 and
#: walls 7, so faint hues are kept rather than flattened.
MON_CHROMA_GATE = 6.0
#: An achromatic block lighter than this CIELAB L is light gray 7, else 8.
MON_L_GRAY = 45.0
#: A chromatic block lighter than this L takes the bright ANSI variant (+8).
MON_L_BRIGHT = 55.0


def quantize_monster(rgba: list[list[tuple[int, int, int, int]]],
                     tw: int, th: int, *, brightness: float = 1.0,
                     ) -> list[list[int]]:
    """Hue-forward block quantize of a monster sprite to ``tw`` x ``th``.

    Billboard rules: a mostly-transparent block is colour 0 (the packed
    columns' transparency); an opaque block takes its alpha-weighted average
    colour through the wall families' hue logic — gray (7 light / 8 dark)
    under :data:`MON_CHROMA_GATE`, else the hue-nearest chromatic ANSI colour
    (bright variant above :data:`MON_L_BRIGHT`).  Plain block-Lab was tried
    first and flattens Freedoom's dark-brown imps and olive zombimen into the
    floor's own gray 8; hue-forward keeps them readable, exactly as
    :func:`family_of` keeps the desaturated wall textures apart.  Black is
    never produced (colour 0 is transparency): a black-ish block is 8.
    """
    hh, ww = len(rgba), len(rgba[0])
    grid: list[list[int]] = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row: list[int] = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            rs = gs = bs = opaque = total = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    r, g, b, a = rgba[yy][xx]
                    total += 1
                    if a > 128:
                        opaque += 1
                        rs += r
                        gs += g
                        bs += b
            if opaque * 2 < total:
                row.append(0)
                continue
            avg = tuple(min(255.0, c / opaque * brightness) for c in (rs, gs, bs))
            l, a_, b_ = srgb_to_lab(avg)
            if math.hypot(a_, b_) < MON_CHROMA_GATE:
                row.append(7 if l > MON_L_GRAY else MON_BLACK)
                continue
            hue = math.atan2(b_, a_)

            def dist(i: int) -> float:
                d = abs(hue - _HUES[i])
                return min(d, 2 * math.pi - d)

            fam = min(range(1, 7), key=dist)
            row.append(fam + 8 if l > MON_L_BRIGHT else fam)
        grid.append(row)
    return grid


def pack_sprite_columns(grid: list[list[int]]) -> list[int]:
    """One packed word per sprite column, **bottom pixel = nibble 0**.

    The paint chain's bottom-up nibble walk (``c = Q % 16; Q //= 16``) reads
    these; height <= 14 keeps every word under 2**63 (16**14 == 2**56).
    """
    h, w = len(grid), len(grid[0])
    assert h <= 14, f"sprite height {h} > 14 would overflow a packed word"
    words = []
    for x in range(w):
        word = 0
        for j in range(h):  # j = rows above the bottom
            word += grid[h - 1 - j][x] * 16 ** j
        assert 0 <= word < 2 ** 63
        words.append(word)
    return words


def monster_band_words(rgba: list[list[tuple[int, int, int, int]]],
                       *, pad_to_bands: bool = False,
                       brightness: float = 1.0) -> list[int]:
    """The 20 packed words of one sprite's three bands (10+6+4 columns).

    ``pad_to_bands`` is the corpse path: the source (a low, wide death frame)
    is quantized to the band width at its own proportional height (floor 2)
    and padded with transparent top rows to the band height, so the paint
    chain needs no extra entry points.
    """
    src = _crop_alpha(rgba)
    sh, sw = len(src), len(src[0])
    words: list[int] = []
    for bw, bh in MON_BANDS:
        if pad_to_bands:
            ch = max(2, min(bh, round(bw * sh / sw)))
            grid = quantize_monster(src, bw, ch, brightness=brightness)
            grid = [[0] * bw for _ in range(bh - ch)] + grid
        else:
            grid = quantize_monster(src, bw, bh, brightness=brightness)
        words += pack_sprite_columns(grid)
    assert len(words) == sum(w for w, _h in MON_BANDS) == 20
    return words


def monster_sprite_words(mon0_rgba, mon1_rgba, corpse_rgba,
                         *, brightness: float = 1.0) -> list[int]:
    """The whole 60-word ``SPRB`` table: species 0 (POSS art) bands, species 1
    (TROO art) bands, then the shared corpse frame padded to the band boxes.
    Column base offsets are ``species * 20 + (0, 10, 16)[band]`` (corpse:
    ``40 + ...``, an M7b consumer)."""
    return (monster_band_words(mon0_rgba, brightness=brightness)
            + monster_band_words(mon1_rgba, brightness=brightness)
            + monster_band_words(corpse_rgba, pad_to_bands=True,
                                 brightness=brightness))


def gun_tables(idle_rgba, flash_rgba, *, width: int = 11, height: int = 10,
               brightness: float = 1.0):
    """``(GUN_IDLE, GUN_FIRE)`` run tables from a pistol + muzzle-flash pair.

    The committed art's construction: the idle gun bottom-centred on the
    viewport (bottom row 39), the fire variant the same gun one row higher
    with the flash blooming directly above it.
    """
    idle = quantize_sprite(_crop_alpha(idle_rgba), width, height,
                           brightness=brightness)
    idle_runs = sprite_runs(idle, 40 - height, (64 - width) // 2)
    flash_src = _crop_alpha(flash_rgba)
    fh = 4
    fw = max(2, min(10, round(fh * len(flash_src[0]) / len(flash_src))))
    flash = quantize_sprite(flash_src, fw, fh, brightness=brightness)
    # the flash sits clear above the RECOILED gun (whose top row is
    # 40 - height - 1), exactly like the committed art's 25..28 band
    flash_runs = sprite_runs(flash, 40 - height - fh - 1, 32 - fw // 2)
    fire_runs = flash_runs + [(r - 1, c, colors) for r, c, colors in idle_runs]
    for name, runs in (("idle", idle_runs), ("fire", fire_runs)):
        if len(runs) > 20:
            raise ValueError(
                f"the {name} pistol quantized to {len(runs)} runs; the unit's "
                "sprite arms fit 20 (leaf spill bound) — coarsen the quantize")
    return idle_runs, fire_runs


#: The HUD face's box: 10x6 in the strip's field rows, clear of the bars
#: (columns 4..28) and the armor block (50..58).
FACE_W, FACE_H, FACE_ROW, FACE_COL = 10, 6, 41, 33
#: The face-core crop (top, bottom, left, right fractions): a 24x29 portrait
#: squashed whole into 6 rows smears eyes and mouth together, so the box keeps
#: the brow-to-chin band (montage-eyeballed on both art sources).
FACE_CROP = (0.18, 0.05, 0.08, 0.08)


def face_tables(faces: dict[str, list[list[tuple[int, int, int, int]]]],
                *, brightness: float = 1.4) -> dict[str, list[tuple[int, int, str]]]:
    """``{state: runs}`` for the status-bar face: each source cropped to the
    face core, composited onto the HUD field gray (colour 8) and block-Lab
    quantized to the face box — one opaque run per row (the CPU paints them
    as CURS + RUN words, so there is no arm budget to honour)."""
    out = {}
    t, b, lft, rgt = FACE_CROP
    for name, rgba in faces.items():
        src = _crop_alpha(rgba)
        h, w = len(src), len(src[0])
        src = [row[int(w * lft):w - int(w * rgt)]
               for row in src[int(h * t):h - int(h * b)]]
        grid = quantize_sprite(src, FACE_W, FACE_H,
                               background=PALETTE[8], brightness=brightness)
        out[name] = [(FACE_ROW + r, FACE_COL, "".join("%x" % c for c in grid[r]))
                     for r in range(FACE_H)]
    return out


#: Which IWAD lumps feed the --wad art overrides: the pistol pair and the
#: status-bar face family (centre gaze per pain band; EVL is the fire grimace).
IWAD_ART_LUMPS = {
    "gun_idle": "PISGA0", "gun_flash": "PISFA0",
    "face_healthy": "STFST01", "face_hurt": "STFST21",
    "face_bloody": "STFST41", "face_grim": "STFEVL0",
    "mon0": "POSSA1", "mon1": "TROOA1", "corpse": "POSSL0",
}


def iwad_art(path: Path) -> dict:
    """The --wad art override bundle: WAD-derived pistol + face run tables
    (M5: the local machines' GUN/GUNF arms and FACE paint carry the user's
    own art; nothing from this path may be committed)."""
    wad = read_wad(path)
    playpal = wad.lump("PLAYPAL")[:768]

    def pic(key: str):
        return decode_picture(wad.lump(IWAD_ART_LUMPS[key]), playpal)

    gun_idle, gun_fire = gun_tables(pic("gun_idle"), pic("gun_flash"))
    faces = face_tables({
        "healthy": pic("face_healthy"), "hurt": pic("face_hurt"),
        "bloody": pic("face_bloody"), "grim": pic("face_grim"),
    })
    sprites = monster_sprite_words(pic("mon0"), pic("mon1"), pic("corpse"))
    return {"gun_idle": gun_idle, "gun_fire": gun_fire, "faces": faces,
            "monster_sprites": sprites}


# ── the Level bundle ─────────────────────────────────────────────────────────
@dataclass
class Level:
    """Everything deadman3d needs, plus the eyeball/report extras."""

    map_rows: list[str]                     # 64 printed rows, north at the top
    spawn: tuple[int, int]                  # open cell
    heading: int                            # 0..15
    title_rows: list[str]                   # 48 rows of 64 hex digits
    families: dict[str, int]                # texture name -> wall family
    #: 64 printed rows, same orientation as ``map_rows``: ``N`` = an open cell
    #: on a damage floor, ``.`` = anything else (M5's nukage bit plane).
    nukage_rows: list[str] = field(default_factory=list)
    #: ``[cx, cy, species]`` per kept monster (M7; see ``_monster_things``).
    monsters: list[list[int]] = field(default_factory=list)
    avg_colours: dict[str, tuple[int, int, int]] = field(default_factory=dict)
    stats: dict = field(default_factory=dict)

    def map_str(self) -> str:
        return "\n".join(self.map_rows) + "\n"

    def family_table(self) -> str:
        lines = ["texture -> wall family (average RGB; family = ANSI hue, "
                 f"gray under CIELAB chroma {CHROMA_GATE:g})"]
        for name in sorted(self.families):
            avg = self.avg_colours.get(name)
            if avg is None:
                a = "  (void fill)"
            else:
                a = f" ({avg[0]:3d},{avg[1]:3d},{avg[2]:3d})"
            lines.append(f"  {name:<8s} -> {self.families[name]}{a}")
        return "\n".join(lines)


def _finish_level(raster: Raster, avg: dict[str, tuple[int, int, int] | None],
                  title_rows: list[str], source: str) -> Level:
    families = {name: family_of(avg.get(name)) for name in
                sorted({t for t in raster.cells.values() if t != "#VOID"})}
    families["#VOID"] = 7
    grid = raster.grid
    rows = []
    nrows = []
    for p in range(grid):
        y = grid - 1 - p
        row = ""
        nrow = ""
        for x in range(grid):
            tex = raster.cells.get((x, y))
            row += "." if tex is None else f"{families[tex]:x}"
            nrow += "N" if tex is None and (x, y) in raster.nukage else "."
        rows.append(row)
        nrows.append(nrow)
    wall_cells = sum(1 for t in raster.cells.values() if t != "#VOID")
    used = sorted(set(families[t] for t in families if t != "#VOID"))
    stats = {
        "source": source,
        "bbox": raster.bbox,
        "grid": grid,
        "wall_cells": wall_cells,
        "open_cells": len(raster.open_cells),
        "void_filled": raster.void_filled,
        "textures": len(families) - 1,
        "families_used": used,
        "title_runs": _run_count(title_rows),
        **{f"nukage_{k}" if not k.startswith("nukage") else k: v
           for k, v in raster.nukage_stats.items()},
        **raster.monster_stats,
    }
    return Level(rows, raster.spawn, raster.heading, title_rows,
                 families, nrows,
                 [list(mon) for mon in raster.monsters],
                 {k: tuple(round(c) for c in v) for k, v in avg.items()
                  if v is not None}, stats)


def _run_count(rows: list[str]) -> int:
    flat = "".join(rows)
    return 1 + sum(1 for a, b in zip(flat, flat[1:], strict=False) if a != b) if flat else 0


# ── Freedoom mode ────────────────────────────────────────────────────────────
def _parse_textures_cfg(text: str) -> dict[str, list[str]]:
    """``textures.cfg`` -> {texture: [patch, ...]} (offsets not needed for an
    average; simplecpp #directives are ignored, so every branch contributes)."""
    texs: dict[str, list[str]] = {}
    cur: str | None = None
    for line in text.splitlines():
        line = line.split(";")[0].rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split()
        if line[0] not in " \t*" and len(parts) == 3:
            cur = parts[0]
            texs.setdefault(cur, [])
        elif parts[0] == "*" and cur and len(parts) >= 4:
            texs[cur].append(parts[1])
    return texs


def _png_avg(rgba: list[list[tuple[int, int, int, int]]]) -> tuple[float, float, float] | None:
    rs = gs = bs = n = 0
    for row in rgba:
        for r, g, b, a in row:
            if a > 128:
                rs += r
                gs += g
                bs += b
                n += 1
    return (rs / n, gs / n, bs / n) if n else None


def load_freedoom(root: Path, mapname: str = "E1M1", grid: int = 64,
                  min_len: float = 32.0) -> Level:
    """Import from a Freedoom checkout: levels/<map>.wad + textures.cfg +
    patches/*.png + graphics/titlepic/titlepic.png."""
    wad = read_wad(root / "levels" / f"{mapname.lower()}.wad")
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    texs = _parse_textures_cfg(
        (root / "lumps" / "textures" / "textures.cfg").read_text(encoding="utf-8"))
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            path = root / "patches" / f"{patch.lower()}.png"
            if not path.exists():
                continue
            one = _png_avg(decode_png(path.read_bytes()))
            if one:
                # weight patches equally; exact per-pixel compositing is not
                # needed for a family decision
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_png(
        (root / "graphics" / "titlepic" / "titlepic.png").read_bytes()))
    return _finish_level(raster, avg, title, f"freedoom:{mapname}")


# ── IWAD mode ────────────────────────────────────────────────────────────────
def _iwad_textures(wad: Wad) -> dict[str, list[str]]:
    """TEXTURE1/TEXTURE2 + PNAMES -> {texture: [patch lump name, ...]}."""
    pn = wad.lump("PNAMES")
    (n_p,), names = struct.unpack("<I", pn[:4]), []
    for i in range(n_p):
        names.append(_cstr(pn[4 + 8 * i:12 + 8 * i]).upper())
    texs: dict[str, list[str]] = {}
    for lumpname in ("TEXTURE1", "TEXTURE2"):
        if lumpname not in wad:
            continue
        data = wad.lump(lumpname)
        (count,) = struct.unpack("<I", data[:4])
        offsets = struct.unpack(f"<{count}I", data[4:4 + 4 * count])
        for off in offsets:
            tname = _cstr(data[off:off + 8])
            (npatch,) = struct.unpack("<H", data[off + 20:off + 22])
            patches = []
            for k in range(npatch):
                p = off + 22 + 10 * k
                (_ox, _oy, pidx) = struct.unpack("<hhH", data[p:p + 6])
                if pidx < len(names):
                    patches.append(names[pidx])
            texs[tname] = patches
    return texs


def load_iwad(path: Path, mapname: str = "E1M1", grid: int = 64,
              min_len: float = 32.0) -> Level:
    """Import from a retail-format IWAD (everything from inside the WAD)."""
    wad = read_wad(path)
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    playpal = wad.lump("PLAYPAL")[:768]
    texs = _iwad_textures(wad)
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            if patch not in wad:
                continue
            one = _png_avg(decode_picture(wad.lump(patch), playpal))
            if one:
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_picture(wad.lump("TITLEPIC"), playpal))
    return _finish_level(raster, avg, title, f"iwad:{path.name}:{mapname}")


# ── output ───────────────────────────────────────────────────────────────────
def _png_bytes(pixels: list[list[tuple[int, int, int]]], scale: int = 8) -> bytes:
    """A minimal RGB PNG writer (same shape as deadman3d's fallback)."""
    h, w = len(pixels), len(pixels[0])
    raw = bytearray()
    for y in range(h):
        for _ in range(scale):
            raw.append(0)
            for x in range(w):
                raw.extend(bytes(pixels[y][x]) * scale)

    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body)))

    ihdr = struct.pack(">IIBBBBB", w * scale, h * scale, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw))) + chunk(b"IEND", b""))


def emit(level: Level, out_dir: Path) -> None:
    """Write the bundle: level.json + map.txt/title.txt/families.txt + the two
    eyeball PNGs (overhead + title)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "level.json").write_text(json.dumps({
        "map_rows": level.map_rows,
        "spawn": list(level.spawn),
        "heading": level.heading,
        "title_rows": level.title_rows,
        "families": level.families,
        "nukage_rows": level.nukage_rows,
        "monsters": level.monsters,
        "stats": level.stats,
    }, indent=1) + "\n", encoding="utf-8")
    (out_dir / "map.txt").write_text(level.map_str(), encoding="utf-8")
    if level.nukage_rows:
        (out_dir / "nukage.txt").write_text(
            "\n".join(level.nukage_rows) + "\n", encoding="utf-8")
    (out_dir / "title.txt").write_text("\n".join(level.title_rows) + "\n", encoding="utf-8")
    (out_dir / "families.txt").write_text(level.family_table() + "\n", encoding="utf-8")
    grid = len(level.map_rows)
    mon_cells = {(mx, my) for mx, my, _sp in level.monsters}
    overhead = []
    for p in range(grid):
        row = []
        for x in range(grid):
            y = grid - 1 - p
            ch = level.map_rows[p][x]
            if (x, y) == level.spawn:
                row.append((255, 255, 0))
            elif (x, y) in mon_cells:
                row.append((255, 0, 0))
            elif ch == ".":
                nuk = level.nukage_rows and level.nukage_rows[p][x] == "N"
                row.append((0, 130, 0) if nuk else (40, 40, 40))
            else:
                row.append(PALETTE[int(ch, 16)])
        overhead.append(row)
    (out_dir / "overhead.png").write_bytes(_png_bytes(overhead))
    title = [[PALETTE[int(c, 16)] for c in row] for row in level.title_rows]
    (out_dir / "title.png").write_bytes(_png_bytes(title))


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--freedoom", type=Path, metavar="DIR",
                     help="a Freedoom checkout/snapshot (pinned commit d14dbbe)")
    src.add_argument("--wad", type=Path, metavar="PATH",
                     help="a retail-format IWAD (local use only; do NOT commit outputs)")
    parser.add_argument("--map", default="E1M1", help="map marker lump (default E1M1)")
    parser.add_argument("--grid", type=int, default=64,
                        help="grid size (default 64; the demo's map word packing"
                             " supports future 128)")
    parser.add_argument("--min-len", type=float, default=32.0,
                        help="ignore one-sided linedefs shorter than this many map units")
    parser.add_argument("--out", type=Path, required=True, help="output directory")
    args = parser.parse_args(argv)
    if args.freedoom:
        level = load_freedoom(args.freedoom, args.map, args.grid, args.min_len)
    else:
        level = load_iwad(args.wad, args.map, args.grid, args.min_len)
    emit(level, args.out)
    print(json.dumps(level.stats))
    print(level.family_table())
    print(f"spawn {level.spawn} heading {level.heading}")
    print(f"wrote {args.out}/level.json (+ map/title/families/overhead/title.png)")


if __name__ == "__main__":
    main()
