#!/usr/bin/env python3
"""WAD level importer for deadman-3d: real DOOM-format geometry -> the 64x64 grid.

Two sources, one pipeline (see ``deadman3d.py`` for the consumer):

* **Freedoom mode** (``--freedoom DIR``): a checkout/snapshot of
  https://github.com/freedoom/freedoom (pinned commit ``d14dbbe``).  The level
  is ``levels/<map>.wad`` (a PWAD of just the map lumps), wall textures are
  composited from ``lumps/textures/textures.cfg`` + ``patches/*.png``, and the
  title screen is ``graphics/titlepic/titlepic.png``.  Freedoom content is
  BSD-licensed (COPYING.adoc) — the committed deadman-3d map, wall families
  and title screen are generated by this mode.

* **IWAD mode** (``--wad PATH``): a retail-format IWAD (e.g. a DOOM shareware
  ``DOOM1.WAD``).  Everything comes from inside the WAD: map lumps,
  ``TEXTURE1``/``TEXTURE2`` + ``PNAMES`` + patch lumps (DOOM picture format)
  + ``PLAYPAL`` for wall colours, ``TITLEPIC`` for the title.  **Nothing
  derived from a retail IWAD may be committed** — outputs belong in a
  git-ignored directory (``littleman/examples/local/``).

The pipeline:

1. Parse the WAD directory (12-byte header, 16-byte directory entries) and the
   fixed-size little-endian map lumps: VERTEXES (4 bytes: x, y), LINEDEFS
   (14 bytes), SIDEDEFS (30 bytes), THINGS (10 bytes).
2. Rasterize: the level bbox is fitted (uniform scale, centred, one-cell
   border) onto a ``grid``x``grid`` map.  Every **one-sided** linedef at least
   ``min_len`` map units long becomes wall cells via an exact supercover
   traversal; two-sided linedefs (room-to-room joins, doorways) and shorter
   detail lines are ignored.  Each wall cell inherits its dominant linedef's
   sidedef texture (weighted by linedef length).
3. Close the map: the player start (THINGS type 1, bumped to the nearest open
   cell if its own cell caught a wall) seeds a 4-connected flood fill; the
   reachable region must not touch the grid border (watertightness — a
   supercover of the level's closed one-sided perimeter cannot be crossed),
   and every unreachable cell is filled solid, so the committed map has no
   void a ray could escape into.
4. Colour: each texture name that occurs on a wall cell maps to a wall family
   1..7 — the ANSI palette index of its average colour (patches composited,
   alpha-weighted).  Because most DOOM-era textures are desaturated, the
   family is chosen by *hue* (CIELAB, families 1..6) with a chroma gate below
   which the texture is gray (family 7); ties collapse identical-hue textures
   into one family, which is the <=7-group clustering.
5. Title: the 320x200 title art (PNG or TITLEPIC picture lump) is quantized to
   64x48 with the repo's block-Lab method — per target block, the ANSI-16
   colour minimizing the sum of CIELAB distances over the source block's
   pixels — after a fixed x1.6 brightness lift (DOOM-era title art is dark;
   measured on both sources), then a single isolated-dot despeckle pass.

The output bundle (``--out DIR``) is ``level.json`` (map rows, spawn, heading,
title rows, the texture->family table) plus eyeball artifacts: ``map.txt``,
``title.txt``, ``overhead.png``, ``title.png``, ``families.txt``.

Stdlib only (struct + zlib carry the PNG codec) so the fast tests can cover
the parser on a synthetic in-memory WAD.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
import zlib
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path

__all__ = [
    "PALETTE", "Wad", "MapData", "Level",
    "read_wad", "parse_map", "supercover", "rasterize",
    "decode_png", "decode_picture", "srgb_to_lab", "family_of",
    "quantize_title", "despeckle",
    "load_freedoom", "load_iwad", "emit", "main",
]

#: The LM-75 ANSI-16 palette (== deadman3d.PALETTE; kept local so the importer
#: never imports the consumer).
PALETTE = [
    (0, 0, 0), (170, 0, 0), (0, 170, 0), (170, 85, 0),
    (0, 0, 170), (170, 0, 170), (0, 170, 170), (170, 170, 170),
    (85, 85, 85), (255, 85, 85), (85, 255, 85), (255, 255, 85),
    (85, 85, 255), (255, 85, 255), (85, 255, 255), (255, 255, 255),
]

NO_SIDE = 0xFFFF  # a linedef with no left sidedef is one-sided (solid)


# ── WAD parsing ──────────────────────────────────────────────────────────────
@dataclass
class Wad:
    """A parsed WAD: the ordered lump directory."""

    ident: str
    lumps: list[tuple[str, bytes]]

    def lump(self, name: str) -> bytes:
        for n, data in self.lumps:
            if n == name:
                return data
        raise KeyError(f"no lump {name!r} in this {self.ident}")

    def __contains__(self, name: str) -> bool:
        return any(n == name for n, _ in self.lumps)


@dataclass
class MapData:
    """One map's fixed-size-record lumps, decoded."""

    vertexes: list[tuple[int, int]]
    #: (v1, v2, flags, special, tag, right_sidedef, left_sidedef)
    linedefs: list[tuple[int, int, int, int, int, int, int]]
    #: (upper, lower, middle, sector)
    sidedefs: list[tuple[str, str, str, int]]
    #: (x, y, angle, type, flags)
    things: list[tuple[int, int, int, int, int]]


def read_wad(data: bytes | Path) -> Wad:
    """Parse an IWAD/PWAD: 12-byte header, then 16-byte directory entries."""
    if isinstance(data, Path):
        data = data.read_bytes()
    ident, count, dir_off = struct.unpack("<4sII", data[:12])
    ident = ident.decode("ascii")
    if ident not in ("IWAD", "PWAD"):
        raise ValueError(f"not a WAD: magic {ident!r}")
    lumps = []
    for i in range(count):
        off, size, raw = struct.unpack("<II8s", data[dir_off + 16 * i:dir_off + 16 * i + 16])
        name = raw.rstrip(b"\0").decode("ascii", "replace")
        lumps.append((name, data[off:off + size]))
    return Wad(ident, lumps)


def _cstr(raw: bytes) -> str:
    return raw.rstrip(b"\0").decode("ascii", "replace")


def parse_map(wad: Wad, mapname: str) -> MapData:
    """The named map's THINGS/LINEDEFS/SIDEDEFS/VERTEXES, from the lumps that
    follow its marker (the marker lump itself is empty)."""
    names = [n for n, _ in wad.lumps]
    try:
        at = names.index(mapname)
    except ValueError:
        raise KeyError(f"no map {mapname!r}; lumps: {names[:8]}...") from None
    section = {n: d for n, d in wad.lumps[at + 1:at + 11]}
    need = ("THINGS", "LINEDEFS", "SIDEDEFS", "VERTEXES")
    missing = [n for n in need if n not in section]
    if missing:
        raise ValueError(f"map {mapname} is missing lumps {missing}")
    vertexes = [struct.unpack("<hh", d) for d in _records(section["VERTEXES"], 4)]
    linedefs = [struct.unpack("<HHHHHHH", d) for d in _records(section["LINEDEFS"], 14)]
    sidedefs = []
    for d in _records(section["SIDEDEFS"], 30):
        _xo, _yo, up, lo, mid, sector = struct.unpack("<hh8s8s8sH", d)
        sidedefs.append((_cstr(up), _cstr(lo), _cstr(mid), sector))
    things = [struct.unpack("<hhHHH", d) for d in _records(section["THINGS"], 10)]
    return MapData(vertexes, linedefs, sidedefs, things)


def _records(data: bytes, size: int):
    return (data[i:i + size] for i in range(0, len(data) - size + 1, size))


# ── rasterization ────────────────────────────────────────────────────────────
def supercover(x0: float, y0: float, x1: float, y1: float) -> set[tuple[int, int]]:
    """Every grid cell the segment touches (Amanatides–Woo traversal; a
    crossing within eps of a cell corner adds both side cells, so a
    4-connected path of empty cells can never slip across the segment)."""
    eps = 1e-9
    cells: set[tuple[int, int]] = set()
    x, y = math.floor(x0), math.floor(y0)
    xe, ye = math.floor(x1), math.floor(y1)
    dx, dy = x1 - x0, y1 - y0
    step_x = 1 if dx > 0 else -1
    step_y = 1 if dy > 0 else -1
    # t at which the ray crosses the next vertical / horizontal grid line
    t_max_x = ((x + (step_x > 0)) - x0) / dx if dx else math.inf
    t_max_y = ((y + (step_y > 0)) - y0) / dy if dy else math.inf
    t_dx = abs(1 / dx) if dx else math.inf
    t_dy = abs(1 / dy) if dy else math.inf
    cells.add((x, y))
    guard = 4 * (abs(xe - x) + abs(ye - y)) + 8
    while (x, y) != (xe, ye) and guard:
        guard -= 1
        if abs(t_max_x - t_max_y) < eps:  # corner crossing: cover both cells
            cells.add((x + step_x, y))
            cells.add((x, y + step_y))
            x += step_x
            y += step_y
            t_max_x += t_dx
            t_max_y += t_dy
        elif t_max_x < t_max_y:
            x += step_x
            t_max_x += t_dx
        else:
            y += step_y
            t_max_y += t_dy
        cells.add((x, y))
    # A segment lying exactly ON a grid line borders both flanking cells
    # (e.g. an axis-aligned wall at an integral coordinate): cover both.
    if dx == 0 and abs(x0 - round(x0)) < eps:
        cells |= {(cx - 1, cy) for cx, cy in cells}
    if dy == 0 and abs(y0 - round(y0)) < eps:
        cells |= {(cx, cy - 1) for cx, cy in cells}
    return cells


@dataclass
class Raster:
    """The rasterized level, before colours."""

    grid: int
    cells: dict[tuple[int, int], str]        # wall cell -> dominant texture
    open_cells: set[tuple[int, int]]         # reachable from the spawn
    spawn: tuple[int, int]
    heading: int                             # 0..15, CCW from east
    bbox: tuple[int, int, int, int]          # minx, miny, maxx, maxy
    void_filled: int = 0


def rasterize(m: MapData, grid: int = 64, min_len: float = 32.0) -> Raster:
    """Project the level onto ``grid`` x ``grid`` (uniform scale, centred, one
    border cell), supercover the long one-sided linedefs, close the map.

    Asserts, in order: a player-1 start exists; the spawn cell is open (bumped
    <=2 cells if the exact cell caught a wall); the flood fill from the spawn
    never reaches the grid border (watertight).  Unreachable cells are then
    filled solid, so the result has no void at all.
    """
    xs = [v[0] for v in m.vertexes]
    ys = [v[1] for v in m.vertexes]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    w, h = maxx - minx, maxy - miny
    scale = (grid - 2) / max(w, h)
    offx = 1 + ((grid - 2) - w * scale) / 2
    offy = 1 + ((grid - 2) - h * scale) / 2

    def to_grid(x: float, y: float) -> tuple[float, float]:
        return (x - minx) * scale + offx, (y - miny) * scale + offy

    weight: dict[tuple[int, int], Counter] = defaultdict(Counter)
    for v1, v2, _flags, _special, _tag, right, left in m.linedefs:
        if left != NO_SIDE or right == NO_SIDE:
            continue  # two-sided (or degenerate): not a solid wall
        ax, ay = m.vertexes[v1]
        bx, by = m.vertexes[v2]
        length = math.hypot(bx - ax, by - ay)
        if length < min_len:
            continue  # detail geometry
        up, lo, mid, _sector = m.sidedefs[right]
        tex = mid if mid and mid != "-" else (up if up and up != "-" else lo)
        if not tex or tex == "-":
            continue
        for c in supercover(*to_grid(ax, ay), *to_grid(bx, by)):
            if 0 <= c[0] < grid and 0 <= c[1] < grid:
                weight[c][tex] += length
    cells = {c: cnt.most_common(1)[0][0] for c, cnt in weight.items()}

    starts = [t for t in m.things if t[3] == 1]
    assert starts, "no player-1 start (THINGS type 1)"
    sx, sy, angle = starts[0][0], starts[0][1], starts[0][2]
    gx, gy = to_grid(sx, sy)
    spawn = (int(gx), int(gy))
    heading = round(angle / 22.5) % 16
    if spawn in cells:  # the start hugged a wall closer than one cell
        near = [(abs(dx) + abs(dy), (spawn[0] + dx, spawn[1] + dy))
                for dx in range(-2, 3) for dy in range(-2, 3)
                if (spawn[0] + dx, spawn[1] + dy) not in cells]
        assert near, f"no open cell within 2 of the spawn {spawn}"
        spawn = min(near)[1]
    assert 0 < spawn[0] < grid - 1 and 0 < spawn[1] < grid - 1, \
        f"spawn {spawn} out of the map interior"

    open_cells = {spawn}
    queue = deque([spawn])
    while queue:
        x, y = queue.popleft()
        for nxt in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nxt[0] < grid and 0 <= nxt[1] < grid \
                    and nxt not in cells and nxt not in open_cells:
                open_cells.add(nxt)
                queue.append(nxt)
    leaks = [c for c in open_cells if c[0] in (0, grid - 1) or c[1] in (0, grid - 1)]
    assert not leaks, f"map leaks into the void at {sorted(leaks)[:8]}"

    void = 0
    for x in range(grid):
        for y in range(grid):
            if (x, y) not in cells and (x, y) not in open_cells:
                cells[(x, y)] = "#VOID"
                void += 1
    return Raster(grid, cells, open_cells, spawn, heading,
                  (minx, miny, maxx, maxy), void)


# ── colours ──────────────────────────────────────────────────────────────────
def srgb_to_lab(rgb: tuple[float, float, float]) -> tuple[float, float, float]:
    """CIELAB (D65) — the same conversion the title/gun quantization used."""
    def lin(c: float) -> float:
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (lin(c) for c in rgb)
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883

    def f(t: float) -> float:
        return t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116

    fx, fy, fz = f(x), f(y), f(z)
    return 116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)


_LAB = [srgb_to_lab(p) for p in PALETTE]
_HUES = {i: math.atan2(_LAB[i][2], _LAB[i][1]) for i in range(1, 7)}
#: Below this CIELAB chroma a texture is just gray (family 7).  DOOM-era
#: metals/concretes sit around 4..8; bricks and screens well above 10.
CHROMA_GATE = 10.0


def family_of(avg: tuple[float, float, float] | None) -> int:
    """Wall family 1..7 for a texture's average colour: gray under the chroma
    gate, else the hue-nearest of the six chromatic ANSI colours."""
    if avg is None:
        return 7
    _l, a, b = srgb_to_lab(avg)
    if math.hypot(a, b) < CHROMA_GATE:
        return 7
    hue = math.atan2(b, a)

    def dist(i: int) -> float:
        d = abs(hue - _HUES[i])
        return min(d, 2 * math.pi - d)

    return min(range(1, 7), key=dist)


# ── PNG decode (stdlib; the subset Freedoom's assets use) ────────────────────
def decode_png(data: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a non-interlaced PNG (bit depth 1/2/4/8; colour types
    0 gray, 2 RGB, 3 palette, 4 gray+alpha, 6 RGBA; tRNS honoured)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    w = h = bitd = ctype = 0
    plte: list[tuple[int, int, int]] = []
    trns = b""
    idat = b""
    at = 8
    while at < len(data):
        (ln,), tag = struct.unpack(">I", data[at:at + 4]), data[at + 4:at + 8]
        body = data[at + 8:at + 8 + ln]
        at += 12 + ln
        if tag == b"IHDR":
            w, h, bitd, ctype, comp, filt, inter = struct.unpack(">IIBBBBB", body)
            if inter:
                raise ValueError("interlaced PNG unsupported")
            if comp or filt:
                raise ValueError("nonstandard PNG compression/filter")
        elif tag == b"PLTE":
            plte = [tuple(body[i:i + 3]) for i in range(0, len(body), 3)]
        elif tag == b"tRNS":
            trns = body
        elif tag == b"IDAT":
            idat += body
        elif tag == b"IEND":
            break
    raw = zlib.decompress(idat)
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bpp = max(1, channels * bitd // 8)
    stride = (w * channels * bitd + 7) // 8
    rows: list[bytearray] = []
    prev = bytearray(stride)
    for yy in range(h):
        f = raw[yy * (stride + 1)]
        line = bytearray(raw[yy * (stride + 1) + 1:(yy + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1:
                line[i] = (line[i] + a) & 0xFF
            elif f == 2:
                line[i] = (line[i] + b) & 0xFF
            elif f == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        rows.append(line)
        prev = line

    def samples(line: bytearray):
        if bitd == 8:
            yield from line
        else:
            per = 8 // bitd
            mask = (1 << bitd) - 1
            for byte in line:
                for k in range(per):
                    yield (byte >> (8 - bitd * (k + 1))) & mask

    out = []
    scale = 255 // ((1 << bitd) - 1) if ctype != 3 else 1
    for line in rows:
        vals = list(samples(line))
        row = []
        for xx in range(w):
            v = vals[xx * channels:(xx + 1) * channels]
            if ctype == 3:
                r, g, b = plte[v[0]]
                a = trns[v[0]] if v[0] < len(trns) else 255
                row.append((r, g, b, a))
            elif ctype == 0:
                g = v[0] * scale
                row.append((g, g, g, 255))
            elif ctype == 4:
                g = v[0] * scale
                row.append((g, g, g, v[1] * scale))
            elif ctype == 2:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, 255))
            else:
                row.append((v[0] * scale, v[1] * scale, v[2] * scale, v[3] * scale))
        out.append(row)
    return out


# ── DOOM picture format (IWAD patches, TITLEPIC) ─────────────────────────────
def decode_picture(data: bytes, playpal: bytes) -> list[list[tuple[int, int, int, int]]]:
    """RGBA rows for a DOOM picture lump: a header of column offsets, each
    column a run of posts (top-delta, length, pad, pixels..., pad), 0xFF ends."""
    w, h, _lo, _to = struct.unpack("<HHhh", data[:8])
    cols = struct.unpack(f"<{w}I", data[8:8 + 4 * w])
    rows = [[(0, 0, 0, 0)] * w for _ in range(h)]
    for x, off in enumerate(cols):
        at = off
        while data[at] != 0xFF:
            top, ln = data[at], data[at + 1]
            for k in range(ln):
                idx = data[at + 3 + k]
                y = top + k
                if y < h:
                    r, g, b = playpal[3 * idx:3 * idx + 3]
                    rows[y][x] = (r, g, b, 255)
            at += 4 + ln
    return rows


# ── the title screen ─────────────────────────────────────────────────────────
#: DOOM-era title art is dark; a fixed linear brightness lift keeps the marine
#: (and the shareware IWAD's title) out of the black/dark-gray sump when the
#: 16-colour palette quantizes it.  Chosen by eyeballing 1.0/1.4/1.6/1.8 on
#: both title sources.
TITLE_BRIGHTNESS = 1.6


def quantize_title(rgba: list[list[tuple[int, int, int, int]]],
                   tw: int = 64, th: int = 48,
                   brightness: float = TITLE_BRIGHTNESS) -> list[str]:
    """The repo's block-Lab method at ``tw`` x ``th``: per target block pick
    the ANSI-16 colour minimizing the summed CIELAB distance over the source
    block's (brightness-lifted) pixels; then one despeckle pass."""
    hh, ww = len(rgba), len(rgba[0])
    cache: dict[tuple[int, int, int], list[float]] = {}

    def dists(px: tuple[int, int, int, int]) -> list[float]:
        rgb = tuple(min(255, round(c * brightness)) for c in px[:3])
        if rgb not in cache:
            lab = srgb_to_lab(rgb)
            cache[rgb] = [math.dist(lab, palette_lab) for palette_lab in _LAB]
        return cache[rgb]

    grid = []
    for ty in range(th):
        y0, y1 = int(ty * hh / th), max(int(ty * hh / th) + 1, int((ty + 1) * hh / th))
        row = []
        for tx in range(tw):
            x0, x1 = int(tx * ww / tw), max(int(tx * ww / tw) + 1, int((tx + 1) * ww / tw))
            acc = [0.0] * 16
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    d = dists(rgba[yy][xx])
                    for i in range(16):
                        acc[i] += d[i]
            row.append(min(range(16), key=acc.__getitem__))
        grid.append(row)
    grid = despeckle(grid)
    return ["".join(f"{c:x}" for c in row) for row in grid]


def despeckle(grid: list[list[int]]) -> list[list[int]]:
    """A pixel whose 4-neighbours all agree on another colour joins them."""
    h, w = len(grid), len(grid[0])
    out = [row[:] for row in grid]
    for y in range(h):
        for x in range(w):
            nb = [grid[y + dy][x + dx]
                  for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                  if 0 <= x + dx < w and 0 <= y + dy < h]
            if len(nb) == 4 and len(set(nb)) == 1 and nb[0] != grid[y][x]:
                out[y][x] = nb[0]
    return out


# ── the Level bundle ─────────────────────────────────────────────────────────
@dataclass
class Level:
    """Everything deadman3d needs, plus the eyeball/report extras."""

    map_rows: list[str]                     # 64 printed rows, north at the top
    spawn: tuple[int, int]                  # open cell
    heading: int                            # 0..15
    title_rows: list[str]                   # 48 rows of 64 hex digits
    families: dict[str, int]                # texture name -> wall family
    avg_colours: dict[str, tuple[int, int, int]] = field(default_factory=dict)
    stats: dict = field(default_factory=dict)

    def map_str(self) -> str:
        return "\n".join(self.map_rows) + "\n"

    def family_table(self) -> str:
        lines = ["texture -> wall family (average RGB; family = ANSI hue, "
                 f"gray under CIELAB chroma {CHROMA_GATE:g})"]
        for name in sorted(self.families):
            avg = self.avg_colours.get(name)
            if avg is None:
                a = "  (void fill)"
            else:
                a = f" ({avg[0]:3d},{avg[1]:3d},{avg[2]:3d})"
            lines.append(f"  {name:<8s} -> {self.families[name]}{a}")
        return "\n".join(lines)


def _finish_level(raster: Raster, avg: dict[str, tuple[int, int, int] | None],
                  title_rows: list[str], source: str) -> Level:
    families = {name: family_of(avg.get(name)) for name in
                sorted({t for t in raster.cells.values() if t != "#VOID"})}
    families["#VOID"] = 7
    grid = raster.grid
    rows = []
    for p in range(grid):
        y = grid - 1 - p
        row = ""
        for x in range(grid):
            tex = raster.cells.get((x, y))
            row += "." if tex is None else f"{families[tex]:x}"
        rows.append(row)
    wall_cells = sum(1 for t in raster.cells.values() if t != "#VOID")
    used = sorted(set(families[t] for t in families if t != "#VOID"))
    stats = {
        "source": source,
        "bbox": raster.bbox,
        "grid": grid,
        "wall_cells": wall_cells,
        "open_cells": len(raster.open_cells),
        "void_filled": raster.void_filled,
        "textures": len(families) - 1,
        "families_used": used,
        "title_runs": _run_count(title_rows),
    }
    return Level(rows, raster.spawn, raster.heading, title_rows,
                 families, {k: tuple(round(c) for c in v) for k, v in avg.items()
                            if v is not None}, stats)


def _run_count(rows: list[str]) -> int:
    flat = "".join(rows)
    return 1 + sum(1 for a, b in zip(flat, flat[1:], strict=False) if a != b) if flat else 0


# ── Freedoom mode ────────────────────────────────────────────────────────────
def _parse_textures_cfg(text: str) -> dict[str, list[str]]:
    """``textures.cfg`` -> {texture: [patch, ...]} (offsets not needed for an
    average; simplecpp #directives are ignored, so every branch contributes)."""
    texs: dict[str, list[str]] = {}
    cur: str | None = None
    for line in text.splitlines():
        line = line.split(";")[0].rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split()
        if line[0] not in " \t*" and len(parts) == 3:
            cur = parts[0]
            texs.setdefault(cur, [])
        elif parts[0] == "*" and cur and len(parts) >= 4:
            texs[cur].append(parts[1])
    return texs


def _png_avg(rgba: list[list[tuple[int, int, int, int]]]) -> tuple[float, float, float] | None:
    rs = gs = bs = n = 0
    for row in rgba:
        for r, g, b, a in row:
            if a > 128:
                rs += r
                gs += g
                bs += b
                n += 1
    return (rs / n, gs / n, bs / n) if n else None


def load_freedoom(root: Path, mapname: str = "E1M1", grid: int = 64,
                  min_len: float = 32.0) -> Level:
    """Import from a Freedoom checkout: levels/<map>.wad + textures.cfg +
    patches/*.png + graphics/titlepic/titlepic.png."""
    wad = read_wad(root / "levels" / f"{mapname.lower()}.wad")
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    texs = _parse_textures_cfg(
        (root / "lumps" / "textures" / "textures.cfg").read_text(encoding="utf-8"))
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            path = root / "patches" / f"{patch.lower()}.png"
            if not path.exists():
                continue
            one = _png_avg(decode_png(path.read_bytes()))
            if one:
                # weight patches equally; exact per-pixel compositing is not
                # needed for a family decision
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_png(
        (root / "graphics" / "titlepic" / "titlepic.png").read_bytes()))
    return _finish_level(raster, avg, title, f"freedoom:{mapname}")


# ── IWAD mode ────────────────────────────────────────────────────────────────
def _iwad_textures(wad: Wad) -> dict[str, list[str]]:
    """TEXTURE1/TEXTURE2 + PNAMES -> {texture: [patch lump name, ...]}."""
    pn = wad.lump("PNAMES")
    (n_p,), names = struct.unpack("<I", pn[:4]), []
    for i in range(n_p):
        names.append(_cstr(pn[4 + 8 * i:12 + 8 * i]).upper())
    texs: dict[str, list[str]] = {}
    for lumpname in ("TEXTURE1", "TEXTURE2"):
        if lumpname not in wad:
            continue
        data = wad.lump(lumpname)
        (count,) = struct.unpack("<I", data[:4])
        offsets = struct.unpack(f"<{count}I", data[4:4 + 4 * count])
        for off in offsets:
            tname = _cstr(data[off:off + 8])
            (npatch,) = struct.unpack("<H", data[off + 20:off + 22])
            patches = []
            for k in range(npatch):
                p = off + 22 + 10 * k
                (_ox, _oy, pidx) = struct.unpack("<hhH", data[p:p + 6])
                if pidx < len(names):
                    patches.append(names[pidx])
            texs[tname] = patches
    return texs


def load_iwad(path: Path, mapname: str = "E1M1", grid: int = 64,
              min_len: float = 32.0) -> Level:
    """Import from a retail-format IWAD (everything from inside the WAD)."""
    wad = read_wad(path)
    raster = rasterize(parse_map(wad, mapname), grid=grid, min_len=min_len)
    playpal = wad.lump("PLAYPAL")[:768]
    texs = _iwad_textures(wad)
    avg: dict[str, tuple[float, float, float] | None] = {}
    for name in {t for t in raster.cells.values() if t != "#VOID"}:
        acc = [0.0, 0.0, 0.0]
        n = 0
        for patch in texs.get(name, ()):
            if patch not in wad:
                continue
            one = _png_avg(decode_picture(wad.lump(patch), playpal))
            if one:
                for i in range(3):
                    acc[i] += one[i]
                n += 1
        avg[name] = tuple(c / n for c in acc) if n else None
    title = quantize_title(decode_picture(wad.lump("TITLEPIC"), playpal))
    return _finish_level(raster, avg, title, f"iwad:{path.name}:{mapname}")


# ── output ───────────────────────────────────────────────────────────────────
def _png_bytes(pixels: list[list[tuple[int, int, int]]], scale: int = 8) -> bytes:
    """A minimal RGB PNG writer (same shape as deadman3d's fallback)."""
    h, w = len(pixels), len(pixels[0])
    raw = bytearray()
    for y in range(h):
        for _ in range(scale):
            raw.append(0)
            for x in range(w):
                raw.extend(bytes(pixels[y][x]) * scale)

    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body)))

    ihdr = struct.pack(">IIBBBBB", w * scale, h * scale, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw))) + chunk(b"IEND", b""))


def emit(level: Level, out_dir: Path) -> None:
    """Write the bundle: level.json + map.txt/title.txt/families.txt + the two
    eyeball PNGs (overhead + title)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "level.json").write_text(json.dumps({
        "map_rows": level.map_rows,
        "spawn": list(level.spawn),
        "heading": level.heading,
        "title_rows": level.title_rows,
        "families": level.families,
        "stats": level.stats,
    }, indent=1) + "\n", encoding="utf-8")
    (out_dir / "map.txt").write_text(level.map_str(), encoding="utf-8")
    (out_dir / "title.txt").write_text("\n".join(level.title_rows) + "\n", encoding="utf-8")
    (out_dir / "families.txt").write_text(level.family_table() + "\n", encoding="utf-8")
    grid = len(level.map_rows)
    overhead = []
    for p in range(grid):
        row = []
        for x in range(grid):
            y = grid - 1 - p
            ch = level.map_rows[p][x]
            if (x, y) == level.spawn:
                row.append((255, 255, 0))
            elif ch == ".":
                row.append((40, 40, 40))
            else:
                row.append(PALETTE[int(ch, 16)])
        overhead.append(row)
    (out_dir / "overhead.png").write_bytes(_png_bytes(overhead))
    title = [[PALETTE[int(c, 16)] for c in row] for row in level.title_rows]
    (out_dir / "title.png").write_bytes(_png_bytes(title))


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--freedoom", type=Path, metavar="DIR",
                     help="a Freedoom checkout/snapshot (pinned commit d14dbbe)")
    src.add_argument("--wad", type=Path, metavar="PATH",
                     help="a retail-format IWAD (local use only; do NOT commit outputs)")
    parser.add_argument("--map", default="E1M1", help="map marker lump (default E1M1)")
    parser.add_argument("--grid", type=int, default=64,
                        help="grid size (default 64; the demo's map word packing"
                             " supports future 128)")
    parser.add_argument("--min-len", type=float, default=32.0,
                        help="ignore one-sided linedefs shorter than this many map units")
    parser.add_argument("--out", type=Path, required=True, help="output directory")
    args = parser.parse_args(argv)
    if args.freedoom:
        level = load_freedoom(args.freedoom, args.map, args.grid, args.min_len)
    else:
        level = load_iwad(args.wad, args.map, args.grid, args.min_len)
    emit(level, args.out)
    print(json.dumps(level.stats))
    print(level.family_table())
    print(f"spawn {level.spawn} heading {level.heading}")
    print(f"wrote {args.out}/level.json (+ map/title/families/overhead/title.png)")


if __name__ == "__main__":
    main()
